'use client'
import {useId,useState} from 'react'
import {AdversityFigure,AdversityCanvas,AdversityPair,AdversityThree,Text,Box,Wire,Select,Tokens} from './security-adversity-primitives'
import {memoryDataReview,peerBoundary,conditionalObservation} from '../../lib/security-adversity-model.mjs'
const paths=[['記憶','書込 → 後で想起'],['知識源','取込 → 検索 → 文脈'],['toolの内容','定義・結果・error → 入力'],['Agent間','委譲 → 共有文脈'],['条件起動','潜伏 → 条件が揃う']]
export function AttackDelayedPaths({children}){
 const id=useId(),[missing,setMissing]=useState('none'),[input,setInput]=useState('result'),[condition,setCondition]=useState('absent'),memory=memoryDataReview({writeChecked:missing!=='write',sourceRecorded:missing!=='source',tenantMatched:missing!=='tenant'}),observed=conditionalObservation(condition==='present')
 return <AdversityFigure diagram="attack-delayed-paths" title="記憶・tool・Agent間で、後から指示に変わる経路" scene={({phase})=><AdversityCanvas diagram="attack-delayed-paths" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['五つの経路を、時間と受け渡しの境界で読む','書かれた記憶が、後のsessionで再び読まれる','知識源の取込と権限検索、生成の未信頼扱い','toolの定義・結果・errorも、外部の内容として読む','内部のAgent間にも、内容と権限の境界がある','条件が揃わない観測は、全条件の安全でない'][stage]}</Text>
 {stage===0&&<>{paths.map((r,i)=><g key={r[0]}><rect x={40} y={78+i*58} width={560} height={48} rx={6} fill="#142b39" stroke="#526b7c"/><Text x={144} y={110+i*58} small>{r[0]}</Text><Text x={423} y={110+i*58} small>{r[1]}</Text></g>)}</>}
 {stage===1&&<><Box x={36} y={86} width={174} height={116} title="書込時" lines={['出所・書込主体','権限と検証']} tone="amber"/><Box x={246} y={86} width={150} height={116} title="保存する" lines={['共有memory','出所を記録']} tone="purple"/><Box x={432} y={86} width={174} height={116} title="後のsession" lines={['権限内で想起','未信頼のdata']}/><Wire id={id} d="M210 145H244" active phase={phase}/><Wire id={id} d="M396 145H430" active phase={phase}/><Box x={116} y={253} width={408} height={111} title={memory.reviewCandidate?'記憶の扱いを検討':'不足する書込・出所・権限へ'} lines={['保存済みでも命令や正解にはしない','想起時にも未信頼扱いを保つ']}/></>}
 {stage===2&&<><AdversityThree columns={[["取込","作者と出所を確認","混入と権限を点検"],["検索","本人・tenant","閲覧範囲の認可"],["生成","文脈は未信頼","上位命令にしない"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Text y={345}>参照情報は、正しさや安全性の保証ではない</Text></>}
 {stage===3&&<AdversityPair left={[input==='definition'?'toolの定義':input==='error'?'toolのerror':'toolの結果','説明や返された内容','接続に成功した相手','内容の作者を確認']} right={['modelへ入るdata','外部からの未信頼入力','認証を内容の信頼にしない','引数・実権限は実行側で制限']} id={id} phase={phase}/>}
 {stage===4&&<><Box x={36} y={87} width={176} height={141} title="外部の内容" lines={['一体への入力','作者は別']} tone="amber"/><Box x={244} y={87} width={152} height={141} title="Agent A" lines={['限定した権限','委譲の提案']} tone="purple"/><Box x={428} y={87} width={176} height={141} title="Agent B" lines={['B自身の権限','親の制約を保持']}/><Wire id={id} d="M212 157H242" active phase={phase}/><Wire id={id} d="M396 157H426" active phase={phase}/><Text y={292}>peer出力を上位命令にしない</Text><Text y={343}>委譲で新しい権限を増やさない</Text></>}
 {stage===5&&<><AdversityPair left={['条件の違い','時間・入力・内部状態','通常時には未発火','条件別に評価する']} right={[observed.path==='trigger-condition-present'?'起動条件が存在する':'起動を観測していない','未発火は全安全でない','継続監視と多様なcase','図は攻撃を実行しない']} id={id} phase={phase}/><Text y={346}>単発の正常結果から、潜伏経路の不在を確定しない</Text></>}
 <Text y={412} small>防御経路の模式図。攻撃payload・実メモリ・接続は生成しない。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===1?<Select label="記憶の取扱いで不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="none">全条件を確認</option><option value="write">書込検証</option><option value="source">出所記録</option><option value="tenant">tenantと権限</option></Select>:stage===3?<Select label="toolから入る内容" value={input} onChange={setInput} ready={ready}><option value="definition">定義</option><option value="result">結果</option><option value="error">error</option></Select>:stage===5?<Select label="条件起動の観測" value={condition} onChange={setCondition} ready={ready}><option value="absent">起動条件を観測しない</option><option value="present">起動条件が存在する</option></Select>:null}>{children}</AdversityFigure>
}
const map=[['記憶','書込検証・出所・権限・想起の未信頼'],['知識源','取込検証・権限検索・生成の未信頼'],['tool','認証と内容の信頼を分ける'],['Agent間','最小権限・親の制約・重要な委譲の確認'],['条件起動','条件別の評価・継続監視']]
export function AttackPropagationControls({children}){
 const id=useId(),[missing,setMissing]=useState('none'),result=peerBoundary({sourceRecorded:missing!=='source',rightsLimited:missing!=='rights',parentGatePreserved:missing!=='gate'})
 return <AdversityFigure diagram="attack-propagation-controls" title="入口の検証・権限・確認を、各経路の境界へ置く" scene={({phase})=><AdversityCanvas diagram="attack-propagation-controls" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['五類型を、既存の防御へ対応づける','書込・取込・検索の制約を、modelの前に置く','各Agentの権限で、波及できる範囲を限定する','重要な委譲は、親の制約と人の確認を保つ','多様な条件と更新を、受入・回帰・観測へ戻す'][stage]}</Text>
 {stage===0&&<>{map.map((r,i)=><g key={r[0]}><rect x={40} y={78+i*58} width={560} height={48} rx={6} fill="#142b39" stroke="#526b7c"/><Text x={110} y={110+i*58} small>{r[0]}</Text><Text x={407} y={110+i*58} small>{r[1]}</Text></g>)}</>}
 {stage===1&&<><AdversityThree columns={[["dataの入口","書込・取込の検証","出所と形式"],["取得前の認可","本人・対象・","tenant","検索範囲を限定"],["modelの文脈","未信頼のdata","上位命令にしない"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Text y={345}>保存や引用によって、内容の信頼を昇格しない</Text></>}
 {stage===2||stage===3?<><Tokens labels={['出所','最小権限','親の制約']} selected={[['source','rights','gate'].indexOf(missing)]} y={88}/><AdversityPair left={['委譲する側','出所を記録','scopeと対象を限定','重要な委譲を確認']} right={[result.reviewCandidate?'委譲設計の検討候補':'不足する境界へ戻る','peer出力は未信頼','親の制約を保持','図は権限を増やさない']} id={id} phase={phase} y={203} height={171}/></>:null}
 {stage===4&&<><AdversityThree columns={[["条件別の評価","通常と発火条件","記憶・受け渡し"],["版と構成の変更","差分審査と再試用","scopeへ戻す"],["運用の観測","新しい経路を記録","回帰と地図へ"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Wire id={id} d="M520 269V331H120V271" active phase={phase}/><Text y={365} small>一回のreviewや正常出力を、全経路の安全にしない。</Text></>}
 <Text y={412} small>全ての受け渡しは未信頼。各Agentの権限と実行側の制約を保つ。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===2||stage===3?<Select label="Agent間で不足する境界" value={missing} onChange={setMissing} ready={ready}><option value="none">全条件を確認</option><option value="source">出所記録</option><option value="rights">最小権限</option><option value="gate">親の制約と確認</option></Select>:null}>{children}</AdversityFigure>
}
