'use client'
import {useId,useState} from 'react'
import {LifecycleCanvas,LifecycleFigure,LifecyclePair,LifecycleThree,Text,Box,Wire,Select,Tokens} from './deployment-lifecycle-primitives'
import {executionRoute,effectRecovery,toyApiCapacity,fallbackPlan,shadowAllowance} from '../../lib/deployment-lifecycle-model.mjs'
export function DeploymentStateExecution({children}){
 const id=useId(),[tail,setTail]=useState('8'),[contract,setContract]=useState('none'),route=executionRoute({tail:Number(tail),syncLimit:5}),recovery=effectRecovery({outcomeKnown:false,receiverContract:contract==='receiver',atomicUpdate:contract==='atomic'})
 return <LifecycleFigure diagram="deployment-state-execution" title="実行形態と外部状態、再開する副作用の契約" scene={({phase})=><LifecycleCanvas diagram="deployment-state-execution" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['Agentの三つの制約を、別の上限として読む','workerが入れ替わっても、状態は外に残す','要求の待ち方と、実行環境の寿命で選ぶ','平均が短くても、tailが同期上限を超え得る','再開点と履歴を、workerのmemoryから分ける','結果不明を、契約なしの再送にしない'][stage]}</Text>
 {stage===0&&<LifecycleThree columns={[["長い処理","toolとloop","timeout"],["外部API","RPM・TPM","retryの上限"],["token費用","要求数と別","長い思考も"]]}/>}
 {stage===1&&<><Box x={40} y={78} width={160} height={112} title="受付とqueue" lines={['jobを受け付け','進捗を返す']}/><Wire id={id} d="M200 135H238" active phase={phase}/><Box x={240} y={78} width={160} height={112} title="worker" lines={['独立して処理','交換と増減']}/><Wire id={id} d="M400 135H438" active phase={phase}/><Box x={440} y={78} width={160} height={112} title="provider" lines={['外部API','代替の条件']}/><Wire id={id} d="M320 190V243" active phase={phase}/><Box x={110} y={245} width={420} height={117} title="外部の状態と成果物" lines={['履歴・checkpoint・処理済み記録','workerの交換と分けて保持する']} tone="violet"/></>}
 {stage===2&&<><Tokens labels={['同期','job','常駐','serverless']} y={90}/><LifecyclePair left={['利用者の待ち方','同期: HTTPの時間内','job: 受付と進捗を返す','対話UIでもjobを使える']} right={['実行環境の寿命','常駐: 自分で上限を持つ','serverless: 制限を照合','cold startと外部状態']} id={id} phase={phase} y={180} arrow={false}/></>}
 {stage===3&&<><Text y={100}>{`模式の同期上限 5 ／ tail ${tail}`}</Text><rect x={60} y={137} width={520} height={26} rx={5} fill="#112638"/><rect x={60} y={137} width={Number(tail)*52} height={26} rx={5} fill="#66dac8"/><line x1={320} x2={320} y1={123} y2={179} stroke="#e9bf69" strokeWidth={3}/><LifecyclePair left={['測る時間の分布','p95〜p99を観測する','平均だけで決めない','図の時間は無単位']} right={[route.next==='job-progress-review'?'進捗付きjobを検討':'同期経路を検討','容量・再開も点検する','模式条件は実測でない','図はjobを実行しない']} id={id} phase={phase} y={203}/></>}
 {stage===4&&<><Tokens labels={['tool前','実行','結果記録','次のphase']} selected={[2]} y={90}/><LifecyclePair left={['process内のmemory','worker交換で失う','affinityだけでは不足','状態を外部へ分ける']} right={['再開できる状態','会話と成果物の参照','tool間のcheckpoint','保存・読取りも検証']} id={id} phase={phase} y={183}/></>}
 {stage===5&&<LifecyclePair left={['結果不明の外部作用','事前の確認だけでは不足','受信側の冪等契約','または同じDBで原子反映']} right={[recovery.next==='stop-and-reconcile'?'自動再送を止め照合':'回復契約を検討','業務キーと処理済み記録','実結果を別に確認する','図は再送しない']} id={id} phase={phase}/>}
 <Text y={412} small>HTTPの切断は処理・課金の取消ではない。図は実復旧を行わない。</Text>
 </>}</LifecycleCanvas>} controls={({stage,ready})=>stage===3?<Select label="模式のtail時間" value={tail} onChange={setTail} ready={ready}><option value="3">3 単位</option><option value="5">5 単位</option><option value="8">8 単位</option></Select>:stage===5?<Select label="結果不明時の回復契約" value={contract} onChange={setContract} ready={ready}><option value="none">どちらも未確認</option><option value="receiver">受信側の冪等契約</option><option value="atomic">同じDBの原子的反映</option></Select>:null}>{children}</LifecycleFigure>
}
export function DeploymentCapacityFallback({children}){
 const id=useId(),[loop,setLoop]=useState('3'),[missing,setMissing]=useState('quality'),[shadow,setShadow]=useState('4')
 const capacity=toyApiCapacity({tasks:3,tokens:4,loopBound:Number(loop),rpm:10,tpm:30}),fallback=fallbackPlan({alternativeEvaluated:missing!=='quality',switchRule:missing!=='switch',returnRule:missing!=='return',available:missing!=='down'}),allowance=shadowAllowance({oldDemand:7,newDemand:Number(shadow),limit:10})
 return <LifecycleFigure diagram="deployment-capacity-fallback" title="外部APIの容量と、切替・展開の条件" scene={({phase})=><LifecycleCanvas diagram="deployment-capacity-fallback" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['server台数とproviderの枠を分けて読む','loop上限とtokenを、流入と待ち時間へ結ぶ','品質・切替・復帰の条件を先に評価する','すべてのproviderが止まる場合も設計する','shadowの新旧両方を、容量計画へ含める','増設やHTTP切断だけでは、残る作用を消せない'][stage]}</Text>
 {stage===0&&<LifecyclePair left={['自分の実行基盤','worker数・CPU・memory','同時実行を制御する','serverだけ増やさない']} right={['外部のprovider枠','RPM: 要求の数','TPM: tokenの量','枠の時点と契約を照合']} id={id} phase={phase} arrow={false}/>}
 {stage===1&&<><Tokens labels={['流入','優先度','queue','同時実行','外部枠']} selected={[3]} y={88}/><LifecyclePair left={['模式の需要','3 task × loop上限',`呼出し ${capacity.calls} ／ RPM枠 10`,`token ${capacity.tokenDemand} ／ TPM枠 30`]} right={[capacity.rpmWithin&&capacity.tpmWithin?'両方の枠を照合':'超える枠から調整','対話とbatchを分ける','queue waitも観測する','値は無単位の模式入力']} id={id} phase={phase} y={181}/></>}
 {stage===2||stage===3?<LifecyclePair left={['切替前の評価','代替modelの品質','切替と復帰の条件','要求／providerのtrace']} right={[fallback.next==='stop-or-queue'?'受付停止か後続queue':fallback.next==='fallback-review'?'fallbackの検討候補':'不足する条件を評価','全停止時も分けて設計','切替先の品質を保護','図は実切替しない']} id={id} phase={phase}/>:null}
 {stage===4&&<><LifecycleThree columns={[["旧経路","需要 7","本処理の枠"],["shadow",`追加 ${shadow}`,"比較にも費用"],["合計",`需要 ${allowance.combined}`,"枠は10単位"]]}/><Text y={330}>{allowance.within?'追加容量を照合':'両経路で枠を超える'}</Text><Text y={364} small>canaryで小さく展開し、品質と容量を観測して戻る。</Text></>}
 {stage===5&&<LifecycleThree columns={[["切断後の処理","中身が継続","課金も残る"],["memoryの消失","stateを外へ","再開点を記録"],["retry storm","枠を奪い合う","流入を制御"]]}/>}
 <Text y={412} small>模式の枠は実契約ではない。要求数だけでtoken費用を管理しない。</Text>
 </>}</LifecycleCanvas>} controls={({stage,ready})=>stage===1?<Select label="模式のloop上限" value={loop} onChange={setLoop} ready={ready}><option value="1">1 回</option><option value="2">2 回</option><option value="3">3 回</option></Select>:stage===2||stage===3?<Select label="切替で不足する条件" value={missing} onChange={setMissing} ready={ready}>{Object.entries({quality:'代替の品質が未評価',switch:'切替条件が未設定',return:'復帰条件が未設定',down:'全providerが停止',none:'三条件を照合'}).map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:stage===4?<Select label="模式のshadow追加需要" value={shadow} onChange={setShadow} ready={ready}><option value="2">2 単位</option><option value="3">3 単位</option><option value="4">4 単位</option></Select>:null}>{children}</LifecycleFigure>
}
