'use client'
import {useId,useState} from 'react'
import {ContextCanvas,ContextFigure,ContextPair,ContextThree,Text,Box,Select,Tokens} from './evaluation-context-primitives'
import {evaluationEnvironmentLayer,evaluationReproducibility} from '../../lib/evaluation-context-model.mjs'
const layers={mock:['モック・スタブ','固定応答で速く測る','tool選択と引数','本番の乖離を保持'],state:['状態付き環境','DB・ファイルをシード','Agentの終了状態を照合','前ケースの作用を消す'],limited:['限定の本番接続','読み取り専用・少数','モックとの乖離を確認','実書込みへ広げない']}
export function EnvironmentLayersState({children}){
 const id=useId(),[layer,setLayer]=useState('state'),[final,setFinal]=useState('wrong'),scope=evaluationEnvironmentLayer(layer)
 return <ContextFigure diagram="environment-layers-state" title="評価の環境と、初期・終了状態を測る層" scene={({phase})=><ContextCanvas diagram="environment-layers-state" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['何を測るか、どこで実行するかを分担する','測る対象から、必要な環境の層を選ぶ','各ケースを、既知の初期状態から始める','会話の宣言と、実際の終了状態を区分する','少数の読み取りで、乖離を検知する'][stage]}</Text>
  {stage===0?<ContextPair id={id} phase={phase} arrow={false} left={['評価用の環境','本番データを触らず','シードとリセット','繰返し比較できる']} right={['別の責任','採点・データセット','継続して回すCI','セキュリティ隔離']}/>:stage===1?<>
   <Tokens labels={['モック','状態付き','限定本番']} selected={[Object.keys(layers).indexOf(layer)]} y={91}/>
   <Box x={64} y={200} width={512} height={183} title={layers[layer][0]} lines={layers[layer].slice(1)} tone="violet" data-evaluation-environment-target={scope.target} data-evaluation-read-only={String(scope.readOnly)} data-evaluation-environment-created="false" data-evaluation-security-guaranteed="false"/>
  </>:stage===2?<ContextPair id={id} phase={phase} left={['ケース前のリセット','前の作用を持ち込まない','既知のDB・ファイル','時刻と外部状態も確認']} right={['同じ入力で実行','状態も同じ条件へ','経路と結果を記録','終了後に照合']}/>:stage===3?<ContextPair id={id} phase={phase} arrow={false} left={['会話の宣言','Agent: 完了しました','言葉だけで採点せず','必要な回答も照合']} right={[final==='match'?'模式の終了状態は一致':'模式の終了状態は不一致',final==='match'?'DBの対象と値は一致':'DBの対象と値に差','正解状態を別に保つ','途中の遵守も別に点検']}/>:<ContextPair id={id} phase={phase} arrow={false} left={['モックの簡略化','空・エラー・大量応答','本番API変更で更新','保守の費用を伴う']} right={['限定した本番照合','読み取り専用・少数','乖離を定期に検知','危険と準備を制限']}/>}
 </>}</ContextCanvas>} controls={({stage,ready})=>stage===1?<Select label="評価で必要な環境の層" value={layer} onChange={setLayer} ready={ready}>{Object.entries(layers).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===3?<Select label="宣言と別に照合する模式状態" value={final} onChange={setFinal} ready={ready}><option value="wrong">完了宣言・状態は違う</option><option value="match">完了宣言・状態は一致</option></Select>:null}>{children}</ContextFigure>
}
export function EnvironmentReproFidelity({children}){
 const id=useId(),[missing,setMissing]=useState('state'),result=evaluationReproducibility({stateReset:missing!=='state',timeFixed:missing!=='time',seedFixed:missing!=='seed',externalFixed:missing!=='external'})
 return <ContextFigure diagram="environment-repro-fidelity" title="環境の再現性、残る揺れと忠実度の保守" scene={({phase})=><ContextCanvas diagram="environment-repro-fidelity" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['環境側の揺れを、消せる範囲で減らす','Agentの揺れは、固定した環境でも残る','必要な忠実度と、更新する費用を読む','環境の準備・後片付けをCIへ載せる','入力と状態を合わせて、失敗を再現する'][stage]}</Text>
  {stage===0?<Box x={64} y={104} width={512} height={219} title={result.conditionsMatched?'環境の条件を照合した候補':'固定できていない条件が残る'} lines={['初期状態のリセット・時刻','乱数とID・外部応答','固定はAgentの決定性を保証しない','図は実環境を作成しない']} tone={result.conditionsMatched?'teal':'amber'} data-evaluation-repro-matched={String(result.conditionsMatched)} data-evaluation-agent-deterministic="false" data-evaluation-environment-created="false"/>:stage===1?<ContextPair id={id} phase={phase} arrow={false} left={['固定する環境条件','同じ初期状態と時刻','同じ外部応答・ID','前ケースの漏れを防ぐ']} right={['残るAgentの揺れ','LLMの出力と対話','同じ条件で反復実行','頻度と成否を集計']}/>:stage===2?<ContextPair id={id} phase={phase} left={['API変更と実際の応答','通常・空・大量・エラー','乖離を限定接続で検知','必要な忠実度を判断']} right={['モックも更新する','単純化を点検','変更運用に組み込む','速さと保守費用を読む']}/>:stage===3?<ContextThree columns={[['準備と終了','seed・reset','cleanupも行う','CIのステップへ','手動依存を減らす'],['実行頻度','速いモックは頻繁','重い状態付きは節目','回帰の層と接続'],['実行予算','LLMと環境の費用','重要ケースと標本','全量を同頻度にせず']]}/>:<ContextPair id={id} phase={phase} left={['本番の失敗','この入力＋この状態','状態をシードへ保存','再現する評価ケース']} right={['修正して回帰へ','環境で失敗を再現','修正を同条件で確認','継続スイートに残す']}/>}
 </>}</ContextCanvas>} controls={({stage,ready})=>stage===0?<Select label="評価環境の未固定条件" value={missing} onChange={setMissing} ready={ready}><option value="state">初期状態のリセット</option><option value="time">時刻</option><option value="seed">乱数とID</option><option value="external">外部応答</option><option value="none">必要条件を照合</option></Select>:null}>{children}</ContextFigure>
}
