'use client'
import {useId,useState} from 'react'
import {AuthorityFigure,AuthorityCanvas,AuthorityPair,AuthorityThree,Text,Box,Wire,Select,Tokens} from './security-authority-primitives'
import {imageFetchReview,retrievalAuthorization} from '../../lib/security-authority-model.mjs'
const routes={response:['応答の混入','権限外dataが応答へ','取得側で認可を強制'],tool:['送信系tool','mail・ticket・APIへ','宛先・内容・承認'],url:['リンクと画像URL','path/queryのdataが外へ','取得前の宛先・内容検証'],log:['ログ・trace','全文が広く長く残る','masking・権限・保持'],memory:['memory・履歴','別user・tenantへ再登場','保存・想起の分離'],service:['外部service','保持・学習・再提供','契約・最小化・設定']}
export function ExfiltrationRoutesUrl({children}){
 const id=useId(),[route,setRoute]=useState('url'),[mode,setMode]=useState('proxy'),[missing,setMissing]=useState('redirect'),fetching=imageFetchReview({automaticFetch:mode!=='blocked',destinationAllowed:missing!=='destination',urlContentChecked:missing!=='content',redirectControlled:missing!=='redirect'})
 return <AuthorityFigure diagram="exfiltration-routes-url" title="六つの漏えい経路と、画像URLを取得する前の制約" scene={({phase})=><AuthorityCanvas diagram="exfiltration-routes-url" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['攻撃者の指示がなくても、設計不備でdataが混ざる','応答・tool・URL・ログ・memory・外部serviceを調べる','URLを書けることも、外へ届く通信経路になる','proxyが同じURLを取りに行けば、dataは上流へ届く','取得前に宛先・内容・redirectをすべて制約する','保存先と外部serviceの契約・保持も点検する'][stage]}</Text>
 {stage===0&&<AuthorityPair left={['攻撃による持出し','未信頼の内容から指示','私有dataを読む','外部送信へ導く']} right={['設計不備による事故','取得するdataの範囲が広い','応答・ログへ混ざる','別user・tenantへ再登場']} id={id} phase={phase} arrow={false}/>}
 {stage===1&&<>{Object.entries(routes).map(([v,a],i)=><Box key={v} x={42+(i%2)*285} y={78+Math.floor(i/2)*100} width={270} height={89} title={a[0]} lines={[a[2]]} tone={route===v?'teal':'purple'}/>)}<Text y={388} small>送信toolがなくても、表示・保存・外部サービスの経路が残る。</Text></>}
 {stage===2||stage===3?<><Box x={35} y={85} width={190} height={142} title="応答のURL" lines={['path / queryへ','機微なdataを埋める','ここでは模式記号だけ']} tone="amber"/><Box x={275} y={85} width={140} height={142} title={mode==='proxy'?'proxy':mode==='blocked'?'取得なし':'表示側'} lines={[mode==='blocked'?'自動取得を停止':'画像を自動取得',mode==='proxy'?'IPを隠す機能':'取得前の制約']} /><Box x={465} y={85} width={140} height={142} title="上流の宛先" lines={["同じpath/","query",'dataが届き得る']} tone="amber"/><Wire id={id} d="M225 155H273" active={mode!=='blocked'} phase={phase}/><Wire id={id} d="M415 155H463" active={mode!=='blocked'} phase={phase}/><Text y={290}>{mode==='blocked'?'自動取得の経路を閉じる':mode==='proxy'?'IPを隠しても、URLの内容は上流へ届く':'画像の自動取得が外部通信になる'}</Text><Text y={344} small>リンクのクリックや他の通信経路は別に制約する。</Text></>:null}
 {stage===4&&<><Tokens labels={['宛先','path/query','redirect']} selected={missing==='none'?[0,1,2]:[]} y={86}/><AuthorityPair left={['取得前の三つの制約','管理画像IDからURLへ','許可宛先・内容を検証','redirect停止／遷移先も検証']} right={[fetching.automaticPathBlocked?'自動取得の経路を閉じる':fetching.reviewCandidate?'取得設計の検討候補':'不足する制約へ戻る','proxyだけで保護しない','他の通信経路も別に点検','図は実取得しない']} id={id} phase={phase} y={180}/></>}
 {stage===5&&<AuthorityThree columns={[["ログ・trace","masking・アクセス","保持期間を制限"],["memory・履歴","user / tenant","分離","共有に書く範囲"],["外部service","利用契約と設定","送信量を最小化"]]}/>}
 <Text y={412} small>模式URLだけを表示。実秘密・リンク操作・画像通信は行わない。</Text>
 </>}</AuthorityCanvas>} controls={({stage,ready})=>stage===1?<Select label="棚卸しする漏えい経路" value={route} onChange={setRoute} ready={ready}>{Object.entries(routes).map(([v,a])=><option key={v} value={v}>{a[0]}</option>)}</Select>:stage===2||stage===3?<Select label="画像URLの模式取得方法" value={mode} onChange={setMode} ready={ready}><option value="direct">直接の自動取得</option><option value="proxy">同じURLをproxyが取得</option><option value="blocked">画像の自動取得を停止</option></Select>:stage===4?<><Select label="画像取得の有無" value={mode} onChange={setMode} ready={ready}><option value="direct">自動取得を行う設計</option><option value="proxy">proxyで取得する設計</option><option value="blocked">自動取得なし</option></Select><Select label="URL取得で不足する制約" value={missing} onChange={setMissing} ready={ready}><option value="destination">宛先が未検証</option><option value="content">URL内容が未検証</option><option value="redirect">redirectが未制御</option><option value="none">三制約を照合</option></Select></>:null}>{children}</AuthorityFigure>
}
export function ExfiltrationStructureAuthorization({children}){
 const id=useId(),[boundary,setBoundary]=useState('send'),[missing,setMissing]=useState('tenant'),auth=retrievalAuthorization({userAllowed:missing!=='user',tenantMatched:missing!=='tenant',resourceAllowed:missing!=='resource'}),removed={data:['公開dataだけを渡す','非公開dataを接続しない','保存・検索の対象も点検'],input:['管理された入力に限定','作者と取り込み経路を管理','社内保管だけで信頼しない'],send:['外部への送信先を制限','表示・ログ・URLも点検','無承認の自動送信を止める']}
 return <AuthorityFigure diagram="exfiltration-structure-authorization" title="三重奏を経路全体で崩し、取得する前に認可する" scene={({phase})=><AuthorityCanvas diagram="exfiltration-structure-authorization" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['一要素を外すなら、全ての経路を確認する','data・作者・送信先のどこを閉じるか選ぶ','社内保管でも、内容の作者が信頼済みとは限らない','承認対象外の画像取得や、子の出力を放置しない','権限外のdataを、modelへ入れる前に止める','出力検知は最後の網。取得認可を置き換えない'][stage]}</Text>
 {stage===0&&<AuthorityThree columns={[["dataを読む","取得と保存の範囲","私有dataの有無"],["内容に触れる","作者と取り込み","社内文書も点検"],["外へ送る","tool・URL・ログ","経路全体で制約"]]}/>}
 {stage===1&&<AuthorityPair left={removed[boundary]} right={['三条件が必要な業務','送信先と内容を明示','実行前に人間が承認','承認外の経路も制御']} id={id} phase={phase} arrow={false}/>}
 {stage===2&&<AuthorityPair left={['社内に保存した資料','転記mail・外部の記述','検索結果や子の要約','内容は非信頼のdata']} right={['親に残す制約','命令や権限の根拠にしない','元の作者と出所を読む','親のscopeと承認を維持']} id={id} phase={phase} arrow={false}/>}
 {stage===3&&<AuthorityThree columns={[["送信tool","宛先・内容を提示","実行前の承認"],["応答のURL","取得前の検証","redirectも制約"],["役割の分割","子の要約はdata","親の権限を維持"]]}/>}
 {stage===4||stage===5?<><Box x={35} y={88} width={200} height={143} title="取得する側で認可" lines={["user・tenant・","resource",auth.mayEnterModel?'三条件を照合':'不足する条件を遮断','出力検知とは別に強制']}/><Wire id={id} d="M235 160H293" active={auth.mayEnterModel} phase={phase}/><Box x={295} y={88} width={160} height={143} title="modelへ渡す" lines={[auth.mayEnterModel?'許可範囲の候補':'権限外を渡さない','取得前の制約']} tone="purple"/><Wire id={id} d="M455 160H490" active={auth.mayEnterModel} phase={phase}/><Box x={493} y={88} width={112} height={143} title="応答" lines={['出力検知','最後の網']} tone="amber"/><Text y={292}>{auth.mayEnterModel?'取得設計の検討候補':'modelへ入れる前に戻す'}</Text><Text y={345} small>検知が合格しても、権限外dataをmodelへ渡さない。</Text></>:null}
 <Text y={412} small>Web無効化は攻撃面の縮小。作者と全通信経路の制御は別に確認する。</Text>
 </>}</AuthorityCanvas>} controls={({stage,ready})=>stage===1?<Select label="経路全体から外す要素" value={boundary} onChange={setBoundary} ready={ready}><option value="data">非公開data</option><option value="input">信頼できない内容</option><option value="send">外部送信</option></Select>:stage===4||stage===5?<Select label="取得認可で不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="user">userの許可が不足</option><option value="tenant">tenantの照合が不足</option><option value="resource">resourceの範囲が不足</option><option value="none">三条件を照合</option></Select>:null}>{children}</AuthorityFigure>
}
