'use client'
import {useId,useState} from 'react'
import {QualityCanvas,QualityFigure,QualityPair,QualityThree,Text,Box,Select,Tokens} from './quality-trace-primitives'
import {counterfactualComparison,stratifiedCounts,fairnessRemediation} from '../../lib/quality-trace-model.mjs'
const types={quality:['グループ間の品質差','層ごとの成功率・正確さ','名前・方言・業種など','全体平均だけを見ない'],stereotype:['表現の固定観念','生成内容を分析する','職業と属性の紋切り型','品質率だけでは分からない'],refusal:['拒否率の偏り','同種の依頼を比較する','過剰な警告・拒否の差','依頼の条件を固定する']}
const percent=v=>v===null?'母数なし':`${Math.round(v*100)}%`
export function FairnessTypesMeasurement({children}){
 const id=useId(),[type,setType]=useState('quality'),[pair,setPair]=useState('attribute'),[different,setDifferent]=useState('yes'),[sample,setSample]=useState('hidden')
 const result=counterfactualComparison({attributeOnly:pair!=='request',requestFixed:pair!=='request',otherFixed:pair!=='other',different:different==='yes'}),counts=stratifiedCounts(sample==='empty'?[{total:10,correct:9},{total:0,correct:0}]:sample==='equal'?[{total:10,correct:5},{total:2,correct:1}]:[{total:10,correct:9},{total:2,correct:1}])
 return <QualityFigure diagram="fairness-types-measurement" title="偏りの類型、対照ペアと層別の母数" scene={({phase})=><QualityCanvas diagram="fairness-types-measurement" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['品質差と表現の偏りを、測って改善へ回す','類型に応じて、測る対象を切り替える','変える属性以外は、同じ条件で比べる','全体と層ごとの率を、母数付きで読む','観点と指標を、測る前に定める'][stage]}</Text>
  {stage===0?<QualityPair id={id} phase={phase} arrow={false} left={['技術で測る対象','どの属性・どの指標','どれだけ差があるか','評価と改善を継続']} right={['判断をつなぐ先','タスクの影響と合意','規制・法務の統制','技術だけで決めない']}/>:stage===1?<>
   <Tokens labels={['品質差','固定観念','拒否の差']} selected={[Object.keys(types).indexOf(type)]} y={88}/><Box x={64} y={191} width={512} height={190} title={types[type][0]} lines={types[type].slice(1)} tone="violet" data-fairness-bias-type={type}/>
  </>:stage===2?<>
   <QualityPair id={id} phase={phase} arrow={false} left={['対照ペアの入力','属性A → 属性B',pair==='request'?'依頼も変わった':'依頼は同じ',pair==='other'?'他の条件も変わった':'他の条件は同じ']} right={[result.pairReady?'同じ条件で比較する候補':'対照条件を整え直す',result.differenceToReview?'模式の出力差を点検':'差の観点を保持','差だけで法的判定せず','図はLLMを実行しない']}/>
   <g data-fairness-pair-ready={String(result.pairReady)} data-fairness-difference-review={String(result.differenceToReview)} data-fairness-legal-determined="false" data-fairness-model-executed="false"/>
  </>:stage===3?<>
   {[{name:'全体',...counts},{name:'層A',...counts.groups[0]},{name:'層B',...counts.groups[1]}].map((row,i)=><g key={row.name}><Text x={50} y={104+i*97} anchor="start" small>{`${row.name}: ${row.correct}/${row.total}`}</Text><rect x={180} y={86+i*97} width={340} height={31} rx={6} fill="#17313c"/>{row.rate!==null&&<rect x={180} y={86+i*97} width={340*row.rate} height={31} rx={6} className={i===2?'qt-bar-amber':'qt-bar-teal'}/>}<Text x={625} y={105+i*97} anchor="end">{percent(row.rate)}</Text></g>)}
   <Text y={393} small>模式の層。母数なしは0%にせず、実集団の成績にしない。</Text>
   <g data-fairness-overall-rate={counts.rate??'unavailable'} data-fairness-small-rate={counts.groups[1].rate??'unavailable'} data-fairness-guaranteed="false"/>
  </>:<QualityThree columns={[['先に設計','属性・グループ','測る指標と差','観点自体が判断'],['二つの手法','対照条件を固定','層ごとの母数','観点の外も残る'],['本番へ続ける','主要な層で監視','対策後も測定','全偏り消失にせず']]}/>}
 </>}</QualityCanvas>} controls={({stage,ready})=>stage===1?<Select label="測定する偏りの類型" value={type} onChange={setType} ready={ready}>{Object.entries(types).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===2?<><Select label="対照ペアで変える条件" value={pair} onChange={setPair} ready={ready}><option value="attribute">属性だけを変更</option><option value="request">依頼も変更</option><option value="other">他の条件も変更</option></Select><Select label="選択する模式の出力差" value={different} onChange={setDifferent} ready={ready}><option value="yes">差がある</option><option value="no">差がない</option></Select></>:stage===3?<Select label="公平性で読む模式の集計" value={sample} onChange={setSample} ready={ready}><option value="hidden">全体平均に隠れる層の差</option><option value="equal">この指標の率は同じ</option><option value="empty">層Bの母数がない</option></Select>:null}>{children}</QualityFigure>
}
export function FairnessJapaneseRemediation({children}){
 const id=useId(),[missing,setMissing]=useState('limits'),result=fairnessRemediation({limitsMeasured:missing!=='limits',japaneseIncluded:missing!=='japanese',criteriaDefined:missing!=='criteria',stakeholdersIncluded:missing!=='stakeholders'})
 return <QualityFigure diagram="fairness-japanese-remediation" title="日本語の偏りと、対策後に残る測定" scene={({phase})=><QualityCanvas diagram="fairness-japanese-remediation" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['英語圏のセットにない観点を、自前で設計する','異なる手段の限界を、並べて読む','対応済みの宣言から、残る偏りの測定へ戻す','公平性で、何を等しくするかを明示する','影響と関係者の合意から、許容範囲を決める'][stage]}</Text>
  {stage===0?<QualityThree columns={[['名前','姓名・読みの多様性','外国由来の名前','品質とトーンの差'],['方言・地域','標準語以外の入力','同じ依頼の品質','日本語の層を設計'],['待遇表現','相手と属性の条件','敬語の不当な差','産出品質と隣接']]}/>:stage===1?<QualityThree columns={[['prompt','手軽な指示','確実ではない','実挙動を測る'],['出力ガード','検知とブロック','網羅性に限界','検知漏れを測る'],['調整データ','FT・few-shot','費用と新たな偏り','対策後も測る']]}/>:stage===2?<Box x={64} y={102} width={512} height={219} title={result.reviewCandidate?'合意へ進む検討候補':'不足する測定と設計へ戻る'} lines={['残る偏り・日本語の観点','評価する指標・関係者の合意','必要条件の照合は公平の保証ではない','図は対策を実行しない']} tone={result.reviewCandidate?'teal':'amber'} data-fairness-review-candidate={String(result.reviewCandidate)} data-fairness-guaranteed="false" data-fairness-remediation-executed="false"/>:stage===3?<QualityPair id={id} phase={phase} arrow={false} left={['複数の公平性指標','何を等しくするか','同時に満たせない場合','単一の完全公平にせず']} right={['残る偏りを測る','属性・指標・差を明示','対応の限界を保持','改善の測定を続ける']}/>:<QualityPair id={id} phase={phase} left={['測定とタスクの影響','どの属性にどんな差','不可逆性や影響度','許容範囲を明示']} right={['関係者と判断する','技術者だけで決めず','規制領域は統制へ','図は法務判断せず']}/>}
 </>}</QualityCanvas>} controls={({stage,ready})=>stage===2?<Select label="公平性対策後に不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="limits">残る偏りと限界の測定</option><option value="japanese">日本語の観点</option><option value="criteria">評価指標の定義</option><option value="stakeholders">関係者との合意</option><option value="none">必要条件を照合</option></Select>:null}>{children}</QualityFigure>
}
