'use client'
import {useId,useState} from 'react'
import {AuthorityFigure,AuthorityCanvas,AuthorityPair,AuthorityThree,Text,Box,Wire,Select,Tokens} from './security-authority-primitives'
import {intersectPermissions,tokenAudienceReview,credentialRoute,revocationReview} from '../../lib/security-authority-model.mjs'
const operationNames={read:'read',write:'write',delete:'delete',send:'send'}
export function IdentityDelegationScope({children}){
 const id=useId(),[user,setUser]=useState('writer'),[agent,setAgent]=useState('reader'),[missing,setMissing]=useState('audience'),sets={reader:['read'],writer:['read','write'],full:['read','write','delete','send'],none:[]},scope=intersectPermissions(sets[user],sets[agent]),token=tokenAudienceReview({correctAudience:missing!=='audience',unexpired:missing!=='expiry',scopeAllowed:missing!=='scope'})
 return <AuthorityFigure diagram="identity-delegation-scope" title="誰の代理か、誰が動くか、どの操作まで許すか" scene={({phase})=><AuthorityCanvas diagram="identity-delegation-scope" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['五つの問いは、異なる制御を設計する入口','自律型とユーザー代理型を、範囲と責任で選ぶ','共有の全権accountを、個別IDとownerへ分ける','subjectの代理として、actorが実際に行動する','宛先・期限・scopeを、それぞれ照合する','二つの権限集合の、共通する操作だけを取る','taskのscopeと、危険操作への承認を重ねる'][stage]}</Text>
 {stage===0&&<><Tokens labels={['認証','委任','認可','帰属','鍵の保護']} y={86}/><AuthorityPair left={['Agentの五つの問い','個別IDで識別する','誰の代理かを表す','何をしてよいかを絞る']} right={['行為と秘密の管理','誰の責任かを記録する','鍵はvaultと実行側へ','IDだけで認可は完成しない']} id={id} phase={phase} y={180} arrow={false}/></>}
 {stage===1&&<AuthorityPair left={['自律のservice account','特定userに依存しないtask','職務に必要な固定scope','ownerが管理・責任を持つ']} right={['userの代理','userごとにアクセスが変わる',"本人の権限と","Agent許可の交差",'委任したuserとownerを辿る']} id={id} phase={phase} arrow={false}/>}
 {stage===2&&<AuthorityThree columns={[["個別のID","Agentごとに発行","共有全権を避ける"],["ownerを付与","管理する人・team","責任を辿れる"],["失効の単位","廃止・異動・異常","個別に止める"]]}/>}
 {stage===3&&<><Box x={35} y={92} width={175} height={142} title="subject: user" lines={['誰の代理か','利用者の権限']} tone="purple"/><Wire id={id} d="M210 162H266" active phase={phase}/><Box x={270} y={92} width={180} height={142} title="actor: Agent" lines={['実際に動く主体','本人と識別を分ける']}/><Wire id={id} d="M450 162H493" active phase={phase}/><Box x={495} y={92} width={110} height={142} title="API" lines={["範囲と認可",'監査へ記録']}/><Text y={290}>subject ＋ actor ＋ task / session</Text><Text y={339} small>actの履歴は、権限の追加や全権の継承ではない。</Text></>}
 {stage===4&&<><Tokens labels={['短寿命','最小scope','audience']} selected={missing==='none'?[0,1,2]:[]} y={86}/><AuthorityPair left={['tokenの三つの境界','期限が切れていないか','この操作のscopeか','このserviceが宛先か']} right={[token.reviewCandidate?'token設計の検討候補':'不足する条件へ戻る','同じuserでも他宛先は別','実認可と署名等を検証','図はtokenを発行しない']} id={id} phase={phase} y={180}/></>}
 {stage===5&&<><Text y={89}>user権限 ∩ Agent許可 = 実効権限</Text>{['read','write','delete','send'].map((op,i)=><g key={op}><Text x={130+i*125} y={145}>{operationNames[op]}</Text><rect x={83+i*125} y={163} width={94} height={38} rx={5} fill={sets[user].includes(op)?'#493653':'#122637'} stroke="#aa99ec"/><rect x={83+i*125} y={215} width={94} height={38} rx={5} fill={sets[agent].includes(op)?'#214941':'#122637'} stroke="#65dac8"/><rect x={83+i*125} y={292} width={94} height={38} rx={5} fill={scope.effective.includes(op)?'#214941':'#122637'} stroke={scope.effective.includes(op)?'#65dac8':'#526b7c'}/></g>)}<Text x={50} y={188} small>user</Text><Text x={45} y={240} small>Agent</Text><Text x={42} y={317} small>交差</Text><Text y={375}>{scope.effective.length?`共通する操作: ${scope.effective.join(' / ')}`:'共通する操作はない'}</Text></>}
 {stage===6&&<AuthorityThree columns={[["taskのscope","必要時に追加要求","同意の契約を確認"],["危険操作の承認","scopeだけでは不足","内容と影響を示す"],["tool層の制約","許可toolと引数","identity層と","重ねる"]]}/>}
 <Text y={412} small>権限は和集合でなく交差。図は実認証・token発行・認可を行わない。</Text>
 </>}</AuthorityCanvas>} controls={({stage,ready})=>stage===4?<Select label="tokenで不足する境界" value={missing} onChange={setMissing} ready={ready}><option value="audience">audienceが一致しない</option><option value="expiry">期限が切れている</option><option value="scope">操作scopeが不足</option><option value="none">三境界を照合</option></Select>:stage===5?<><Select label="利用者の模式権限" value={user} onChange={setUser} ready={ready}>{Object.keys(sets).map(v=><option key={v} value={v}>{v==='reader'?'readのみ':v==='writer'?'readとwrite':v==='full'?'四操作': '操作なし'}</option>)}</Select><Select label="Agentの模式許可" value={agent} onChange={setAgent} ready={ready}>{Object.keys(sets).map(v=><option key={v} value={v}>{v==='reader'?'readのみ':v==='writer'?'readとwrite':v==='full'?'四操作':'操作なし'}</option>)}</Select></>:null}>{children}</AuthorityFigure>
}
export function IdentityAuditCredentials({children}){
 const id=useId(),[route,setRoute]=useState('egress'),[missing,setMissing]=useState('token'),credential=credentialRoute(route),revocation=revocationReview({tokenRevoked:missing!=='token',credentialsDisabled:missing!=='credentials',toolsBlocked:missing!=='tools'})
 return <AuthorityFigure diagram="identity-audit-credentials" title="帰属を辿る記録と、modelへ見せない資格情報" scene={({phase})=><AuthorityCanvas diagram="identity-audit-credentials" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['誰が、誰の委任で、どのtaskで動いたかを記録する','ownerと廃止・異常を、失効する手順へ結ぶ','modelへ見せる領域と、鍵を保管する領域を分ける','modelには記号、実行時にvaultの値を使う','接続先ごとの狭い鍵と、refresh・失効を管理する','自分宛てtokenと、上流APIへ使う鍵を分ける'][stage]}</Text>
 {stage===0&&<AuthorityThree columns={[["行為の主体","actor: Agent ID","人間と区別"],["委任の起点","subject: user","task・session"],["管理と調査","owner: 人・team","traceと突合せ"]]}/>}
 {stage===1&&<AuthorityPair left={['失効の三つの制御','tokenを失効する','資格情報を無効化する','toolの新しい実行を止める']} right={[revocation.futureControlCandidate?'今後の制御の検討候補':'残る制御へ戻る','廃止・異動・異常へ連動','実行済みの作用は残る','図は取消や失効を実行しない']} id={id} phase={phase}/>}
 {stage===2||stage===3?<><Box x={40} y={90} width={250} height={156} title={credential.modelVisible?'modelが鍵を読む':'modelには記号'} lines={credential.modelVisible?['prompt・履歴へ実値','抽出・出力で漏れ得る','後から削除も別に検証']:['<credential> の記号','実値は文脈へ入れない','鍵はvaultで管理']} tone={credential.modelVisible?'amber':'purple'}/><Box x={350} y={90} width={250} height={156} title={credential.executionInjected?'実行コードが注入':'秘密の可視範囲が広い'} lines={credential.executionInjected?['vaultから実行時に使用',route==='egress'?'送信時に記号を差し替え':'tool実行の瞬間に注入','refresh・失効は実行側']:['modelの拒否に頼れない','vaultへ保管する設計へ','既読秘密の削除は別問題']}/><Wire id={id} d="M290 168H348" active={!credential.modelVisible} phase={phase}/><Text y={304}>資格情報は実行側で、接続先ごとに最小化する</Text><Text y={352} small>模式の記号だけを表示する。実秘密を生成・保存・送信しない。</Text></>:null}
 {stage===4&&<AuthorityThree columns={[["接続先ごとの鍵","狭いscopeを発行","共通全権を避ける"],["実行側で管理","refresh・","rotation","tokenをloop外へ"],["実環境のID","短寿命へ交換","失効も設計する"]]}/>}
 {stage===5&&<AuthorityPair left={['MCP宛てtoken','受け手がaudienceを検証','resourceとscopeを限定','上流へそのまま渡さない']} right={['上流APIへの接続','契約に沿った別の資格情報','必要なscopeで接続する','混乱した代理人を避ける']} id={id} phase={phase} arrow={false}/>}
 <Text y={412} small>失効で過去の外部作用は取り消せない。鍵はmodelに見せない。</Text>
 </>}</AuthorityCanvas>} controls={({stage,ready})=>stage===1?<Select label="失効で不足する制御" value={missing} onChange={setMissing} ready={ready}><option value="token">token失効が不足</option><option value="credentials">資格情報の無効化が不足</option><option value="tools">toolの停止が不足</option><option value="none">三制御を照合</option></Select>:stage===2||stage===3?<Select label="資格情報を渡す模式経路" value={route} onChange={setRoute} ready={ready}><option value="prompt">promptへ鍵を入れる</option><option value="runtime">実行時にvaultから注入</option><option value="egress">送信時に記号を差し替え</option></Select>:null}>{children}</AuthorityFigure>
}
export function IdentityStandardsConnection({children}){
 const id=useId(),[kind,setKind]=useState('draft'),[connection,setConnection]=useState('openai'),states={rfc:['確定した土台','RFC 8693','subject / actorの標準語彙','専用Agent標準とは別'],draft:['動いている提案','WG採択・個人draft','採択とRFC成立を区分','原文の観測時点へ戻る'],product:['製品の提供区分','各社のGA・Preview等','機能・accountの対象を照合','全機能の適合は保証しない']},routes={openai:['Connectors API','tokenをauthorizationへ','登録とuser認可はアプリ側','画面の接続設定とは別'],google:['Googleの新旧API','Auth managerとAgent ID','legacy connector','からの移行','対象環境と手順を検証'],okta:['Okta Previewの設定','Managed connection','廃止告知','Resource Serverへ再設定','upcomingを','確定停止日にしない']}
 return <AuthorityFigure diagram="identity-standards-connection" title="標準の土台・動く仕様・製品と設定移行の確認先" scene={({phase})=><AuthorityCanvas diagram="identity-standards-connection" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['確定した土台と、専用Agent提案を分ける','WG採択と、RFCの成立を混同しない','MCPの版付き仕様と、認可の契約を読む','設計の形と、製品の提供区分を分ける','APIの接続契約を、アプリ側で実装・検証する','旧新のAPI・設定を、対象環境で移す'][stage]}</Text>
 {stage<2||stage===3?<><Tokens labels={['RFCの土台','draft','製品の提供']} selected={[['rfc','draft','product'].indexOf(kind)]} y={86}/><AuthorityPair left={states[kind]} right={['原文の時点を保持','仕様・製品ごとの出典日','新しい版・GAは別に確認','図は採用判断を行わない']} id={id} phase={phase} y={180} arrow={false}/></>:null}
 {stage===2&&<AuthorityThree columns={[["版付きの仕様","2026-07-28の観測","次の版は別に照合"],["受け手と宛先","resource・","audience","発行者とscope"],["上流への接続","tokenを転送しない","認可契約を分ける"]]}/>}
 {stage===4||stage===5?<AuthorityPair left={routes[connection]} right={['対象環境で確認','scope・refresh・再同意','保管とログのmasking','名称だけを置き換えない']} id={id} phase={phase} arrow={false}/>:null}
 <Text y={412} small>原文の確認日・TODOを保つ。現アカウント・提供状態は検証しない。</Text>
 </>}</AuthorityCanvas>} controls={({stage,ready})=>stage<2||stage===3?<Select label="標準と提供状態の区分" value={kind} onChange={setKind} ready={ready}>{Object.entries(states).map(([v,a])=><option key={v} value={v}>{a[0]}</option>)}</Select>:stage===4||stage===5?<Select label="接続と設定移行の確認先" value={connection} onChange={setConnection} ready={ready}>{Object.entries(routes).map(([v,a])=><option key={v} value={v}>{a[0]}</option>)}</Select>:null}>{children}</AuthorityFigure>
}
