'use client'
import {useId,useState} from 'react'
import {QualityCanvas,QualityFigure,QualityPair,QualityThree,Text,Box,Select,Tokens} from './quality-trace-primitives'
import {japaneseCheckRoute,japaneseJudgeAcceptance} from '../../lib/quality-trace-model.mjs'
const axes={honorific:['敬語・待遇表現','相手・行為者・場面の条件','尊敬語と謙譲語の使い分け','不適切な二重敬語と慣用の例外'],style:['文体一貫性','敬体と常体の揺れ','引用・見出しを範囲から除く','用途の規定と用法の誤りを区分'],notation:['表記ゆれ・全半角','指定用語と記号の統一','サーバ／サーバーなどの混在','機械定義できる範囲を明示'],names:['固有名詞・読み','人名・地名・製品名','表記と読みの正しさ','誤変換を含む評価ケース'],natural:['不自然な直訳調','場面に合う自然な表現','受動態などを一律禁止せず','意味と文脈から判断する']}
const exceptions={habit:['慣習として定着した例','お伺いする','全二重敬語を不正解にしない','LLM採点基準は自社で設計'],quote:['文体判定の適用範囲','引用を除く本文は敬体','引用中の常体を本文と区分','引用と見出しの例外を定める'],context:['用法と用途の規定','相手・行為者に合う敬語','指定表記と適用範囲を明示','単純な全件不正解にしない']}
export function JapaneseAxesExceptions({children}){
 const id=useId(),[axis,setAxis]=useState('honorific'),[exception,setException]=useState('habit')
 return <QualityFigure diagram="japanese-axes-exceptions" title="日本語の品質軸と、条件の範囲・例外" scene={({phase})=><QualityCanvas diagram="japanese-axes-exceptions" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['日本語の産出品質を、意味の正確さに加えて測る','意味だけでは見えない、五つの品質軸を読む','例外を含めて、適用する条件を書く','実際の日本語タスクで、崩れやすい入力を集める','自社用途の期待値を、条件と範囲で定める'][stage]}</Text>
  {stage===0?<QualityPair id={id} phase={phase} arrow={false} left={['本記事の対象','日本語として適切か','敬語・文体・表記など','実タスクの産出品質']} right={['分担する領域','翻訳の原文忠実さ','属性・グループの公平','judgeの共通設計']}/>:stage===1?<><Tokens labels={['敬語','文体','表記','固有名詞','直訳調']} selected={[Object.keys(axes).indexOf(axis)]} y={87}/><Box x={64} y={184} width={512} height={193} title={axes[axis][0]} lines={axes[axis].slice(1)} tone="violet" data-japanese-quality-axis={axis}/></>:stage===2?<Box x={64} y={101} width={512} height={219} title={exceptions[exception][0]} lines={exceptions[exception].slice(1)} tone="teal" data-japanese-exception={exception} data-japanese-graded="false"/>:stage===3?<QualityThree columns={[['実際の入力','日本語の応対ログ','実タスクの条件','機械翻訳だけにせず'],['崩れやすい入力','敬語が要る場面','長文・文体の揺れ','多い固有名詞'],['条件の期待値','引用を除く敬体','相手に合う敬語','指定表記と例外']]}/>:<QualityPair id={id} phase={phase} left={['明示する評価条件','適用範囲と例外','用途の規定を明示','人手ラベルの判断へ']} right={['自社用途の評価設計','指針は用法の根拠','LLM採点基準は別','条件と文脈を検証']}/>}
 </>}</QualityCanvas>} controls={({stage,ready})=>stage===1?<Select label="日本語で確認する品質軸" value={axis} onChange={setAxis} ready={ready}>{Object.entries(axes).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===2?<Select label="日本語条件で保持する例外" value={exception} onChange={setException} ready={ready}>{Object.entries(exceptions).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:null}>{children}</QualityFigure>
}
export function JapaneseJudgeDivision({children}){
 const id=useId(),[missing,setMissing]=useState('human'),[kind,setKind]=useState('notation'),[scope,setScope]=useState('both')
 const judge=japaneseJudgeAcceptance({humanJapanese:missing!=='human',wrongAcceptedChecked:missing!=='wrong',rightRejectedChecked:missing!=='right',blindspotsChecked:missing!=='blindspots'}),route=japaneseCheckRoute({kind,scopeDefined:scope!=='scope',exceptionsDefined:scope!=='exceptions'})
 return <QualityFigure diagram="japanese-judge-division" title="日本語judgeの検証と、コード・人手の分担" scene={({phase})=><QualityCanvas diagram="japanese-judge-division" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['生成の順位と、採点できる能力を分ける','日本語の人手ラベルで、採点の誤りを点検する','機械定義できる範囲は、コードで測る','条件ごとに、コードと判断の分担を切り替える','公開ベンチから、自社の日本語評価へ戻す'][stage]}</Text>
  {stage===0?<QualityPair id={id} phase={phase} arrow={false} left={['採点能力の根拠にせず','生成能力の順位','被評価より大きいモデル','同系の癖を自然と誤認']} right={['実際に検証する','敬語・文体・表記の採点','日本語の人手ラベル','誤って通す／落とす']}/>:stage===1?<Box x={64} y={101} width={512} height={219} title={judge.reviewCandidate?'検証済み採用を検討する候補':'人手と誤りの点検へ戻す'} lines={['日本語の人手ラベルとの照合','誤答を通す・適切な表現を落とす','別系統でも共有の盲点を点検','図は実モデルを採点しない']} tone={judge.reviewCandidate?'teal':'amber'} data-japanese-judge-candidate={String(judge.reviewCandidate)} data-japanese-grading-guaranteed="false" data-japanese-model-executed="false"/>:stage===2||stage===3?<>
   <QualityPair id={id} phase={phase} left={['測る対象と範囲',kind==='notation'?'指定用語・全半角':kind==='style'?'文体の曖昧な候補':'敬語・文脈の自然さ',scope==='scope'?'適用範囲が未定義':'適用範囲を定める',scope==='exceptions'?'例外が未定義':'例外と誤検知を点検']} right={[route.route==='code'?'機械条件のコード検査':'人・検証済みjudgeへ',route.route==='code'?'範囲が定義できる表記':'文脈を含む判断を残す','全条件合格≠自然さ','図は実採点しない']}/>
   <g data-japanese-check-route={route.route} data-japanese-naturalness-guaranteed="false" data-japanese-graded="false"/>
  </>:<QualityPair id={id} phase={phase} left={['公開ベンチのスコア','当たりを付ける','入力と採点基準を読む','最新はTODOで確認']} right={['自前の日本語セット','自社の実タスクで測る','公開の分布と区分','検証したjudgeを使う']}/>}
 </>}</QualityCanvas>} controls={({stage,ready})=>stage===1?<Select label="日本語judgeの不足する検証" value={missing} onChange={setMissing} ready={ready}><option value="human">日本語の人手ラベル</option><option value="wrong">誤答を通す条件</option><option value="right">適切な表現を落とす条件</option><option value="blindspots">共有する盲点</option><option value="none">必要条件を照合</option></Select>:stage===2||stage===3?<><Select label="日本語の採点対象" value={kind} onChange={setKind} ready={ready}><option value="notation">指定表記・全半角</option><option value="style">文体の曖昧な候補</option><option value="context">敬語・文脈の自然さ</option></Select><Select label="日本語チェックの定義状態" value={scope} onChange={setScope} ready={ready}><option value="both">範囲・例外を定義</option><option value="scope">適用範囲が未定義</option><option value="exceptions">例外が未定義</option></Select></>:null}>{children}</QualityFigure>
}
