'use client'
import {useId,useState} from 'react'
import {BudgetCanvas,BudgetFigure,BudgetPair,BudgetThree,Text,Box,Wire,Select} from './service-budgets-primitives'
import {toyLatency,latencyAdoption} from '../../lib/service-budgets-model.mjs'
const modes={llm:{ttft:4,output:12,perToken:1,toolA:2,toolB:3,overhead:1},tool:{ttft:2,output:4,perToken:1,toolA:16,toolB:3,overhead:1},short:{ttft:2,output:4,perToken:1,toolA:2,toolB:3,overhead:1}}
export function LatencyBreakdownTools({children}){
 const id=useId(),[mode,setMode]=useState('llm'),[parallel,setParallel]=useState('serial'),[dependent,setDependent]=useState('independent'),result=toyLatency({...modes[mode],independent:dependent==='independent',parallel:parallel==='parallel'}),tools=toyLatency({ttft:0,output:0,perToken:0,toolA:3,toolB:5,overhead:0,independent:dependent==='independent',parallel:parallel==='parallel'})
 return <BudgetFigure diagram="latency-breakdown-tools" title="応答時間の内訳と、toolの依存関係" scene={({phase})=><BudgetCanvas diagram="latency-breakdown-tools" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['完了までの時間を、三つの項へ分解する','一回のLLM時間を、待機と生成へ分ける','遅いタスクの内訳から、支配する項を読む','独立するtoolだけを、並列に置ける','固定の手順を、毎回の推論から切り出す'][stage]}</Text>
  {stage===0||stage===2?<>
   <Text y={88}>{`模式時間: 合計${result.total}単位（実測ではない）`}</Text>
   {[['LLM',result.llm,'sb-bar-teal'],['tool',result.tools,'sb-bar-amber'],['overhead',result.overhead,'sb-bar-teal']].map(([label,value,tone],i)=><g key={label}><Text x={54} y={142+i*80} anchor="start" small>{`${label}: ${value}`}</Text><rect x={180} y={124+i*80} width={value*18} height={32} rx={6} className={tone}/></g>)}
   <Text y={397} small>streamingの体感改善と、実際の完了時間を区分する。</Text><g data-latency-llm={result.llm} data-latency-tools={result.tools} data-latency-total={result.total} data-latency-measured="false"/>
  </>:stage===1?<BudgetPair id={id} phase={phase} arrow={false} left={['最初までの待機','TTFT: 入力処理＋最初','プロンプトと構成の条件','実際の待機を測る']} right={['その後の生成','出力長 × 生成時間','近似の項と実測を区分','品質・再試行も残す']}/>:stage===3?<>
   <Box x={35} y={95} width={250} height={92} title="tool A: 模式3" lines={['必要な結果を返す']} tone="violet"/><Box x={355} y={result.parallelUsed?95:231} width={250} height={92} title="tool B: 模式5" lines={[dependent==='independent'?'Aの結果は不要':'Aの結果が必要']} tone="teal"/>
   {!result.parallelUsed&&<Wire id={id} d="M285 141H317V277H355" active phase={phase}/>}
   <Text y={372}>{`模式tool時間: ${tools.tools}単位。実行はしない。`}</Text><g data-latency-parallel-used={String(tools.parallelUsed)} data-latency-tool-pair-time={tools.tools} data-latency-tools-executed="false"/>
  </>:<BudgetPair id={id} phase={phase} arrow={false} left={['固定の手順','手順が実質同じ','Workflowへ切り出す','推論の往復を減らす']} right={['必要な判断','入力で経路が変わる','Agentに判断を残す','品質・費用・時間を評価']}/>}
 </>}</BudgetCanvas>} controls={({stage,ready})=>stage===0||stage===2?<Select label="内訳を読む模式時間の構成" value={mode} onChange={setMode} ready={ready}><option value="llm">LLMの項が大きい</option><option value="tool">tool Aの項が大きい</option><option value="short">短い出力の模式構成</option></Select>:stage===3?<><Select label="模式tool間の依存関係" value={dependent} onChange={setDependent} ready={ready}><option value="independent">BはAの結果を使わない</option><option value="dependent">BはAの結果を使う</option></Select><Select label="模式toolの実行配置" value={parallel} onChange={setParallel} ready={ready}><option value="parallel">並列を要求</option><option value="serial">直列に配置</option></Select></>:null}>{children}</BudgetFigure>
}
export function LatencyLeversPriorities({children}){
 const id=useId(),[missing,setMissing]=useState('quality'),[sync,setSync]=useState('job'),result=latencyAdoption({qualityChecked:missing!=='quality',costChecked:missing!=='cost',latencyChecked:missing!=='latency',priorityDefined:missing!=='priority'})
 return <BudgetFigure diagram="latency-levers-priorities" title="四つの時間レバーと、同期で待つ要件" scene={({phase})=><BudgetCanvas diagram="latency-levers-priorities" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['中間の出力を、品質とセットで短くする','入力再処理と、単純部品のモデルを見直す','tool側の時間と、待機の上限を設計する','品質・費用・時間の優先順位を明示する','同期で完了を待つ必要があるかを確認する'][stage]}</Text>
  {stage===0?<BudgetPair id={id} phase={phase} left={['中間出力の長さ','構造化・短い形式','判断理由を短くする','生成の項を減らす']} right={['品質とセットで調整','推論の記述が必要か','元タスクで評価する','短さだけで採用せず']}/>:stage===1?<BudgetThree columns={[['cache','入力の再処理','prefixとモデル条件','実TTFTを測る'],['部品のモデル','分類・抽出と経路','高速な候補を評価','品質と再試行'],['総費用と品質','安さだけで選ばず','成功タスクで比較','実測から採用判断']]}/>:stage===2?<BudgetPair id={id} phase={phase} arrow={false} left={['tool側の最適化','遅い社内・外部API','重いqueryを改善','実時間の支配項を測る']} right={['全toolにtimeout','待機の上限を設ける','失敗と復旧経路を設計','既作用の取消とは別']}/>:stage===3?<Box x={64} y={102} width={512} height={219} title={result.reviewCandidate?'実測から採用を検討する候補':'不足する評価と優先順位へ戻す'} lines={['品質・費用・実時間を測る','タスクの優先順位を明示','全軸を無条件に最優先へしない','図は実改善・配信を行わない']} tone={result.reviewCandidate?'teal':'amber'} data-latency-review-candidate={String(result.reviewCandidate)} data-latency-deployed="false" data-latency-improvement-guaranteed="false"/>:<BudgetPair id={id} phase={phase} arrow={false} left={[sync==='job'?'急がないタスク':'同期で完了が必要','妥当な時間内の完了',sync==='job'?'ジョブとして受け付ける':'同期SLOを実測する','優先する要件を明示']} right={[sync==='job'?'非同期と完了通知へ':'支配項の最適化へ',sync==='job'?'受付と完了を区分':'品質・費用を併せて読む','図は実通知を送らない','即時完了の保証にせず']}/>}
 </>}</BudgetCanvas>} controls={({stage,ready})=>stage===3?<Select label="時間最適化で不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="quality">品質の評価</option><option value="cost">総費用の評価</option><option value="latency">実レイテンシの評価</option><option value="priority">タスクの優先順位</option><option value="none">必要条件を照合</option></Select>:stage===4?<Select label="完了を待つ必要のある模式要件" value={sync} onChange={setSync} ready={ready}><option value="job">妥当な時間内に通知が来ればよい</option><option value="sync">同期で完了を待つ必要がある</option></Select>:null}>{children}</BudgetFigure>
}
