'use client'
import {useId,useState} from 'react'
import {SecurityFigure,SecurityCanvas,SecurityPair,SecurityThree,Text,Box,Wire,Select,Tokens} from './security-boundaries-primitives'
import {scopedToolReview,approvalPlacement,sandboxReview,mcpReview,taskToolSet} from '../../lib/security-boundaries-model.mjs'
export function PermissionGatesScope({children}){
 const id=useId(),[missing,setMissing]=useState('tenant'),[risk,setRisk]=useState('external'),scope=scopedToolReview({callerAllowed:missing!=='caller',tenantMatched:missing!=='tenant',resourceAllowed:missing!=='resource',operationAllowed:missing!=='operation'}),approval=approvalPlacement({irreversible:risk==='irreversible',largeImpact:risk==='large',untrustedRecent:risk==='external'})
 return <SecurityFigure diagram="permission-gates-scope" title="本人・対象・操作の権限と、実行前の承認ゲート" scene={({phase})=><SecurityCanvas diagram="permission-gates-scope" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['渡した能力が、誤りや悪用で起こせる被害を決める','四原則を、toolとbackendの設計へ結ぶ','本人・tenant・resource・操作をすべて照合する','可逆性と総影響の二軸で、ゲートを配置する','未信頼の内容に触れた後は、危険操作を点検する','具体的な影響を示して、形だけの承認を避ける'][stage]}</Text>
 {stage===0&&<SecurityPair left={['広いservice account','全てのread・writeが可能','modelへ限定と伝えるだけ','誤りで全権を代理し得る']} right={['最小限の実行権限','必要な対象と操作だけ','本人の許可と範囲を照合','modelの誤りでも昇格しない']} id={id} phase={phase} arrow={false}/>}
 {stage===1&&<>{[['toolを最小化','必要な能力だけ'],['read/writeを分離','読取taskへwriteなし'],['利用者の権限','全権で代理しない'],['tenant・resource','backendでscope制限']].map((a,i)=><Box key={a[0]} x={45+(i%2)*285} y={85+Math.floor(i/2)*140} width={265} height={115} title={a[0]} lines={[a[1]]}/>)}<Text y={378} small>自然言語のお願いと、実行側の認可は別の制約。</Text></>}
 {stage===2&&<><Tokens labels={['本人','tenant','resource','操作']} muted={missing==='none'?[]:[['caller','tenant','resource','operation'].indexOf(missing)]} selected={missing==='none'?[0,1,2,3]:[]} y={86}/><SecurityPair left={['代理の範囲を照合','本人に許可があるか','同じtenantの対象か','この操作が許されるか']} right={[scope.reviewCandidate?'認可設計の検討候補':'不足条件の照合へ戻る','toolとbackendで強制','図は実認証を試さない','図は実操作を実行しない']} id={id} phase={phase} y={180}/></>}
 {stage===3||stage===4?<><Tokens labels={['可逆性','件数・金額','外部への影響']} selected={[risk==='irreversible'?0:risk==='large'?1:risk==='external'?2:0]} y={86}/><SecurityPair left={['操作と入力の状況',risk==='irreversible'?'取り消せない作用':risk==='large'?'総件数・金額が大きい':risk==='external'?'未信頼内容に触れた直後':'限定した可逆・小さい作用','対象と送り先を具体化','分割後も総影響を確認']} right={[approval.needsReview?'実行前の確認へ戻す':'限定した境界を確認','承認者と作者を分ける','承認は対象と影響を確認','図は承認を取得しない']} id={id} phase={phase} y={180}/></>:null}
 {stage===5&&<SecurityPair left={['形だけの全操作承認','回数だけが増える','慣れで影響を見落とす','検知合格を承認にしない']} right={['危険操作の具体的な確認','対象・件数・金額・宛先','強制制約と復旧も設計','入力の作者を承認者にしない']} id={id} phase={phase} arrow={false}/>}
 <Text y={412} small>図は承認や権限を付与しない。実認証・policyを別に検証する。</Text>
 </>}</SecurityCanvas>} controls={({stage,ready})=>stage===2?<Select label="認可で不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="caller">本人の許可が不足</option><option value="tenant">tenantの照合が不足</option><option value="resource">resourceの範囲が不足</option><option value="operation">操作の許可が不足</option><option value="none">四条件を照合</option></Select>:stage===3||stage===4?<Select label="承認を配置する状況" value={risk} onChange={setRisk} ready={ready}><option value="irreversible">取り消せない操作</option><option value="large">件数・金額・総影響が大きい</option><option value="external">未信頼内容に触れた直後</option><option value="small">限定した可逆・小さい操作</option></Select>:null}>{children}</SecurityFigure>
}
export function PermissionSandboxMcp({children}){
 const id=useId(),[missing,setMissing]=useState('egress'),[mcpMissing,setMcpMissing]=useState('version'),[task,setTask]=useState('read'),sandbox=sandboxReview({isolatedEnvironment:missing!=='environment',restrictedEgress:missing!=='egress',boundedResources:missing!=='resources',dedicatedAccount:missing!=='account'}),mcp=mcpReview({sourceChecked:mcpMissing!=='source',versionPinned:mcpMissing!=='version',toolsAllowed:mcpMissing!=='tools',tokenScoped:mcpMissing!=='token'}),tools=taskToolSet(task)
 return <SecurityFigure diagram="permission-sandbox-mcp" title="隔離する四つの制約と、MCP・状況別toolの範囲" scene={({phase})=><SecurityCanvas diagram="permission-sandbox-mcp" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['production・開発者と、実行環境を分ける','四制約を別々に照合し、名前だけで保証しない','実ユーザーのbrowser・credentialを持ち込まない','MCP serverの出所・固定版・更新差分を照合する','許可toolとtokenを絞っても、結果の内容は未信頼','taskの変更や異常で、渡すtoolを縮める'][stage]}</Text>
 {stage===0&&<><rect x={55} y={85} width={340} height={252} rx={14} fill="#112638" stroke="#65dbc8" strokeDasharray="6 6"/><Text x={225} y={123}>隔離した実行環境</Text><Box x={95} y={165} width={260} height={132} title="コード・画面操作" lines={['一時環境・専用account','通信先・資源の上限']}/><Box x={450} y={165} width={155} height={132} title="元の環境" lines={['production','開発者の秘密']} tone="amber"/><Text y={378} small>隔離の機構と実設定を検証する。container名は保証ではない。</Text></>}
 {stage===1&&<><Tokens labels={['環境','通信','資源','専用account']} muted={missing==='none'?[]:[['environment','egress','resources','account'].indexOf(missing)]} selected={missing==='none'?[0,1,2,3]:[]} y={86}/><SecurityPair left={['四つの制約','filesystemと本番を分離','egressの許可先を限定','CPU・memory・時間・disk']} right={[sandbox.reviewCandidate?'実隔離を検証する候補':'不足する制約へ戻る','専用accountと権限','実環境の逃げ道も点検','図は隔離を実検証しない']} id={id} phase={phase} y={180}/></>}
 {stage===2&&<SecurityPair left={['専用のbrowser','一時profileで画面を操作','限定した資格情報','productionとは分離']} right={['持ち込まないもの','実利用者のログイン','開発者の秘密や全権','認証と通信の逃げ道']} id={id} phase={phase} arrow={false}/>}
 {stage===3||stage===4?<><Tokens labels={['出所','固定版','tool','token']} selected={mcpMissing==='none'?[0,1,2,3]:[]} muted={mcpMissing==='none'?[]:[['source','version','tools','token'].indexOf(mcpMissing)]} y={86}/><SecurityPair left={['接続前の四条件','出所と版を確認する','更新差分・追加toolを点検','許可toolとtoken範囲']} right={[mcp.reviewCandidate?'接続設計の検討候補':'不足する条件へ戻る','返った内容は未信頼入力','危険操作の承認は別','図はserverへ接続しない']} id={id} phase={phase} y={180}/></>:null}
 {stage===5&&<><Tokens labels={['読取task','限定write','異常時']} selected={[['read','write','incident'].indexOf(task)]} y={86}/><SecurityPair left={['taskに渡すtool',tools.tools.length?tools.tools.join(' / '):'toolを停止する',task==='read'?'write toolは渡さない':'強い承認ゲートへ戻す','backendでもscope制限']} right={['状況で権限を縮める','利用者の目的を確認','異常時は停止・承認必須','依頼だけに頼らない']} id={id} phase={phase} y={180} arrow={false}/></>}
 <Text y={412} small>結果の内容は認証と別。図は接続・隔離・権限付与を実行しない。</Text>
 </>}</SecurityCanvas>} controls={({stage,ready})=>stage===1?<Select label="隔離で不足する制約" value={missing} onChange={setMissing} ready={ready}><option value="environment">環境の隔離が不足</option><option value="egress">通信先の制限が不足</option><option value="resources">資源の上限が不足</option><option value="account">専用accountが不足</option><option value="none">四制約を照合</option></Select>:stage===3||stage===4?<Select label="MCPで不足する条件" value={mcpMissing} onChange={setMcpMissing} ready={ready}><option value="source">出所が未確認</option><option value="version">版が未固定</option><option value="tools">tool許可が未確認</option><option value="token">token範囲が未確認</option><option value="none">四条件を照合</option></Select>:stage===5?<Select label="権限を渡すtaskの状況" value={task} onChange={setTask} ready={ready}><option value="read">読取task</option><option value="write">範囲を限定したwrite</option><option value="incident">異常時に停止</option></Select>:null}>{children}</SecurityFigure>
}
