'use client'
import {useId,useState} from 'react'
import {TrustFigure,TrustCanvas,TrustPair,TrustThree,Text,Box,Wire,Select,Tokens} from './trust-privacy-primitives'
import {petCandidate,privacyUnit,dpIllustration,sequentialBudget,federatedLayers,privacyBasics} from '../../lib/trust-privacy-model.mjs'
const techniques=[['検出・mask','PIIを隠す・置き換える'],['仮名化・匿名化','加工と再識別の限界'],['差分プライバシー','公開確率の差を制限'],['連合学習','生dataを各所に置く'],['秘密計算・TEE','暗号・隔離して処理']]
export function PrivacyLayersFit({children}){
 const id=useId(),[mode,setMode]=useState('aggregation'),layers=federatedLayers(mode)
 return <TrustFigure diagram="privacy-layers-fit" title="五つの技術を、守る対象と処理の段階で選ぶ" scene={({phase})=><TrustCanvas diagram="privacy-layers-fit" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['最小化と統制、残る公開と共有の経路を分ける','五層は適用を考える分類で、強さの順位ではない','名前を消しても、文脈や別dataから再識別し得る','集計・学習・推論で、保護する対象が異なる','生data・更新情報・完成modelを、別の経路として読む','集約と公開modelの保護を、脅威に合わせて組み合わせる'][stage]}</Text>
 {stage===0&&<TrustPair left={['基本の設計','不要dataを減らす','誰が見られるかを絞る','maskの漏れを評価']} right={['残る公開・共有','集計結果からの推論','学習更新と完成model','場面に合う追加保護']} id={id} phase={phase}/>}
 {stage===1&&<>{techniques.map((r,i)=><g key={r[0]}><rect x={40} y={78+i*58} width={560} height={48} rx={6} fill="#142b39" stroke="#526b7c"/><Text x={163} y={110+i*58} small>{r[0]}</Text><Text x={443} y={110+i*58} small>{r[1]}</Text></g>)}</>}
 {stage===2&&<><TrustPair left={['加工したdata','名前を隠す・置き換える','検出漏れが残り得る','文脈にも個人の手がかり']} right={['別dataとの突合せ','仮名化も再識別し得る','アクセス統制を併用','対象と用途で評価']} id={id} phase={phase}/><Text y={345}>匿名化の名称だけで、安全や再識別不能にしない</Text></>}
 {stage===3&&<TrustThree columns={[["公開する集計","単位とDPの予算","有用性を評価"],["学習の更新","共有先と集約方式","完成modelも点検"],["推論・処理","暗号方式／TEE","信頼と費用を比較"]]}/>}
 {stage===4||stage===5?<><Box x={34} y={88} width={176} height={123} title="各所の生data" lines={['中央へ集めない','手元で学習']} tone="purple"/><Box x={244} y={88} width={152} height={123} title="更新情報" lines={[layers.aggregationCandidate?'集約の保護候補':'共有時の漏えい','誰へ送るか']}/><Box x={430} y={88} width={176} height={123} title="完成model" lines={[layers.outputPrivacyCandidate?'出力保護のDP候補':'公開後の推論経路','利用者も脅威に含む']} tone="amber"/><Wire id={id} d="M210 149H242" active phase={phase}/><Wire id={id} d="M396 149H428" active phase={phase}/><TrustPair left={['集約時の保護','更新情報を秘匿する','生dataを送らない構成','出力保護は別に確認']} right={['公開後の保護','完成modelからの推論','誰から何を守るか','名称だけで保証にしない']} id={id} phase={phase} y={259} height={128} arrow={false}/></>:null}
 <Text y={412} small>集約の秘匿だけで、完成modelからの推論も防げるとは扱わない。</Text>
 </>}</TrustCanvas>} controls={({stage,ready})=>stage===4||stage===5?<Select label="連合学習で検討する追加保護" value={mode} onChange={setMode} ready={ready}><option value="none">追加保護をまだ検討しない</option><option value="aggregation">集約時の保護を検討</option><option value="dp">公開modelのDPを検討</option><option value="both">両方を検討</option></Select>:null}>{children}</TrustFigure>
}
export function PrivacyUnitBudget({children}){
 const id=useId(),[unit,setUnit]=useState('row'),[epsilon,setEpsilon]=useState('0.1'),[delta,setDelta]=useState('0'),[count,setCount]=useState('10'),scope=privacyUnit(unit),formula=dpIllustration(Number(epsilon),Number(delta)),budget=sequentialBudget(Number(count))
 return <TrustFigure diagram="privacy-unit-budget" title="保護単位・εとδ・累積公開を、同じ仕様で読む" scene={({phase})=><TrustCanvas diagram="privacy-unit-budget" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['何を隣接とするか、各公開の条件と合計を仕様にする','一行の違いと、一人の全記録の違いを分ける','右辺はexp(ε)による乗法とδによる加法','小さいparameterの制約と、結果の有用性を併せて評価','同じ対象の公開を増やすと、単純合成の上限も増える','DPの範囲と、集約時・公開後の保護を分ける'][stage]}</Text>
 {stage===0&&<>{techniques.map((r,i)=><g key={r[0]}><rect x={40} y={78+i*58} width={560} height={48} rx={6} fill="#142b39" stroke="#526b7c"/><Text x={163} y={110+i*58} small>{r[0]}</Text><Text x={443} y={110+i*58} small>{r[1]}</Text></g>)}</>}
 {stage===1&&<><Tokens labels={['一行','一event','一人の全記録']} selected={[['row','event','person'].indexOf(unit)]} y={88}/><TrustPair left={['隣接dataの違い',unit==='row'?'一行だけを変える':unit==='event'?'一eventだけを変える':'一人の全記録を変える','同じ定義で保証を読む','単位を明示する']} right={[scope.protectsAllPersonRecords?'一人の記録の単位':'一人全体への転用は不可','全属性の推論禁止ではない','個人の影響ゼロではない','実機構の保証は別に検証']} id={id} phase={phase} y={203} height={171}/></>}
 {stage===2||stage===3?<><Text y={97}>P[M(D) ∈ S] ≤ exp(ε) × P[M(D′) ∈ S] + δ</Text><Text y={145} small>同じ出力事象 S と、保護単位が同じ隣接dataを比較する。</Text><Box x={38} y={186} width={264} height={127} title={`exp(ε) = ${formula.factor.toFixed(3)}`} lines={['模式の参照確率: 0.100',`乗法の寄与: ${(formula.factor*0.1).toFixed(3)}`]} tone="purple"/><Box x={338} y={186} width={264} height={127} title={`右辺 = ${formula.rightBound.toFixed(3)}`} lines={[`加法の許容分 δ: ${Number(delta).toFixed(3)}`,'全事象のDP証明ではない']}/><Text y={359} small>固定の模式確率の右辺。ノイズの追加や一式だけで保証にしない。</Text></>:null}
 {stage===4&&<><Text y={87}>単純な逐次合成: 各公開の ε・δ の和を上限にする</Text><Text y={137} small>同じ対象へ、毎回 ε = 0.1、δ = 0.000001 の模式設定。</Text><rect x={48} y={182} width={544} height={38} rx={7} fill="#112638"/><rect x={48} y={182} width={544*budget.releases/20} height={38} rx={7} fill="#68ded0"/><TrustPair left={[`${budget.releases} 回の公開`,`累積 ε: ${budget.epsilon.toFixed(1)}`,`累積 δ: ${budget.delta.toFixed(6)}`]} right={['管理する上限','各回の成功だけで終えない','公開の全体を合成する','無制限の公開にしない']} id={id} phase={phase} y={255} height={131} arrow={false}/></>}
 {stage===5&&<TrustPair left={['保証の定義と範囲','単位・ε・δ・累積の予算','集団の傾向は残り得る','非保護の既存公開は消えない']} right={['別に残る保護段階','学習更新の共有と集約','完成modelからの推論','それぞれの脅威を照合']} id={id} phase={phase} arrow={false}/>}
 <Text y={412} small>模式の式と単純合成。実DP機構・実data・実損失は検証していない。</Text>
 </>}</TrustCanvas>} controls={({stage,ready})=>stage===1?<Select label="差分プライバシーの保護単位" value={unit} onChange={setUnit} ready={ready}><option value="row">一行</option><option value="event">一event</option><option value="person">一人の全記録</option></Select>:stage===2||stage===3?<><Select label="模式不等式のepsilon" value={epsilon} onChange={setEpsilon} ready={ready}>{['0','0.1','0.5','1'].map(v=><option key={v} value={v}>{v}</option>)}</Select><Select label="模式不等式のdelta" value={delta} onChange={setDelta} ready={ready}>{['0','0.001','0.01'].map(v=><option key={v} value={v}>{v}</option>)}</Select></>:stage===4?<Select label="同じ対象の模式公開回数" value={count} onChange={setCount} ready={ready}>{['0','1','5','10','20'].map(v=><option key={v} value={v}>{v}</option>)}</Select>:null}>{children}</TrustFigure>
}
const candidates={'differential-privacy':'差分プライバシー','federated-learning':'連合学習','cryptography-or-tee':'秘密計算・TEE'}
export function PrivacyBasicSelection({children}){
 const id=useId(),[scene,setScene]=useState('aggregation'),[missing,setMissing]=useState('none'),candidate=petCandidate(scene),basics=privacyBasics({minimized:missing!=='minimize',accessLimited:missing!=='access',maskEvaluated:missing!=='mask',residualRequirementChecked:missing!=='residual'})
 return <TrustFigure diagram="privacy-basic-selection" title="基本と残る要件から、場面に合うPETと負担を選ぶ" scene={({phase})=><TrustCanvas diagram="privacy-basic-selection" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['集計・学習・処理の場面から、守る経路を特定する','名称からでなく、保護対象と範囲で候補を選ぶ','最小化・統制・maskの評価と、残る要件を揃える','何を・誰から・なぜ守るか、基本と候補を照合する','有用性・性能・実装・運用の負担を測って判断する'][stage]}</Text>
 {stage===0||stage===1?<><TrustPair left={[scene==='aggregation'?'公開する集計':scene==='training'?'各所で学習する':'暗号・隔離して処理','守るdataと相手を定義','公開・更新・処理の範囲','既存公開や推論は別に確認']} right={[`${candidates[candidate.candidate]}の候補`,'名称だけで最適にしない','適用場面の制約を照合','自社の条件で実測する']} id={id} phase={phase}/><Text y={345}>技術の成熟度・費用・運用負担は、一様でない</Text></>:null}
 {stage===2&&<><Tokens labels={['最小化','アクセス統制','maskの評価','残る要件']} selected={[['minimize','access','mask','residual'].indexOf(missing)]} y={88}/><TrustPair left={['基本の設計','集めない・持たない','人と用途を限定','漏れと過剰maskを評価']} right={[basics.reviewCandidate?'追加保護を含め検討':'不足する基本と要件へ戻る','基本の省略はしない','公開保護は併せて設計可能','再識別の不在は保証しない']} id={id} phase={phase} y={203} height={171}/></>}
 {stage===3&&<><TrustThree columns={[["要件の特定","何を・誰から・","なぜ","機微度と主権"],["基本の照合","最小化・統制・","mask","残る経路を確認"],["場面の候補","集計・学習・処理","負担を測る"]]}/><Wire id={id} d="M208 180H230" active phase={phase}/><Wire id={id} d="M408 180H430" active phase={phase}/></>}
 {stage===4&&<TrustPair left={['保護と有用性','保証の範囲を仕様へ','結果の精度低下を評価','実dataで要件を照合']} right={['実務の負担','性能と費用を測る','実装と運用の負担','現実的な組合せを判断']} id={id} phase={phase} arrow={false}/>}
 <Text y={412} small>最適技術・規制適合・再識別不能は確定せず、自社要件・実測へ戻る。</Text>
 </>}</TrustCanvas>} controls={({stage,ready})=>stage===0||stage===1?<Select label="PETを選ぶ処理の場面" value={scene} onChange={setScene} ready={ready}><option value="aggregation">集計・分析</option><option value="training">学習</option><option value="processing">推論・処理</option></Select>:stage===2?<Select label="基本の設計で不足する条件" value={missing} onChange={setMissing} ready={ready}>{[['none','全条件を確認'],['minimize','最小化'],['access','アクセス統制'],['mask','maskの評価'],['residual','残る要件']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:null}>{children}</TrustFigure>
}
