'use client'
import {useId,useState} from 'react'
import {AdversityFigure,AdversityCanvas,AdversityPair,AdversityThree,Text,Box,Wire,Select,Tokens} from './security-adversity-primitives'
import {exerciseReview,actionEvidence,repairReview} from '../../lib/security-adversity-model.mjs'
const manual=[['直接','利用者入力'],['間接','Web・検索結果'],['権限','本人・scope'],['承認','省略・使い回し'],['漏えい','URL・送信先'],['連鎖','memory・Agent'],['誘導','業務と害の混在']]
export function RedExerciseDesign({children}){
 const id=useId(),[missing,setMissing]=useState('none'),[kind,setKind]=useState('0'),review=exerciseReview({scopeDefined:missing!=='scope',goalDefined:missing!=='goal',capabilityDefined:missing!=='capability',evidenceDefined:missing!=='evidence',isolatedEnvironment:missing!=='isolation'})
 return <AdversityFigure diagram="red-exercise-design" title="演習のscope・作用・証拠を先に定める" scene={({phase})=><AdversityCanvas diagram="red-exercise-design" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['脅威モデルの地図から、試験と修正の循環へ','文章・提案と、害のある外部作用を分ける','四つの設計と隔離環境を、試験前に揃える','七つの型を、sourceと境界ごとに掘り下げる','同じ境界の変形と回帰を、自動で反復する','手動の深さと、自動の広さを補い合う'][stage]}</Text>
 {stage===0&&<><AdversityThree columns={[["脅威モデル","資産と能力","境界の仮説"],["隔離した演習","同等の限定権限","作用の証拠"],["構造の修正","権限・承認","同じと派生"]]}/><Wire id={id} d="M208 182H230" active phase={phase}/><Wire id={id} d="M408 182H430" active phase={phase}/><Wire id={id} d="M520 269V330H120V271" active phase={phase}/><Text y={360} small>新しい経路を地図へ戻す。一度の演習で網羅しない。</Text></>}
 {stage===1&&<><Tokens labels={['出力','tool提案','実行','外部状態']} selected={[3]} y={89}/><AdversityPair left={['文章と提案','有害な文章を出す','危険なtoolを要求','要求だけでは実作用でない']} right={['実行と結果','操作ログを確かめる','状態・送信先を照合','作用に成功条件を置く']} id={id} phase={phase} y={199} height={171}/></>}
 {stage===2&&<><Tokens labels={['scope','goal','能力','証拠']} selected={[['scope','goal','capability','evidence'].indexOf(missing)]} y={80}/><AdversityPair left={['試験の契約','対象と許可を限定','攻撃者が使える能力','記録と成功条件を定義']} right={[review.reviewCandidate?'演習設計の検討候補':'不足条件へ戻る','隔離環境も必要','本番と似た限定権限','図は攻撃を実行しない']} id={id} phase={phase} y={185} height={177}/></>}
 {stage===3&&<>{manual.map((r,i)=><g key={r[0]}><rect x={38+(i%2)*290} y={74+Math.floor(i/2)*73} width={270} height={60} rx={6} fill="#142b39" stroke={Number(kind)===i?'#68ded0':'#526b7c'}/><Text x={173+(i%2)*290} y={98} small>{r[0]}</Text><Text x={173+(i%2)*290} y={123} small>{r[1]}</Text></g>)}</>}
 {stage===4&&<><AdversityThree columns={[["生成と変形","文字列・文脈","攻撃側LLM"],["試行と回帰","限定した環境","既知caseを保持"],["採点と証拠","judgeも検証","作用は状態へ"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Text y={344}>試行数は、網羅性や実安全率ではない</Text></>}
 {stage===5&&<AdversityPair left={['手動の深さ','新しい攻撃の発想','文脈と権限の盲点','細かな作用を調べる']} right={['自動の広さ','変形と反復・再現','既知caseを回帰へ','検証済judgeと状態の証拠']} id={id} phase={phase} arrow={false}/>}
 <Text y={412} small>payload・本番操作は実行しない。許可・scopeは実構成で確認する。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===2?<Select label="演習設計で不足する条件" value={missing} onChange={setMissing} ready={ready}>{[['none','全条件を確認'],['scope','scope'],['goal','goal'],['capability','能力'],['evidence','証拠'],['isolation','隔離環境']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:stage===3?<Select label="手動で掘り下げる型" value={kind} onChange={setKind} ready={ready}>{manual.map((r,i)=><option key={i} value={i}>{r[0]}</option>)}</Select>:null}>{children}</AdversityFigure>
}
export function RedResultsReturn({children}){
 const id=useId(),[evidence,setEvidence]=useState('effect'),[missing,setMissing]=useState('none'),result=actionEvidence({unsafeText:evidence==='text',toolRequested:['request','execution','effect'].includes(evidence),toolExecuted:['execution','effect'].includes(evidence),stateChanged:evidence==='effect',observationComplete:evidence!=='unknown'}),repair=repairReview({structuralControl:missing!=='structure',sameCasePassed:missing!=='same',variantsPassed:missing!=='variants',regressionAdded:missing!=='regression'})
 const findings={'unknown':'観測不足で未確定','external-effect-observed':'外部の作用を観測','execution-observed':'実行だけを観測','request-observed':'tool要求を観測','output-observed':'出力だけを観測','not-observed':'観測範囲で未発見'}
 return <AdversityFigure diagram="red-results-return" title="作用の証拠と構造修正を、次の地図へ戻す" scene={({phase})=><AdversityCanvas diagram="red-results-return" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['何を観測したかを、実行と外部状態まで分ける','影響と悪用のしやすさから、構造の穴を優先する','同じcase・派生・回帰を、修正した境界で試す','構成の変更で、攻撃面とscopeを見直す','既知回帰・外部の視点・開示窓口を継続する','新しい経路を、脅威モデルの地図へ戻す'][stage]}</Text>
 {stage===0&&<><Tokens labels={['出力','要求','実行','状態']} selected={[['text','request','execution','effect'].indexOf(evidence)]} y={89}/><AdversityPair left={['記録する証拠','出力だけで閉じない','tool引数と操作ログ','送信先と最終状態']} right={[findings[result.finding],'未観測は全安全でない','観測の範囲も明示','図は実作用を起こさない']} id={id} phase={phase} y={205} height={171}/></>}
 {stage===1&&<AdversityPair left={['影響を具体化','可逆性・機微度・件数','金額・公開・削除','悪用しやすい経路']} right={['構造を先に修正','権限と承認の穴','data・入力・送信の連結','promptの個別修正は補助']} id={id} phase={phase}/>}
 {stage===2&&<><Tokens labels={['構造','同じcase','派生','回帰']} selected={[['structure','same','variants','regression'].indexOf(missing)]} y={89}/><AdversityPair left={['境界の修正','文字列だけで止めない','同じと派生を再試験','回帰へ残す']} right={[repair.reviewCandidate?'修正受入の検討候補':'不足する再検証へ戻る','全脅威の安全ではない','実構成で作用を確認','図は受入を実行しない']} id={id} phase={phase} y={205} height={171}/></>}
 {stage===3&&<AdversityThree columns={[["構成の変更","tool・MCP","model・prompt"],["攻撃面を見直す","増えた能力","境界とdata"],["隔離で再演習","同じと派生","権限と証拠"]]}/>}
 {stage===4&&<AdversityThree columns={[["定期の回帰","既知caseを保持","構成変更も契機"],["外部の視点","重要度に応じる","対象と許可を限定"],["開示の窓口","発見を受ける","影響を評価"]]}/>}
 {stage===5&&<><AdversityThree columns={[["発見した経路","新しい入力source","権限と実作用"],["地図へ戻す","資産と境界を更新","scopeへ書き戻す"],["次の演習","条件と版を限定","作用と証拠を確認"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Wire id={id} d="M520 269V330H120V271" active phase={phase}/><Text y={363} small>完了した一回の演習から、次の変更と条件へ戻る。</Text></>}
 <Text y={412} small>正常な出力や一度の成功を、全経路の安全保証へ変換しない。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===0?<Select label="観測した証拠の範囲" value={evidence} onChange={setEvidence} ready={ready}>{[['text','出力'],['request','tool要求'],['execution','実行'],['effect','外部作用'],['unknown','観測不足']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:stage===2?<Select label="修正後に不足する条件" value={missing} onChange={setMissing} ready={ready}>{[['none','全条件を確認'],['structure','構造の修正'],['same','同じcase'],['variants','派生'],['regression','回帰']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:null}>{children}</AdversityFigure>
}
