'use client'
import {useId,useState} from 'react'
import {ReuseCanvas,ReuseFigure,ReusePair,ReuseThree,Text,Box,Wire,Select,Tokens} from './gateway-reuse-primitives'
import {responseCacheTarget,cacheReuse,cacheInvalidation} from '../../lib/gateway-reuse-model.mjs'
const levels={exact:['完全一致','入力文字列が同じ','権限・文脈・版は別条件','言い換えは拾わない'],normal:['正規化一致','確認した変換だけ','語順・否定を消さない','意味保存を検証する'],semantic:['意味的類似','近い質問を候補へ','類似と同一は違う','被害から基準を選ぶ']}
export function CacheLevelsSemanticRisk({children}){
 const id=useId(),[level,setLevel]=useState('semantic'),[example,setExample]=useState('direction'),[match,setMatch]=useState('near')
 return <ReuseFigure diagram="cache-levels-semantic-risk" title="入力処理と応答の再利用、三つの一致と誤ヒット" scene={({phase})=><ReuseCanvas diagram="cache-levels-semantic-risk" phase={phase} id={id}>{({stage})=><>
 <Text x={320} y={38} center>{['入力の処理結果と、最終応答そのものを分ける','キーの厳しさを、まず完全一致から読む','同じ単語でも語順や否定で意味が変わる','質問の候補から過去の最終応答へ進む','意味が近くても、答えが同じとは限らない','ヒット率だけでなく、誤答の被害と品質を見る'][stage]}</Text>
 {stage===0&&<ReusePair left={['入力側のcache','固定部分の処理を再利用','モデルは応答を生成','入力費用・初回時間']} right={['応答側のcache','過去の最終応答を返す','ヒット時はモデルを省く','検索の費用は残る']} id={id} phase={phase} arrow={false}/>}
 {stage===1&&<><Tokens labels={['完全','正規化','類似']} stage={Object.keys(levels).indexOf(level)} y={90}/><Box x={65} y={185} width={510} height={174} title={levels[level][0]} lines={levels[level].slice(1)} tone="teal"/></>}
 {stage===2&&<><ReusePair left={[example==='direction'?'A pays B':'解約できますか','支払う側や否定を保持','コードや名前も点検','表記変換は用途で確認']} right={[example==='direction'?'B pays A':'解約できませんか',example==='direction'?'支払う側が逆':'確認する内容が異なる','同じ単語だけで一致させない','意味を変える正規化は避ける']} id={id} phase={phase} arrow={false}/><Text x={320} y={348} center>無条件に語順・大小文字・空白を消さない</Text></>}
 {stage===3&&<><Tokens labels={['質問','埋込','候補','しきい値','応答']} stage={3} y={90}/><ReusePair left={['候補の質問','キャッシュ済みベクトル','近いものを選ぶ','RAGの文書検索とは別']} right={['再利用する応答','過去の最終応答','ヒットならモデルを省く','図は実検索しない']} id={id} phase={phase} y={184}/></>}
 {stage===4&&<ReusePair left={['東京の明日の天気','入力の地域と時点','質問同士は近くなり得る','類似候補だけでは足りない']} right={['大阪の明日の天気',match==='near'?'近くても答えが違う':'同じ答えの条件を検証','権限・文脈・鮮度を点検','実の品質判定は別']} id={id} phase={phase} arrow={false}/>}
 {stage===5&&<ReusePair left={['しきい値の緩和','候補ヒットを増やし得る','誤ヒットも点検','被害の大きさを読む']} right={['基準と対象を調整','誤ヒット率と品質','自分の分布で評価','実品質は図で測らない']} id={id} phase={phase}/>}
 <Text x={320} y={409} center small>類似は同一ではない。入力側のcacheを最終応答の再利用にしない。</Text>
 </>}</ReuseCanvas>} controls={({stage,ready})=>stage===1?<Select label="比較する一致の階層" value={level} onChange={setLevel} ready={ready}>{Object.entries(levels).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===2?<Select label="原文で区別する意味の差" value={example} onChange={setExample} ready={ready}><option value="direction">支払う側の語順</option><option value="negation">解約の肯定・否定</option></Select>:stage===4?<Select label="類似候補を読む条件" value={match} onChange={setMatch} ready={ready}><option value="near">候補が近いだけ</option><option value="check">答えの条件も検証する</option></Select>:null}>{children}</ReuseFigure>
}
export function CacheReuseInvalidation({children}){
 const id=useId(),[target,setTarget]=useState('freshness'),[missing,setMissing]=useState('tenant'),[event,setEvent]=useState('knowledge')
 const t=responseCacheTarget({deterministic:target!=='determinism',nonPersonalized:target!=='personal',freshnessIndependent:target!=='freshness'}),reuse=cacheReuse({matchCandidate:missing!=='match',sameTenant:missing!=='tenant',sameScope:missing!=='scope',sameContext:missing!=='context',versionsCurrent:missing!=='version',notExpired:missing!=='expiry',sharedTarget:missing!=='target'}),invalid=cacheInvalidation({knowledgeChanged:event==='knowledge',promptChanged:event==='prompt',modelChanged:event==='model',ttlExpired:event==='ttl'})
 return <ReuseFigure diagram="cache-reuse-invalidation" title="共有する応答の条件と、更新・期限・tenantの境界" scene={({phase})=><ReuseCanvas diagram="cache-reuse-invalidation" phase={phase} id={id}>{({stage})=><>
 <Text x={320} y={38} center>{['全応答を一律に共有対象へ載せない','決定性・非個人化・鮮度の三条件を揃える','更新のイベントとTTLを、別の無効化条件にする','近い質問でも、tenant・権限・文脈を混ぜない','ヒットと、誤ヒット・品質低下を並べる','費用・時間と品質から、基準と対象を直す'][stage]}</Text>
 {(stage===0||stage===1)&&<ReusePair left={['共有の対象条件','同じ入力に同じ答え','ユーザー固有でない','古くならない']} right={[t.reviewCandidate?'共有対象の検討候補':'共有対象から外す','在庫・残高は鮮度が要る','個人・権限の応答は別','図は実保存しない']} id={id} phase={phase}/>}
 {stage===2&&<><Tokens labels={['知識源','prompt','model','TTL']} stage={event==='none'?-1:['knowledge','prompt','model','ttl'].indexOf(event)} y={90}/><Box x={60} y={185} width={520} height={174} title={invalid.discardCandidate?'無効化の設計候補':'ほかの利用条件も点検'} lines={['知識・prompt・modelの変更に連動','TTLは明示的な無効化の安全網','期限内でも古い版なら使い回さない']} tone={invalid.discardCandidate?'amber':'teal'}/></>}
 {stage===3&&<ReusePair left={['再利用の境界','候補とtenant・scope','同じ文脈と現行の版','期限と共有対象の条件']} right={[reuse.reviewCandidate?'再利用設計の検討候補':'不足する境界へ戻る','個人応答は共有しない','境界をkey・検索へ含める','図は応答を返さない']} id={id} phase={phase}/>}
 {stage===4&&<ReuseThree columns={[["ヒット率","利用の分布","片方だけでない"],["誤ヒット","応答を比較","被害を読む"],["品質の変化","sampling評価","実測を持つ"]]}/>}
 {stage===5&&<ReusePair left={['削減の効果','モデル費用と時間','cache検索の負担','実の分布で測る']} right={['品質と調整','誤ヒットの被害','しきい値と対象を修正','ヒットだけで成功にしない']} id={id} phase={phase}/>}
 <Text x={320} y={409} center small>模式条件は正答・実測・保存・無効化や、実利用の許可ではない。</Text>
 </>}</ReuseCanvas>} controls={({stage,ready})=>stage===0||stage===1?<Select label="共有対象で不足する条件" value={target} onChange={setTarget} ready={ready}>{Object.entries({determinism:'同じ答えでよい',personal:'非パーソナライズ',freshness:'鮮度不問',none:'三条件を照合'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select>:stage===2?<Select label="模式の無効化イベント" value={event} onChange={setEvent} ready={ready}>{Object.entries({knowledge:'知識源の更新',prompt:'promptの更新',model:'modelの更新',ttl:'TTL満了',none:'この四条件には該当なし'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select>:stage===3?<Select label="応答再利用で不足する条件" value={missing} onChange={setMissing} ready={ready}>{Object.entries({match:'一致・類似候補',tenant:'同じtenant',scope:'同じ権限scope',context:'同じ文脈',version:'現行の知識・prompt・model版',expiry:'期限内',target:'共有対象の条件',none:'必要条件を照合'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select>:null}>{children}</ReuseFigure>
}
