'use client'
import {useId,useState} from 'react'
import {HardwareCanvas,HardwareFigure,HardwarePair,HardwareThree,Text,Box,Select,Tokens} from './hardware-serving-primitives'
import {toyOwnershipCost,batchingSlots,toyKvDemand,modelUpdateReview} from '../../lib/hardware-serving-model.mjs'
export function ServingEnginesThroughput({children}){
 const id=useId(),[requests,setRequests]=useState('20'),[step,setStep]=useState('0'),cost=toyOwnershipCost(Number(requests)),slots=batchingSlots(Number(step))
 return <HardwareFigure diagram="serving-engines-throughput" title="自ホストの総費用と、空き枠を使う推論engine" scene={({phase})=><HardwareCanvas diagram="serving-engines-throughput" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['model選定・アプリ基盤と、modelを提供する層を分ける','同じ品質の処理件数と、固定費込みで比べる','機能に加え、hardware・互換・許諾・保守を確認する','要求が終わったslotへ、次の要求を入れる','KVの容量を管理する機能を、engineで利用する'][stage]}</Text>
 {stage===0&&<HardwareThree columns={[["選ぶmodel","用途と品質","選定の正本"],["アプリ基盤","queueとstate","容量の正本"],["model提供層","engineとGPU","本記事の運用"]]}/>}
 {stage===1&&<><HardwareThree columns={[["処理件数",`${requests} 件`,"品質を揃える"],["借りる費用",`${cost.api} 単位`,"一件3の模式"],["持つ費用",`${cost.self} 単位`,"固定120＋件数"]]}/><Text y={327}>{cost.next==='self-cost-review'?'自ホスト費用の検討候補':cost.next==='equal-cost-review'?'模式の費用が同じ':'API費用の検討候補'}</Text><Text y={365} small>無単位の入力で、実料金・損益分岐を示すものではない。</Text></>}
 {stage===2&&<HardwarePair left={['選ぶengineの類型','高throughput系と軽量系','対応hardwareと互換範囲','許諾・保守の継続を照合']} right={['代表例の確認時点','2026-08の原文を保持','TGIのarchiveは旧観測','現在の推奨順は生成しない']} id={id} phase={phase} arrow={false}/>}
 {stage===3&&<><Text y={93}>{`模式の時点 ${step} ／ 完了した記号: ${slots.completed.join('・')||'まだなし'}`}</Text>{slots.slots.map((s,i)=><Box key={i} x={85+i*270} y={135} width={200} height={130} title={`slot ${i+1}: ${s}`} lines={['開始・終了は別々','空いた枠へ次を追加']} tone={i?'violet':'teal'}/>)}<Text y={325}>Aが終了 → Cを追加 ／ Bが終了 → Dを追加</Text><Text y={363} small>記号は要求の模式図。実速度・出力順・納期は示さない。</Text></>}
 {stage===4&&<HardwarePair left={['KVのmemory管理','生成した中間状態を保持','ページ等で効率よく配置','長文脈と多数同時を点検']} right={['engineを選んで使う','成熟した機能を利用','自作で再発明しない','品質と容量は自社で検証']} id={id} phase={phase}/>}
 <Text y={412} small>主権・閉域・custom・遅延の動機を点検。図はserverを動かさない。</Text>
 </>}</HardwareCanvas>} controls={({stage,ready})=>stage===1?<Select label="比較する模式の処理件数" value={requests} onChange={setRequests} ready={ready}><option value="20">20 件</option><option value="60">60 件</option><option value="100">100 件</option><option value="200">200 件</option></Select>:stage===3?<Select label="連続batchingの模式時点" value={step} onChange={setStep} ready={ready}><option value="0">0: AとBが実行中</option><option value="1">1: Aが完了しCを追加</option><option value="2">2: Bが完了しDを追加</option></Select>:null}>{children}</HardwareFigure>
}
export function ServingMemoryRollout({children}){
 const id=useId(),[concurrency,setConcurrency]=useState('2'),[context,setContext]=useState('4'),[missing,setMissing]=useState('rollback'),capacity=toyKvDemand({concurrency:Number(concurrency),context:Number(context)}),update=modelUpdateReview({distributed:missing!=='distribution',rollbackReady:missing!=='rollback',evaluationDone:missing!=='evaluation',cacheLinked:missing!=='cache',versionRecorded:missing!=='version'})
 return <HardwareFigure diagram="serving-memory-rollout" title="同時実行のmemoryと、品質・監視・model更新の連動" scene={({phase})=><HardwareCanvas diagram="serving-memory-rollout" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['重みの外へ、KVと作業領域を積み上げる','同時実行と文脈長を増やすと、重み以外が増える','量子化のlevelごとに、自社taskの品質を評価する','throughputとqueue・末尾遅延を一緒に観測する','配布・load時間と、新旧稼働・切戻しを設計する','更新を評価・cache・版管理へ連動させる'][stage]}</Text>
 {stage===0||stage===1?<><Text y={92}>{`重み14 ＋ KV ${capacity.kv} ＋ 作業領域2 = ${capacity.total} 単位`}</Text><g>{[[14,'#a594ee'],[capacity.kv,'#66dac8'],[2,'#e9bf69']].map(([n,color],i)=><rect key={i} x={60+([0,14,14+capacity.kv][i])*10} y={125} width={n*10} height={31} fill={color}/>)}</g><line x1={300} x2={300} y1={114} y2={171} stroke="#dbe8ef" strokeWidth={3}/><HardwarePair left={[`同時 ${concurrency} × 文脈 ${context}`,'KVの模式量を計算','実modelの係数とは違う','重みが載っても同時で溢れる']} right={[capacity.within?'模式の24枠を照合':'模式の24枠を超える','想定ピークを別に実測','余裕とruntimeを点検','図はmodelをロードしない']} id={id} phase={phase} y={195}/></>:null}
 {stage===2&&<HardwarePair left={['低精度の効果','容量と帯域の負荷を減らす','より多い同時実行の候補','model・task・手法で変わる']} right={['本番前の品質','量子化levelごとに比較','自社の基準を満たすか','載るだけで採用しない']} id={id} phase={phase}/>}
 {stage===3&&<><Tokens labels={['GPU','VRAM','処理数','queue','tail']} y={90}/><HardwareThree y={185} columns={[["資源の観測","遊休と溢れ","実構成で測る"],["処理の観測","throughput","queueの伸び"],["体験の観測","末尾の遅延","app traceへ"]]}/></>}
 {stage===4&&<HardwarePair left={['重みを配布する','大きいfileの転送','load時間と新旧容量','切替に失敗した場合を設計']} right={[update.reviewCandidate?'更新設計の検討候補':'不足する条件へ戻る','新旧稼働と切戻し','更新後の品質を検証','図は切替しない']} id={id} phase={phase}/>}
 {stage===5&&<><Tokens labels={['配布','評価','cache','版','監視']} y={90}/><HardwarePair left={['変更イベントを連動','model版と実行構成','回帰と品質の確認','cache無効化を設計']} right={[update.reviewCandidate?'更新設計の検討候補':'不足する条件へ戻る','各原則の正本へ戻す','file交換だけでは不足','図は実更新しない']} id={id} phase={phase} y={183}/></>}
 <Text y={412} small>容量は無単位の模式入力。実modelのVRAM・品質・速度を測らない。</Text>
 </>}</HardwareCanvas>} controls={({stage,ready})=>stage===0||stage===1?<><Select label="KV模式の同時実行" value={concurrency} onChange={setConcurrency} ready={ready}><option value="1">1</option><option value="2">2</option><option value="4">4</option></Select><Select label="KV模式の文脈量" value={context} onChange={setContext} ready={ready}><option value="1">1</option><option value="2">2</option><option value="4">4</option></Select></>:stage===4||stage===5?<Select label="model更新で不足する条件" value={missing} onChange={setMissing} ready={ready}>{Object.entries({distribution:'配布が未確認',rollback:'切戻しが未設計',evaluation:'品質が未評価',cache:'cache連動が未設定',version:'版が未記録',none:'五条件を照合'}).map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:null}>{children}</HardwareFigure>
}
