'use client'
import {useId,useState} from 'react'
import {ContextCanvas,ContextFigure,ContextPair,ContextThree,Text,Box,Select,Tokens} from './evaluation-context-primitives'
import {simulatorUtterance,simulatorAcceptance} from '../../lib/evaluation-context-model.mjs'
const parts={persona:['ペルソナ','初心者・熟練者など','多様なユーザーへ','Agentが対応できるか'],goal:['目標','達成したいタスク','終了状態の正解へ','満足の言葉だけにせず'],information:['持ち情報','固定した予約番号など','聞かれたら答える','後出しを意図して作る'],patience:['忍耐と振舞い','諦める条件と小出し','曖昧な要求を含める','協力的すぎる役にせず'],tone:['口調','表現の多様性','言い回しへの頑健性','流暢な雑談を目的にせず']}
export function SimulatorRolesConstraints({children}){
 const id=useId(),[part,setPart]=useState('information'),[fault,setFault]=useState('facts'),validity=simulatorUtterance({factsMatch:fault!=='facts',allowedSpeech:fault!=='action',goalBounded:fault!=='goal',endBounded:fault!=='end'})
 return <ContextFigure diagram="simulator-roles-constraints" title="相手役・業務操作・採点と、発話の境界" scene={({phase})=><ContextCanvas diagram="simulator-roles-constraints" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['相手役の満足と、Agentの達成を分ける','評価目的から、振舞いと持ち情報を設計する','目標と終了を、相手役の外から定める','相手役の違反は、Agentの失敗と別に残す','原論文では、ユーザー役はtool通信を見ない'][stage]}</Text>
  {stage===0?<ContextThree columns={[['相手役LLM','Agentと会話する','目標・持ち情報','満足を採点にせず'],['評価対象Agent','業務toolを操作','DB・APIへアクセス','ポリシーを守る'],['採点側','終了状態を照合','必要な回答も確認','相手役とは別責任']]}/>:stage===1?<Box x={64} y={104} width={512} height={207} title={parts[part][0]} lines={parts[part].slice(1)} tone="violet"/>:stage===2?<ContextPair id={id} phase={phase} arrow={false} left={['外から定める条件','目標と終了の基準','出してよい持ち情報','選択肢と状態遷移']} right={['発話へ限定する','脱線と満足を点検','業務toolを渡さない','自由文は人手も残す']}/>:stage===3?<Box x={64} y={104} width={512} height={219} title={validity.simulatorFailure?'相手役の失敗として別集計':'発話の条件を照合した候補'} lines={['予約番号など固定事実を照合','許可した発話・目標・終了','自由文の全てをコード検証できず','図は会話や実Agent評価を行わない']} tone={validity.simulatorFailure?'amber':'teal'} data-simulator-failure={String(validity.simulatorFailure)} data-simulator-agent-outcome-verified="false" data-simulator-conversation-executed="false"/>:<ContextPair id={id} phase={phase} arrow={false} left={['ユーザー役が見るもの','初期シナリオ','Agentとの会話履歴','Agentとtoolの通信は不可視']} right={['Agentと採点の側','業務APIとDBの操作','終了時のDB状態を照合','必要な回答内容も採点']}/>}
 </>}</ContextCanvas>} controls={({stage,ready})=>stage===1?<Select label="相手役に設計する構成" value={part} onChange={setPart} ready={ready}>{Object.entries(parts).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===3?<Select label="相手役の模式違反" value={fault} onChange={setFault} ready={ready}><option value="facts">固定事実の捏造</option><option value="action">発話以外の行動</option><option value="goal">目標から逸脱</option><option value="end">終了条件から逸脱</option><option value="none">必要条件を照合</option></Select>:null}>{children}</ContextFigure>
}
const scenarios={normal:['正常な依頼','必要な情報を持つ','目標に沿う対話','典型ケースを残す'],ambiguous:['曖昧な依頼','確認質問が必要','情報を小出しにする','過度に協力させない'],missing:['情報不足・変更','必要情報を持たない','途中で要求が変わる','詰まりやすさを設計'],refuse:['拒否すべき依頼','ポリシーの境界へ','正しい拒否と代替','単に満足させない']}
export function SimulatorScenariosValidation({children}){
 const id=useId(),[scenario,setScenario]=useState('ambiguous'),[missing,setMissing]=useState('human'),quality=simulatorAcceptance({humanCompared:missing!=='human',knownQualitySeparated:missing!=='quality',factsChecked:missing!=='facts',failuresSeparated:missing!=='failures',repeated:missing!=='repeat',blindspotsChecked:missing!=='blindspots'})
 return <ContextFigure diagram="simulator-scenarios-validation" title="シナリオの分布と、評価する道具の検証" scene={({phase})=><ContextCanvas diagram="simulator-scenarios-validation" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['代表的で困難な実対話から、分布を設計する','人間がする発話・確認との違いを読む','既知の良し悪しを弁別できるか点検する','特定の相手役だけに強い改善を避ける','モデルの共有盲点と、難しさを区分する'][stage]}</Text>
  {stage===0?<Box x={64} y={104} width={512} height={207} title={scenarios[scenario][0]} lines={scenarios[scenario].slice(1)} tone="violet"/>:stage===1?<ContextPair id={id} phase={phase} arrow={false} left={['実際の人間ログ','必要なことを聞くか','人間がしない発話か','実ログから困難を抽出']} right={['シミュレータの対話','人間との差を測る','自然さだけで代表にせず','実態の乖離を修正']}/>:stage===2?<Box x={64} y={104} width={512} height={219} title={quality.reviewCandidate?'評価へ使うことを検討する候補':'道具の検証へ戻る'} lines={['人間ログ・既知の良い／悪いAgent','事実の照合・失敗の別集計','反復と共有盲点の点検','条件照合だけで品質保証にしない']} tone={quality.reviewCandidate?'teal':'amber'} data-simulator-review-candidate={String(quality.reviewCandidate)} data-simulator-quality-guaranteed="false" data-simulator-conversation-executed="false"/>:stage===3?<ContextPair id={id} phase={phase} left={['特定の相手役で改善','同じ相手にだけ強い','固定しすぎの過適合','スコアの上昇を疑う']} right={['実利用者へ照合','人間との対話を併用','反復と新たなシナリオ','現実の分布へ戻す']}/>:<ContextPair id={id} phase={phase} arrow={false} left={['共有する盲点','同系モデルの弱点','同じ言い回しを優遇','流暢さを難しさにせず']} right={['別系統と人手','異なるモデルで点検','人手で難しさを設計','全盲点の解消でない']}/>}
 </>}</ContextCanvas>} controls={({stage,ready})=>stage===0?<Select label="シナリオへ含める分布" value={scenario} onChange={setScenario} ready={ready}>{Object.entries(scenarios).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===2?<Select label="相手役の検証で不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="human">人間ログとの比較</option><option value="quality">既知の良し悪しの弁別</option><option value="facts">固定事実の照合</option><option value="failures">相手役失敗の別集計</option><option value="repeat">反復実行</option><option value="blindspots">共有盲点の点検</option><option value="none">必要条件を照合</option></Select>:null}>{children}</ContextFigure>
}
