'use client'
import {useId,useState} from 'react'
import {BudgetCanvas,BudgetFigure,BudgetPair,BudgetThree,Text,Box,Select,Tokens} from './service-budgets-primitives'
import {sloMeasurement,toyErrorBudget,sloRelease} from '../../lib/service-budgets-model.mjs'
const indicators={success:['タスク成功率','成功の定義と実状態の照合','完了率という代理との区分','タスクに合う測定を設計'],judge:['回答品質の合格率','本番出力をサンプリング','judgeの検証と較正','判定の信頼を先に点検'],deviation:['幻覚率・逸脱率','根拠なし回答・制約違反','検出の網羅性の限界','検知漏れを保持する'],escalation:['エスカレーション率','人へ回る割合を測る','低すぎ: 抱え込み','高すぎ: 役立たない'],combined:['時間・費用との複合','p95とリクエスト単価','品質の指標と併記する','片方だけで判断せず']}
export function SloIndicatorsReliability({children}){
 const id=useId(),[indicator,setIndicator]=useState('judge'),[missing,setMissing]=useState('judge'),result=sloMeasurement({definitionKnown:missing!=='definition',judgeValidated:missing!=='judge',samplingKnown:missing!=='sampling',measurementWindowKnown:missing!=='window'})
 return <BudgetFigure diagram="slo-indicators-reliability" title="AIの品質指標と、測定の信頼から決める目標" scene={({phase})=><BudgetCanvas diagram="slo-indicators-reliability" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['測る指標と、目標・予算・対応を区分する','品質と技術の指標を組み合わせる','品質の95%を、正しく測れているか点検する','現状から、必要な水準を関係者と合意する','品質・時間・費用を並べて、暴走を見落とさない'][stage]}</Text>
  {stage===0?<BudgetThree columns={[['SLIを測る','記録と品質の信号','judgeの検証・較正','測定基盤が前提'],['SLOを宣言','指標の目標を合意','許容失敗を予算へ','変更判断へ接続'],['対応と契約','発火後の対応手順','対外約束はSLA','目標達成と区分']]}/>:stage===1?<><Tokens labels={['成功','採点','逸脱','移管','複合']} selected={[Object.keys(indicators).indexOf(indicator)]} y={85}/><Box x={64} y={184} width={512} height={192} title={indicators[indicator][0]} lines={indicators[indicator].slice(1)} tone="violet" data-slo-indicator={indicator}/></>:stage===2?<Box x={64} y={103} width={512} height={219} title={result.reviewCandidate?'実際の測定を検討する候補':'不足する測定の定義と検証へ戻す'} lines={['成功定義・judgeの較正と検証','サンプリングの方法と測定期間','模式の照合を実品質95%にしない','図は契約や実採点を行わない']} tone={result.reviewCandidate?'teal':'amber'} data-slo-measurement-candidate={String(result.reviewCandidate)} data-slo-quality-measured="false" data-slo-contract-created="false"/>:stage===3?<BudgetPair id={id} phase={phase} left={['まずベースライン','現状のSLIを測る','影響に合う必要水準','品質100%を目標にせず']} right={['関係者と目標を合意','維持／引上げる水準','タスクごとの影響度','過剰品質の費用を読む']}/>:<BudgetThree columns={[['品質の目標','成功定義と信頼','幻覚・逸脱も点検','実タスクで測る'],['時間と費用','品質と併記する','片方だけを追わず','費用暴走を点検'],['必要十分な水準','現状と影響で合意','誤答と棄権の負担','適切な水準を残す']]}/>}
 </>}</BudgetCanvas>} controls={({stage,ready})=>stage===1?<Select label="SLOで確認するSLI候補" value={indicator} onChange={setIndicator} ready={ready}>{Object.entries(indicators).map(([value,row])=><option key={value} value={value}>{row[0]}</option>)}</Select>:stage===2?<Select label="品質SLIの不足する測定条件" value={missing} onChange={setMissing} ready={ready}><option value="definition">成功・品質の定義</option><option value="judge">judgeの較正と検証</option><option value="sampling">サンプリングの方法</option><option value="window">測定する期間</option><option value="none">必要条件を照合</option></Select>:null}>{children}</BudgetFigure>
}
export function SloBudgetReleaseSla({children}){
 const id=useId(),[failed,setFailed]=useState('6'),[target,setTarget]=useState('99'),[missing,setMissing]=useState('measurement'),budget=toyErrorBudget({total:1000,failed:Number(failed),targetPercent:Number(target)}),release=sloRelease({budgetRemaining:budget.remaining,measurementTrusted:missing!=='measurement',guardPassed:missing!=='guard'})
 return <BudgetFigure diagram="slo-budget-release-sla" title="失敗予算からの変更判断と、SLAへの昇格" scene={({phase})=><BudgetCanvas diagram="slo-budget-release-sla" phase={phase} id={id}>{({stage})=><>
  <Text y={34}>{['期間と母数を定めて、許容失敗量を読む','予算が残る場合と、枯渇した場合を分ける','残量だけで、未検証の変更を出さない','内部の目標と、対外の契約を分担する','内部目標より余裕のある約束を設計する','変更前後を、回帰と段階リリースで確認する'][stage]}</Text>
  {stage===0||stage===1?<>
   <Text y={91}>{`模式1000件・目標${target}%: 許容失敗${budget.allowed}件`}</Text>
   <Box x={48} y={138} width={248} height={154} title={`失敗: ${failed}件`} lines={['モデル・promptの変更','知識源の劣化も消費','実品質の測定ではない']} tone="violet"/>
   <Box x={344} y={138} width={248} height={154} title={`残量: ${budget.remaining}件`} lines={[budget.exhausted?'新規変更を凍結する型':'機能追加も検討する型','品質の改善へ人を回す','超過は判断のトリガー']} tone={budget.exhausted?'amber':'teal'}/>
   <Text y={379} small>原文99%なら許容1%。模式の目標は自社の最適値ではない。</Text><g data-slo-allowed={budget.allowed} data-slo-remaining={budget.remaining} data-slo-exhausted={String(budget.exhausted)} data-slo-quality-measured="false"/>
  </>:stage===2?<Box x={64} y={103} width={512} height={219} title={release.reviewCandidate?'変更の採用を検討する候補':'品質改善と測定・guardへ戻す'} lines={[`模式の残量: ${budget.remaining}件`,'測定の信頼・変更のguardを確認','予算だけで未検証の変更を出さず','図は実リリース・契約を行わない']} tone={release.reviewCandidate?'teal':'amber'} data-slo-release-candidate={String(release.reviewCandidate)} data-slo-deployed="false" data-slo-contract-created="false"/>:stage===3?<BudgetPair id={id} phase={phase} arrow={false} left={['内部SLO','維持する指標の目標','失敗予算で優先順位','実際のSLIから測る']} right={['対外SLA','顧客との契約と結果','約束する指標を限定','信頼と統制可能性']}/>:stage===4?<BudgetPair id={id} phase={phase} left={['原文の例: 内部99%','品質の目標を測る','時間と費用も併記','小さな劣化への余裕']} right={['原文の例: 対外95%','内部より余裕ある約束','回答正解を無条件保証せず','API契約の正本へ']}/>:<BudgetThree columns={[['変更と静かな消費','modelとprompt','知識源の劣化','予算と信号で監視'],['変更前後を測る','回帰と段階配信','違反する変更は保留','guardを関門にする'],['判定も測り直す','judgeの世代交代','モデル更新の影響','SLI再測定を継続']]}/>}
 </>}</BudgetCanvas>} controls={({stage,ready})=>stage<=2?<><Select label="SLOの模式目標" value={target} onChange={setTarget} ready={ready}><option value="99">99%</option><option value="95">95%</option><option value="90">90%</option></Select><Select label="期間内1000件の模式失敗件数" value={failed} onChange={setFailed} ready={ready}><option value="6">6件</option><option value="10">10件</option><option value="12">12件</option><option value="50">50件</option></Select>{stage===2&&<Select label="SLO変更の不足する条件" value={missing} onChange={setMissing} ready={ready}><option value="measurement">測定の信頼</option><option value="guard">変更のguard</option><option value="none">必要条件を照合</option></Select>}</>:null}>{children}</BudgetFigure>
}
