'use client'
import {useId,useState} from 'react'
import {AdversityFigure,AdversityCanvas,AdversityPair,AdversityThree,Text,Box,Wire,Select,Tokens} from './security-adversity-primitives'
import {assetReview,assetPromotion,updateReview} from '../../lib/security-adversity-model.mjs'
const assets=[['modelの重み','形式と読込コード','出所・同一性・許諾'],['学習・調整data','挙動へ長く残る','出所と混入を点検'],['prompt・skill','共有した指示','権限と内容を審査'],['MCP・tool','接続と更新','対象・版・実権限'],['通常の依存','package・実行code','署名・固定・監査']]
export function SupplyAssetIntegrity({children}){
 const id=useId(),[asset,setAsset]=useState('0'),[missing,setMissing]=useState('none'),row=assets[Number(asset)],review=assetReview({sourceChecked:missing!=='source',integrityMatched:missing!=='integrity',licenseChecked:missing!=='license',registryChecked:missing!=='registry'})
 return <AdversityFigure diagram="supply-asset-integrity" title="導入資産の出所・同一性・許諾と、残る実行制約" scene={({phase})=><AdversityCanvas diagram="supply-asset-integrity" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['導入前の受入と、実行時の安全を分ける','五つのAI資産を、使う場所と能力で棚卸しする','選んだ資産が、何を変えるかを読む','出所と同一性は、無害性とは別の証拠','署名・許諾・審査は、別々に照合する','受入後も、権限・隔離・監視を維持する'][stage]}</Text>
 {stage===0&&<AdversityPair left={['導入する資産','外部から取得','審査と限定試用','出所と版を記録']} right={['実行時の境界','最小限のdataと権限','実行code・接続を隔離','更新と作用を監視']} id={id} phase={phase}/>}
 {stage===1&&<>{assets.map((r,i)=><g key={r[0]}><rect x={40} y={78+i*58} width={560} height={48} rx={6} fill="#142b39" stroke={Number(asset)===i?'#68ded0':'#526b7c'}/><Text x={164} y={110+i*58} small>{r[0]}</Text><Text x={433} y={110+i*58} small>{r[1]}</Text></g>)}</>}
 {stage===2&&<AdversityPair left={[row[0],row[1],row[2],'必要な能力だけで試す']} right={['受入と作用の照合','信頼した出所を点検','形式と差分を確認','限定環境で挙動を試す']} id={id} phase={phase}/>}
 {stage===3&&<AdversityPair left={['同一性の証拠','信頼した出所の署名','期待するchecksum','取得物の一致を照合']} right={['別に残る判断','挙動は無害か','利用条件に適うか','必要な権限で使えるか']} id={id} phase={phase} arrow={false}/>}
 {stage===4&&<><Tokens labels={['出所','同一性','license','registry']} selected={[['source','integrity','license','registry'].indexOf(missing)]} y={88}/><AdversityPair left={['四つを分けて確認','誰が公開した何か','一致と許諾を別に読む','審査済かを確認']} right={[review.reviewCandidate?'受入設計の検討候補':'不足する受入確認へ戻る','hash一致は無害性でない','図は実署名を検証しない','受入後の制約を維持']} id={id} phase={phase} y={203} height={171}/></>}
 {stage===5&&<AdversityThree columns={[["権限の上限","対象・操作・宛先","必要な能力だけ"],["隔離と試験","codeと接続を制限","実dataは限定"],["更新と観測","固定した版と差分","異常を調べる"]]}/>}
 <Text y={412} small>署名・hash・形式の確認は、無害性・zero riskの保証でない。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===1||stage===2?<Select label="棚卸しするAI資産" value={asset} onChange={setAsset} ready={ready}>{assets.map((r,i)=><option key={i} value={i}>{r[0]}</option>)}</Select>:stage===4?<Select label="資産審査で不足する条件" value={missing} onChange={setMissing} ready={ready}>{[['none','全条件を確認'],['source','出所'],['integrity','同一性'],['license','license'],['registry','registry審査']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:null}>{children}</AdversityFigure>
}
export function SupplyAdmissionUpdate({children}){
 const id=useId(),[missing,setMissing]=useState('none'),[change,setChange]=useState('new-unreviewed'),promotion=assetPromotion({reviewed:missing!=='review',isolatedTrialPassed:missing!=='trial',rightsLimited:missing!=='rights',explicitApproval:missing!=='approval',sameVersion:missing!=='version'}),update=updateReview({sameVersion:change==='same',oldReviewValid:true,deltaReviewed:change==='new-reviewed',newTrialPassed:change==='new-reviewed'})
 return <AdversityFigure diagram="supply-admission-update" title="限定試用から昇格へ、版が変われば受入へ戻る" scene={({phase})=><AdversityCanvas diagram="supply-admission-update" phase={phase} id={id}>{({stage})=><>
 <Text y={38}>{['審査した資産を、限定した隔離環境で試す','同じ版・必要な権限・承認を揃えて判断へ','一つのinventoryで、版・権限・場所を結ぶ','更新で変わった内容は、旧版の成功と分ける','版の固定と差分・再試用を、更新の前に置く','異常から、該当する版と使う場所を辿る'][stage]}</Text>
 {stage===0&&<><AdversityThree columns={[["審査","出所・同一性","許諾と審査"],["隔離した試用","限定data・権限","作用を観測"],["昇格判断","同じ版と必要権限","明示的に確認"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/><Text y={346}>試用成功から、全権や本番dataを自動で渡さない</Text></>}
 {stage===1&&<><Tokens labels={['審査','試用','最小権限','承認','同じ版']} selected={[['review','trial','rights','approval','version'].indexOf(missing)]} y={88}/><AdversityPair left={['昇格前の条件','限定環境の同じ版','必要な範囲へ権限を絞る','明示的な確認を保つ']} right={[promotion.reviewCandidate?'昇格判断の検討候補':'不足条件へ戻る','図は権限を付与しない','全権への昇格でない','実運用の受入へ戻す']} id={id} phase={phase} y={203} height={171}/></>}
 {stage===2&&<><Box x={40} y={83} width={560} height={78} title="統制のinventoryに統合" lines={['作業用の追加台帳は作らない']}/>{[['出所・版','誰が公開した何か'],['受入日・権限','いつ、何を許可したか'],['利用する場所','どのAgentと環境で使うか']].map(([a,b],i)=><g key={a}><Text x={162} y={223+i*56} small>{a}</Text><Text x={447} y={223+i*56} small>{b}</Text></g>)}</>}
 {stage===3||stage===4?<><AdversityPair left={[change==='same'?'検証した同じ版':'変更された新しい版','MCP・tool・skillの差分','前の版での成功を保持','新しい挙動は別に確認']} right={[update.reviewCandidate?'更新設計の検討候補':'差分と再試用へ戻る',update.oldApprovalTransferred?'同じ版の受入を参照':'旧版の承認を転用しない','固定は脆弱性の解消でない','図は実更新を行わない']} id={id} phase={phase}/><Text y={343}>版の固定 → 差分審査 → 限定再試用 → 判断</Text></>:null}
 {stage===5&&<><AdversityThree columns={[["異常の観測","作用と接続先","導入後も点検"],["inventoryへ","該当する版","権限と場所"],["限定した対処","影響を照合","停止・受入を判断"]]}/><Wire id={id} d="M208 181H230" active phase={phase}/><Wire id={id} d="M408 181H430" active phase={phase}/></>}
 <Text y={412} small>旧版の成功を未確認版へ転用しない。図は実更新・停止をしない。</Text>
 </>}</AdversityCanvas>} controls={({stage,ready})=>stage===1?<Select label="昇格判断で不足する条件" value={missing} onChange={setMissing} ready={ready}>{[['none','全条件を確認'],['review','審査'],['trial','限定試用'],['rights','最小権限'],['approval','承認'],['version','同じ版']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>:stage===3||stage===4?<Select label="資産の版と再検証" value={change} onChange={setChange} ready={ready}><option value="same">同じ検証済み版</option><option value="new-unreviewed">新しい未確認の版</option><option value="new-reviewed">差分審査と再試用済みの新版</option></Select>:null}>{children}</AdversityFigure>
}
