'use client'
import {ReadingFigure} from './reading-figure'
import {SceneBase} from './concept-scene-primitives'
import {Box,Wire,Select} from './learning-scene-primitives'
import {VENDOR_PROMPT_CONTROLS_STAGES,vendorPromptControlsFrame,vendorExampleAdmission,vendorPromptAcceptance} from '../../lib/vendor-prompt-controls-model.mjs'
import './vendor-prompt-controls.css'
export {Text,Box,Wire,Select,Tokens} from './learning-scene-primitives'
export function VendorCanvas({diagram,phase,id,children}){const frame=vendorPromptControlsFrame(diagram,phase);return <SceneBase id={id} title={frame.title} detail={frame.detail} className="aw-scene lf-scene" data-vendor-prompt-controls-diagram={diagram} data-stage={frame.stage}>{children(frame)}</SceneBase>}
export function VendorFigure({diagram,title,scene,controls,children}){return <ReadingFigure diagramId={diagram} title={title} eyebrow="PROMPT / MODEL CONTROLS" stages={VENDOR_PROMPT_CONTROLS_STAGES[diagram]} renderScene={scene} renderControls={controls} className="vendor-prompt-controls-walkthrough" footnote="元記事の確認日と条件を読む模式図です。実モデル・API・業務操作は実行しません。">{children}</ReadingFigure>}
export function VendorPair({left,right,id,phase,y=86,arrow=true}){return <><Box x={32} y={y} width={260} height={177} title={left[0]} lines={left.slice(1)} tone="violet"/>{arrow&&<Wire id={id} d={`M292 ${y+88}H340`} active phase={phase}/>}<Box x={348} y={y} width={260} height={177} title={right[0]} lines={right.slice(1)} tone="teal"/></>}
export function ExampleGate({state}){const result=vendorExampleAdmission({aligned:state!=='conflict',representative:state!=='biased',repetitive:state==='repeated'});return <Box x={64} y={274} width={512} height={94} title={result.reviewCandidate?'例を評価する候補':'例と指示の不足を残す'} tone={result.reviewCandidate?'teal':'amber'} data-vendor-example-candidate={String(result.reviewCandidate)} data-vendor-quality-guaranteed="false"/>}
export function ExampleSelect({state,setState,ready}){return <Select label="例の照合条件" value={state} onChange={setState} ready={ready}><option value="conflict">指示と例が矛盾</option><option value="biased">代表性が不足</option><option value="repeated">類似例が多すぎる</option><option value="checked">必要な条件を照合</option></Select>}
export function MigrationGate({missing}){const result=vendorPromptAcceptance({modelApiChecked:missing!=='model',contractChecked:missing!=='contract',regressionPassed:missing!=='regression',authorityChecked:missing!=='authority'});return <Box x={64} y={112} width={512} height={190} title={result.reviewCandidate?'移行を検討する候補':'不足を残して再評価する'} lines={['モデル・APIの対応と製品の契約','代表タスクの回帰と必要な権限','既定と旧依存も照合する','図は本番を変更しない']} tone={result.reviewCandidate?'teal':'amber'} data-vendor-migration-candidate={String(result.reviewCandidate)} data-vendor-deployment-executed="false"/>}
export function MigrationSelect({missing,setMissing,ready}){return <Select label="移行前の不足条件" value={missing} onChange={setMissing} ready={ready}><option value="model">モデル・APIの対応</option><option value="contract">製品の契約</option><option value="regression">代表タスクの回帰</option><option value="authority">必要な権限</option><option value="none">必要条件を照合</option></Select>}
