'use client'
import {useId,useState} from 'react'
import {OpsCanvas,OpsFigure,OpsPair,Text,Box,Wire,Select,Tokens} from './release-response-primitives'
import {configurationTrace,releaseAllocation,rollbackPath,migrationGate} from '../../lib/release-response-model.mjs'
const keys=['code','prompt','tool','model','settings','evaluation'],labels=['コード','prompt','tool定義','モデル','生成設定','評価側']
export function VersionCompositionPinning({children}){
 const id=useId(),[missing,setMissing]=useState('evaluation'),[reference,setReference]=useState('snapshot')
 const traced=configurationTrace(Object.fromEntries(keys.map(k=>[k,missing!==k])))
 return <OpsFigure diagram="version-composition-pinning" title="六つの構成と、応答の版・モデルの期限" scene={({phase})=><OpsCanvas diagram="version-composition-pinning" phase={phase} id={id}>{({stage})=><>
 <Text x={320} y={38} center>{['挙動と物差しの組合せ全体を記録する','生成の五構成と、評価側の版を束ねる','当時の応答から六つの構成へ遡る','promptとtoolも履歴・検査を通す','固定した指定と、更新を受ける参照を分ける','提供経路別の期限から移行を計画する'][stage]}</Text>
 {stage<=1&&<>{labels.map((label,i)=><Box key={label} x={32+i%3*200} y={90+Math.floor(i/3)*165} width={176} height={125} title={label} lines={[["実装の変更","処理の経路"],["指示と例","一行でも影響"],["名前・説明","引数schema"],["IDと版","提供元も記録"],["出力の条件","各種の設定"],["dataとjudge","品質の物差し"]][i]} tone={i===5?'amber':i%2?'teal':'violet'}/>)}</>}
 {stage===2&&<><Tokens labels={labels} stage={missing==='none'?-1:keys.indexOf(missing)} y={85}/><Box x={65} y={180} width={510} height={160} title={traced.identifiedCandidate?'組合せ特定の検討候補':'不足する版へ戻る'} lines={[missing==='none'?'六構成の記録条件を照合':`${labels[keys.indexOf(missing)]}の記録が不足`,'同じ出力の決定性は別の条件','実ログを復元した結果ではない']} tone={traced.identifiedCandidate?'teal':'amber'}/></>}
 {stage===3&&<OpsPair left={['管理する変更','同じrepoの履歴','レビューと回帰','応答へ版を記録']} right={['迂回する直接編集','管理画面やDB','履歴・review・CIなし','緊急時もフラグへ']} id={id} phase={phase} arrow={false}/>}
 {stage===4&&<OpsPair left={['snapshot参照','特定の版を指定','自分の移行を評価','提供条件を確認']} right={[reference==='snapshot'?'pinでも期限がある':'aliasは更新を受ける',reference==='snapshot'?'永久提供ではない':'提供元が参照先を更新','版と期限を記録','原文TODOで確認']} id={id} phase={phase} arrow={false}/>}
 {stage===5&&<><Box x={60} y={90} width={520} height={112} title="廃止の告知と期限" lines={['利用モデルと提供経路を点検','実モデルの日付は図に設定しない']} tone="amber"/><Wire id={id} d="M320 202V239" active phase={phase}/><Box x={60} y={241} width={520} height={112} title="期限付きの移行計画" lines={['新モデルの評価・調整・段階切替','旧モデルへ戻せる期間も点検']} tone="teal"/></>}
 {stage<5&&<Text x={320} y={410} center small>組合せの特定・pinは、決定性や永久提供を保証しない。</Text>}
 </>}</OpsCanvas>} controls={({stage,ready})=>stage===2?<Select label="構成特定で不足する版" value={missing} onChange={setMissing} ready={ready}>{keys.map((key,i)=><option key={key} value={key}>{labels[i]}</option>)}<option value="none">六構成を照合</option></Select>:stage===4?<Select label="モデル参照の模式条件" value={reference} onChange={setReference} ready={ready}><option value="snapshot">特定版をpin</option><option value="alias">aliasを参照</option></Select>:null}>{children}</OpsFigure>
}
export function VersionRolloutMigration({children}){
 const id=useId(),[mode,setMode]=useState('shadow'),[rollbackMissing,setRollbackMissing]=useState('exercise'),[judge,setJudge]=useState('changed'),[migrationMissing,setMigrationMissing]=useState('human')
 const allocation=releaseAllocation(mode),rollback=rollbackPath({flagPrepared:rollbackMissing!=='flag',flagExercised:rollbackMissing!=='exercise',oldAvailable:rollbackMissing!=='retired'}),migration=migrationGate({judgeChanged:judge==='changed',judgeHumanValidated:migrationMissing!=='human',suiteChecked:migrationMissing!=='suite',newFailuresRead:migrationMissing!=='failures',promptChecked:migrationMissing!=='prompt',stagedPlan:migrationMissing!=='stages'})
 return <OpsFigure diagram="version-rollout-migration" title="段階リリースと、物差し・差分・戻る経路" scene={({phase})=><OpsCanvas diagram="version-rollout-migration" phase={phase} id={id}>{({stage})=><>
 <Text x={320} y={38} center>{['評価セットより広い本番分布を点検する','誰に返し、どの構成で処理するかを分ける','切替手段の準備・演習・提供期間を照合する','judgeを変える場合は先に人手で再検証する','全評価と新しい失敗を読み、調整して移行する','安定まで旧構成を残し、期限内の経路を保つ'][stage]}</Text>
 {stage===0&&<OpsPair left={['評価スイート','既知の入力分布','変更の回帰を点検','全入力ではない']} right={['本番の分布','未知の条件も含む','段階的に影響を限定','品質と技術を比較']} id={id} phase={phase}/>}
 {stage===1&&<>{[['旧を返す',allocation.oldUserPercent],['新を返す',allocation.newUserPercent],['新で処理',allocation.newProcessedPercent]].map(([label,value],i)=><g key={label}><Text x={42} y={127+i*79} small>{label}</Text><rect x="162" y={100+i*79} width={value*3.7} height="38" rx="6" className={i===0?'rr-bar-violet':'rr-bar-teal'}/><Text x={596} y={127+i*79} center small>{`${value}%`}</Text></g>)}<Text x={320} y={373} center small>{mode==='shadow'?['新結果はユーザーへ返さない。','shadowの副作用toolは実行しない。']:['図の10%は模式例。実配信は行わない。','実際の品質・技術指標を比較する。']}</Text></>}
 {stage===2&&<Box x={65} y={110} width={510} height={210} title={rollback.reviewCandidate?'戻る経路の検討候補':'不足する切替条件へ戻る'} lines={['事前フラグを準備し演習','旧構成がまだ利用可能','デプロイせず切替える設計','既に起きた作用は取消せない']} tone={rollback.reviewCandidate?'teal':'amber'}/>}
 {stage===3&&<OpsPair left={['物差しの変更',judge==='changed'?'judgeの版も変更':'judgeの版は保持','人手ラベルと照合','新judgeを先に検証']} right={['Agentの比較','新モデルの全評価','物差しの条件を明示','新たな失敗を読む']} id={id} phase={phase}/>}
 {stage===4&&<Box x={65} y={110} width={510} height={210} title={migration.reviewCandidate?'移行の検討候補':'不足する検証へ戻る'} lines={['judge条件と全評価','新しく落ちたケースを読む','promptを点検・再調整','shadow→canary→全量を計画']} tone={migration.reviewCandidate?'teal':'amber'}/>}
 {stage===5&&<OpsPair left={['旧構成を保持','新構成の安定を確認','廃止の告知を追う','期限前に評価と移行']} right={['提供終了の境界','廃止後は利用不可','旧モデルへ戻れない','経路別の期限を確認']} id={id} phase={phase}/>}
 {stage!==1&&<Text x={320} y={400} center small>検討条件の照合は、実評価・配信・切替の実施ではない。</Text>}
 </>}</OpsCanvas>} controls={({stage,ready})=>stage===1?<Select label="模式の段階リリース" value={mode} onChange={setMode} ready={ready}><option value="old">旧構成だけ</option><option value="shadow">shadowで新旧を処理</option><option value="canary">canaryで10%を新へ</option><option value="full">全量を新へ</option></Select>:stage===2?<Select label="戻る経路で不足する条件" value={rollbackMissing} onChange={setRollbackMissing} ready={ready}><option value="flag">切替フラグ</option><option value="exercise">切替の演習</option><option value="retired">旧モデルの提供</option><option value="none">必要条件を照合</option></Select>:stage===3||stage===4?<><Select label="移行でのjudge変更" value={judge} onChange={setJudge} ready={ready}><option value="changed">judgeも変更する</option><option value="unchanged">judgeは保持する</option></Select>{stage===4&&<Select label="移行で不足する確認" value={migrationMissing} onChange={setMigrationMissing} ready={ready}><option value="human">judgeの人手再検証</option><option value="suite">全評価スイート</option><option value="failures">新しい失敗ケース</option><option value="prompt">promptの点検</option><option value="stages">段階移行の計画</option><option value="none">必要条件を照合</option></Select>}</>:null}>{children}</OpsFigure>
}
