#!/usr/bin/env node
// 共通規約と対応済みスキルから Claude Code の互換入口を決定生成する。
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const sharedSkills = Object.freeze(['examples-check', 'new-doc', 'publish-review', 'quarterly-maintenance'])
const normalize = text => text.replaceAll('\r\n', '\n').trimEnd() + '\n'
const banner = source => `<!-- Generated by scripts/sync-harness.mjs from ${source}. Edit the source, then run node scripts/sync-harness.mjs --write. -->`

function filesIn(directory) {
  if (!existsSync(directory)) return []
  if (lstatSync(directory).isSymbolicLink()) throw new Error(`symlink は同期対象にできません: ${directory}`)
  return readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0).flatMap(entry => {
    const file = path.join(directory, entry.name)
    if (entry.isSymbolicLink()) throw new Error(`symlink は同期対象にできません: ${file}`)
    return entry.isDirectory() ? filesIn(file) : [file]
  })
}

export function renderClaude(agents) {
  const common = normalize(agents).replace(/^# AGENTS\.md[^\n]*\n/, '# CLAUDE.md — 共通契約の互換入口\n').replace('このファイルが共通契約の正本です。', '共通契約の正本は [AGENTS.md](AGENTS.md) です。')
  return banner('AGENTS.md') + '\n\n' + common + '\n## Claude Code での実行\n\n共通契約は上記の生成内容に従い、対応する作業のスキルは `.claude/skills/` から使います。専任担当は `.claude/agents/`、実行権限とフックは `.claude/settings.json` がこの製品の入口です。Codex の設定ファイルを Claude Code が読み込むとは扱いません。定期最新化の起動は Codex 専用です。\n'
}

export function renderSkill(source, text) {
  const normalized = normalize(text)
  const frontmatter = /^---\n[\s\S]*?\n---\n/.exec(normalized)
  if (!frontmatter) throw new Error(`スキルに front matter がありません: ${source}`)
  return `${frontmatter[0]}\n${banner(source)}\n${normalized.slice(frontmatter[0].length)}`
}

// --check は読み取りのみ。--write も未知の互換ファイルを削除せず、所有者に判断を返す。
export function syncHarness(root, { write = false } = {}) {
  root = path.resolve(root)
  const expected = new Map([['CLAUDE.md', Buffer.from(renderClaude(readFileSync(path.join(root, 'AGENTS.md'), 'utf8'))) ]])
  for (const skill of sharedSkills) {
    const sourceRoot = path.join(root, '.agents/skills', skill)
    if (!existsSync(path.join(sourceRoot, 'SKILL.md'))) throw new Error(`正本スキルがありません: ${skill}`)
    for (const file of filesIn(sourceRoot)) {
      const suffix = path.relative(sourceRoot, file).replaceAll('\\', '/')
      const source = `.agents/skills/${skill}/${suffix}`
      const destination = `.claude/skills/${skill}/${suffix}`
      const content = suffix === 'SKILL.md' ? Buffer.from(renderSkill(source, readFileSync(file, 'utf8'))) : readFileSync(file)
      expected.set(destination, content)
    }
  }
  const unexpected = filesIn(path.join(root, '.claude/skills')).map(file => path.relative(root, file).replaceAll('\\', '/')).filter(file => !expected.has(file))
  const mismatches = []
  for (const [file, desired] of expected) {
    const destination = path.join(root, file)
    // 生成先の symlink / junction 経由で作業ディレクトリ外へ書き込まない。
    let ancestor = destination
    while (ancestor !== root) {
      if (existsSync(ancestor) && lstatSync(ancestor).isSymbolicLink()) throw new Error(`symlink は同期先にできません: ${ancestor}`)
      ancestor = path.dirname(ancestor)
    }
    const current = existsSync(destination) ? readFileSync(destination) : undefined
    const same = current && (file.endsWith('.md') ? normalize(current.toString('utf8')) === normalize(desired.toString('utf8')) : current.equals(desired))
    if (same) continue
    mismatches.push(file)
    if (write && unexpected.length === 0) {
      mkdirSync(path.dirname(destination), { recursive: true })
      writeFileSync(destination, desired)
    }
  }
  return { mismatches, unexpected, written: write && unexpected.length === 0 ? mismatches : [] }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2)
    if (args.length > 1 || (args[0] && !['--check', '--write'].includes(args[0]))) throw new Error('Usage: node scripts/sync-harness.mjs [--check|--write]')
    const write = args[0] === '--write'
    const result = syncHarness(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), { write })
    for (const file of result.unexpected) console.error(`未管理の互換ファイルです。所有者と正本を確認してください: ${file}`)
    for (const file of result.mismatches) console[write && !result.unexpected.length ? 'log' : 'error'](`${write && !result.unexpected.length ? '更新' : '同期が必要'}: ${file}`)
    if (result.unexpected.length || (!write && result.mismatches.length)) process.exitCode = 1
    else console.log(`harness sync: ${write ? 'written' : 'verified'}`)
  } catch (error) {
    console.error(error.message)
    process.exitCode = 1
  }
}
