#!/usr/bin/env node
// 共通規約と対応済みスキルから Claude Code の互換入口を決定生成する。
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const sharedSkills = Object.freeze(['examples-check', 'new-doc', 'publish-review', 'quarterly-maintenance'])
export const sharedRoles = Object.freeze(['doc-reviewer', 'freshness-checker'])
const normalize = text => text.replaceAll('\r\n', '\n').trimEnd() + '\n'
const banner = source => `<!-- Generated by scripts/sync-harness.mjs from ${source}. Edit the source, then run node scripts/sync-harness.mjs --write. -->`

function assertNoLinks(root, file) {
  let ancestor = file
  while (true) {
    let stat
    try { stat = lstatSync(ancestor) } catch (error) { if (error.code !== 'ENOENT') throw error }
    if (stat?.isSymbolicLink()) throw new Error(`symlink は同期対象にできません: ${ancestor}`)
    if (ancestor === root) break
    const parent = path.dirname(ancestor)
    if (parent === ancestor) throw new Error('同期対象が作業領域外です')
    ancestor = parent
  }
}

function filesIn(directory) {
  if (!existsSync(directory)) return []
  if (lstatSync(directory).isSymbolicLink()) throw new Error(`symlink は同期対象にできません: ${directory}`)
  return readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0).flatMap(entry => {
    const file = path.join(directory, entry.name)
    if (entry.isSymbolicLink()) throw new Error(`symlink は同期対象にできません: ${file}`)
    return entry.isDirectory() ? filesIn(file) : [file]
  })
}

export function renderClaude(agents) {
  const common = normalize(agents).replace(/^# AGENTS\.md[^\n]*\n/, '# CLAUDE.md — 共通契約の互換入口\n').replace('このファイルが共通契約の正本です。', '共通契約の正本は [AGENTS.md](AGENTS.md) です。')
  return banner('AGENTS.md') + '\n\n' + common + '\n## Claude Code での実行\n\n共通契約は上記の生成内容に従い、対応する作業のスキルは `.claude/skills/` から使います。専任担当は `.claude/agents/`、実行権限とフックは `.claude/settings.json` がこの製品の入口です。Codex の設定ファイルを Claude Code が読み込むとは扱いません。定期最新化の起動は Codex 専用です。\n\nClaude が編集した commit・PR は末尾に `Agent: claude` と `Co-authored-by: Claude <noreply@anthropic.com>` をこの綴りで1回ずつ付けます。Codex と共同編集なら `Agent: codex,claude` と両者の名義を定義順に記載します。製品のモデル版・Claude-Session・Generated 行は付けません。`.claude/settings.json` の attribution は製品既定の追加を無効化します。branch は `claude/<kebab-slug>` と `codex/<kebab-slug>` も許容します。提出前は [Git 共通規約](harness/git-rules.md)の検査を行います。\n'
}

export function renderSkill(source, text) {
  const normalized = normalize(text)
  const frontmatter = /^---\n[\s\S]*?\n---\n/.exec(normalized)
  if (!frontmatter) throw new Error(`スキルに front matter がありません: ${source}`)
  return `${frontmatter[0]}\n${banner(source)}\n${normalized.slice(frontmatter[0].length)}`
}

export function renderRole(role, client) {
  if (!sharedRoles.includes(role.name) || typeof role.description !== 'string' || typeof role.instructions !== 'string') throw new Error('role 正本の形式が不正です')
  const source = `harness/roles/${role.name}.json`
  if (client === 'codex') return `# Generated from ${source}; run node scripts/sync-harness.mjs --write.\nname = ${JSON.stringify(role.name)}\ndescription = ${JSON.stringify(role.description)}\nsandbox_mode = "read-only"\ndeveloper_instructions = ${JSON.stringify(normalize(role.instructions))}\n`
  const lines = ['---', `name: ${role.name}`, `description: ${JSON.stringify(role.description)}`, `tools: ${role.claude_tools.join(', ')}`]
  if (role.claude_hooks) lines.push(`hooks: ${JSON.stringify(role.claude_hooks)}`)
  return lines.join('\n') + '\n---\n\n' + banner(source) + '\n\n' + normalize(role.instructions)
}

// --check は読み取りのみ。--write も未知の互換ファイルを削除せず、所有者に判断を返す。
export function syncHarness(root, { write = false } = {}) {
  root = path.resolve(root)
  assertNoLinks(root, path.join(root, 'AGENTS.md'))
  const expected = new Map([['CLAUDE.md', Buffer.from(renderClaude(readFileSync(path.join(root, 'AGENTS.md'), 'utf8'))) ]])
  for (const name of sharedRoles) {
    const source = path.join(root, 'harness/roles', `${name}.json`)
    assertNoLinks(root, source)
    const role = JSON.parse(readFileSync(source, 'utf8'))
    if (role.name !== name) throw new Error(`role name が不一致です: ${name}`)
    expected.set(`.codex/agents/${name}.toml`, Buffer.from(renderRole(role, 'codex')))
    expected.set(`.claude/agents/${name}.md`, Buffer.from(renderRole(role, 'claude')))
  }
  for (const skill of sharedSkills) {
    const sourceRoot = path.join(root, '.agents/skills', skill)
    assertNoLinks(root, sourceRoot)
    if (!existsSync(path.join(sourceRoot, 'SKILL.md'))) throw new Error(`正本スキルがありません: ${skill}`)
    for (const file of filesIn(sourceRoot)) {
      const suffix = path.relative(sourceRoot, file).replaceAll('\\', '/')
      const source = `.agents/skills/${skill}/${suffix}`
      const destination = `.claude/skills/${skill}/${suffix}`
      const content = suffix === 'SKILL.md' ? Buffer.from(renderSkill(source, readFileSync(file, 'utf8'))) : readFileSync(file)
      expected.set(destination, content)
    }
  }
  assertNoLinks(root, path.join(root, '.claude/skills'))
  const unexpected = filesIn(path.join(root, '.claude/skills')).map(file => path.relative(root, file).replaceAll('\\', '/')).filter(file => !expected.has(file))
  // 全出力を先に検査する。存在しないリンク先を指す leaf も lstat で拒否する。
  for (const file of expected.keys()) assertNoLinks(root, path.join(root, file))
  const mismatches = []
  for (const [file, desired] of expected) {
    const destination = path.join(root, file)
    const current = existsSync(destination) ? readFileSync(destination) : undefined
    const same = current && (file.endsWith('.md') ? normalize(current.toString('utf8')) === normalize(desired.toString('utf8')) : current.equals(desired))
    if (same) continue
    mismatches.push(file)
    if (write && unexpected.length === 0) {
      mkdirSync(path.dirname(destination), { recursive: true })
      writeFileSync(destination, desired)
    }
  }
  return { mismatches, unexpected, written: write && unexpected.length === 0 ? mismatches : [] }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2)
    if (args.length > 1 || (args[0] && !['--check', '--write'].includes(args[0]))) throw new Error('Usage: node scripts/sync-harness.mjs [--check|--write]')
    const write = args[0] === '--write'
    const result = syncHarness(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), { write })
    for (const file of result.unexpected) console.error(`未管理の互換ファイルです。所有者と正本を確認してください: ${file}`)
    for (const file of result.mismatches) console[write && !result.unexpected.length ? 'log' : 'error'](`${write && !result.unexpected.length ? '更新' : '同期が必要'}: ${file}`)
    if (result.unexpected.length || (!write && result.mismatches.length)) process.exitCode = 1
    else console.log(`harness sync: ${write ? 'written' : 'verified'}`)
  } catch (error) {
    console.error(error.message)
    process.exitCode = 1
  }
}
