import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {CASE_EVIDENCE_STAGES} from '../../lib/case-evidence-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['case-study-customer-support-agent',['support-scope-gates','support-rollout-return']],['case-study-data-analysis-agent',['analysis-error-context','analysis-validation-return']],['case-study-email-assistant-incident',['mail-capability-path','mail-containment-return']]]
checkReadingArticles({name:'Case evidence',chapter:'case-studies',articles,stages:CASE_EVIDENCE_STAGES,sceneSelector:'svg[data-case-evidence-diagram]'})
const plans=[
 [0,'support-scope-gates','本番の関門','本番化で不足する関門',['identity','retrieval','capacity','data','none'],'本番化reviewの検討候補','未確認の関門へ戻る','四条件は実認証・配信の証明ではない'],
 [1,'analysis-validation-return','判断を保留','分析reviewで不足する条件',['known','independent','shown','assumptions','regression','none'],'分析reviewの検討候補','不足する条件へ戻る','図は実queryを検証しない'],
 [2,'mail-containment-return','限定で再開','限定再開で不足する条件',['image','egress','sessions','verified','history','none'],'限定再開の検討候補','遮断条件へ戻る','既送信は取り消せない']
]
async function open(page,index,id,stage){await page.goto(`${base}/docs/case-studies/${articles[index][0]}`);const r=page.locator(`[data-diagram-id="${id}"]`);await r.getByRole('button',{name:stage,exact:true}).click();await expect(r).toHaveAttribute('data-current-stage',String(CASE_EVIDENCE_STAGES[id].findIndex(x=>x.label===stage)));return r}
for(const [index,id,stage,label,values,yes,no,boundary] of plans)test(`${id}: every missing gate blocks promotion while retaining its explicit boundary`,async({page})=>{const r=await open(page,index,id,stage),svg=r.locator('svg[data-case-evidence-diagram]');for(const v of values){await r.getByRole('combobox',{name:label,exact:true}).selectOption(v);await expect(svg).toContainText(v===values.at(-1)?yes:no);await expect(svg).toContainText(boundary)}})
test('shadow changes draft visibility and canary does not erase human send judgment or scope',async({page})=>{const r=await open(page,0,'support-rollout-return','shadowの比較'),svg=r.locator('svg[data-case-evidence-diagram]');for(const v of ['shadow','canary','expanded']){await r.getByRole('combobox',{name:'下書きの段階導入',exact:true}).selectOption(v);await expect(svg).toContainText(v==='shadow'?'担当者へ提示しない':'限定して提示する');await expect(svg).toContainText('送信判断は人');await expect(svg).toContainText('全問い合わせへ広げない')}})
test('three original addition stages reveal accumulating connections and never claim an incomplete stage safe',async({page})=>{const r=await open(page,2,'mail-capability-path','送信能力を追加'),svg=r.locator('svg[data-case-evidence-diagram]');for(const v of ['0','1','2']){await r.getByRole('combobox',{name:'原文の機能追加の段階',exact:true}).selectOption(v);await expect(svg).toContainText(v==='2'?'三重奏が同じ処理へ揃う':'この三要素はまだ揃っていない');await expect(svg).toContainText(Number(v)>=1?'横断検索が追加済み':'横断検索はまだない');await expect(svg).toContainText('未成立を全安全にしない')}})
test('proxy retains upstream sensitive URL path while a blocked fetch sends no illustration request',async({page})=>{const r=await open(page,2,'mail-capability-path','表示から送信へ'),svg=r.locator('svg[data-case-evidence-diagram]');for(const v of ['direct','proxy','blocked']){await r.getByRole('combobox',{name:'応答表示の外部取得経路',exact:true}).selectOption(v);await expect(svg).toContainText(v==='blocked'?'模式の取得経路を遮断':'URLのdataが上流へ');await expect(svg).toContainText('proxyはdataを隠さない');await expect(svg).toContainText('図はrequestを送らない')}})
test('analysis three errors have separate visible positions and independent meaning is stated on the next figure',async({page})=>{const r=await open(page,1,'analysis-error-context','静かな三誤り');const rows=await r.locator('svg[data-case-evidence-diagram] .lf-box').evaluateAll(boxes=>boxes.map(x=>x.querySelector('text').getBBox().y));expect(rows).toHaveLength(3);expect(rows[1]).toBeGreaterThan(rows[0]+40);expect(rows[2]).toBeGreaterThan(rows[1]+40);const next=page.locator('[data-diagram-id="analysis-validation-return"]');await next.getByRole('button',{name:'二つの照合',exact:true}).click();await expect(next.locator('svg[data-case-evidence-diagram]')).toContainText('SQLの表現変更だけでない')})
test('fictional notices original tables attack example Mermaid and dates remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route] of articles){await p.goto(`${base}/docs/case-studies/${route}`);await expect(p.locator('article')).toContainText('架空の事例');await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual play stops and print retains all original prose instead of controls',async({page})=>{await page.setViewportSize({width:1280,height:720});const r=await open(page,2,'mail-containment-return','限定で再開');const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(r.locator('svg[data-case-evidence-diagram]')).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('既存の履歴');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
