import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {CASE_DECISIONS_STAGES} from '../../lib/case-decisions-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['case-study-expense-agent',['expense-migration-evidence','expense-write-regression']],['case-study-failed-poc',['pilot-criteria-value','pilot-withdrawal-assets']],['case-study-it-helpdesk-agent',['helpdesk-action-boundary','helpdesk-authority-trace']]]
checkReadingArticles({name:'Case decisions',chapter:'case-studies',articles,stages:CASE_DECISIONS_STAGES,sceneSelector:'svg[data-case-decisions-diagram]'})
async function open(page,index,id,stage){await page.goto(`${base}/docs/case-studies/${articles[index][0]}`);const r=page.locator(`[data-diagram-id="${id}"]`);await r.getByRole('button',{name:stage,exact:true}).click();await expect(r).toHaveAttribute('data-current-stage',String(CASE_DECISIONS_STAGES[id].findIndex(x=>x.label===stage)));return r}
for(const [index,id,stage,label,values,yes,no,boundary] of [
 [0,'expense-migration-evidence','移行の証拠','Agent移行で不足する根拠',['fixed','evidence','regression','none'],'Agentの検討候補','今の要件と根拠へ戻る','図は採用を決めない'],
 [0,'expense-write-regression','本人と承認','申請提出で不足する条件',['approved','scope','target','tool','none'],'提出reviewの検討候補','許可条件へ戻る','図は申請を提出しない'],
 [2,'helpdesk-authority-trace','誰が何をしたか','操作記録で不足する項目',['input','decision','tool','approval','outcome','actor','none'],'記録reviewの検討候補','不足する記録へ戻る','実行済みの証明は別']
])test(`${id}: each missing condition prevents unsupported promotion`,async({page})=>{const r=await open(page,index,id,stage),svg=r.locator('svg[data-case-decisions-diagram]');for(const v of values){await r.getByRole('combobox',{name:label,exact:true}).selectOption(v);await expect(svg).toContainText(v===values.at(-1)?yes:no);await expect(svg).toContainText(boundary)}})
test('fictional threshold relaxation changes displayed attainment but preserves original criterion and residual human cost',async({page})=>{const r=await open(page,1,'pilot-criteria-value','基準のすり替え'),svg=r.locator('svg[data-case-decisions-diagram]');for(const v of ['95','80']){await r.getByRole('combobox',{name:'原文の架空の成功基準',exact:true}).selectOption(v);await expect(svg).toContainText(v==='80'?'変更した表示基準は達成':'表示基準に未達');await expect(svg).toContainText('着手時95%は未達');await expect(svg).toContainText('人手と運用費が残る')}})
test('changing past cost cannot override any insufficient future condition or choose actual withdrawal',async({page})=>{const r=await open(page,1,'pilot-withdrawal-assets','これからの価値'),svg=r.locator('svg[data-case-decisions-diagram]');for(const f of ['negative','unsolved','all'])for(const past of ['0','100','10000']){await r.getByRole('combobox',{name:'将来の品質と価値の模式条件',exact:true}).selectOption(f);await r.getByRole('combobox',{name:'判断から除く過去費用の模式入力',exact:true}).selectOption(past);await expect(svg).toContainText(f==='all'?'続行reviewの検討候補':'将来の基準と見込みへ');await expect(svg).toContainText('過去費用は判定に使わない');await expect(svg).toContainText('図は実採否を決めない')}})
test('reset software and new rights preserve distinct original conditions and common enforcement attribution',async({page})=>{const r=await open(page,2,'helpdesk-action-boundary','操作別の条件'),svg=r.locator('svg[data-case-decisions-diagram]');for(const action of ['reset','software','rights'])for(const missing of ['identity','allowlist','approval','tool','actor','none']){await r.getByRole('combobox',{name:'原文の操作の種類',exact:true}).selectOption(action);await r.getByRole('combobox',{name:'操作reviewで不足する確認',exact:true}).selectOption(missing);const common=['tool','actor'].includes(missing),blocked=common||(action==='reset'?['identity','approval'].includes(missing):action==='software'?missing==='allowlist':missing==='approval');await expect(svg).toContainText(blocked?'操作条件へ戻る':'操作reviewの検討候補');await expect(svg).toContainText(action==='software'?'許可リスト内に限定':'人の承認が必要');await expect(svg).toContainText('図は操作を実行しない')}})
test('fictional notices original risk and criterion numbers and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route] of articles){await p.goto(`${base}/docs/case-studies/${route}`);await expect(p.locator('article')).toContainText('架空の事例');await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual stop and print retain prose and fictional disclaimers',async({page})=>{await page.setViewportSize({width:1280,height:720});const r=await open(page,0,'expense-write-regression','本人と承認');const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(r.locator('svg[data-case-decisions-diagram]')).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('架空の事例');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
