import {test,expect} from '@playwright/test'
import {DATA_RESILIENCE_STAGES} from '../../lib/data-resilience-model.mjs'
import {checkReadingArticles} from './reading-article-checks.mjs'
checkReadingArticles({name:'Data resilience',chapter:'operations',stages:DATA_RESILIENCE_STAGES,sceneSelector:'svg[data-data-resilience-diagram]',articles:[['conversation-data-management',['conversation-collection-layers','conversation-retention-deletion','conversation-use-access']],['data-governance-for-ai',['governance-ownership-catalogue','governance-quality-permission']],['chaos-engineering-for-ai',['chaos-hypothesis-targets','chaos-environment-learning']]]})
const base=process.env.NEXT_PUBLIC_BASE_PATH||'',svg=root=>root.locator('svg[data-data-resilience-diagram]')
async function open(page,route,id,label){await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('training permission stays separate from operation purpose and all shared collection controls remain required',async({page})=>{
 const root=await open(page,'conversation-data-management','conversation-collection-layers','目的と最小化');for(const purpose of ['operation','training'])for(const missing of ['trace','notice','minimum','retention','access','training','none']){await root.getByRole('combobox',{name:'模式の収集目的',exact:true}).selectOption(purpose);await root.getByRole('combobox',{name:'収集設計で不足する条件',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'||purpose==='operation'&&missing==='training'?'収集設計の検討候補':'不足する条件へ戻る')}
})
test('each derivative store remains in deletion scope and all checked never means actually deleted',async({page})=>{
 const root=await open(page,'conversation-data-management','conversation-retention-deletion','派生物まで');for(const missing of ['raw','pseudonym','embedding','cache','evaluation','memory','none']){await root.getByRole('combobox',{name:'削除設計で未点検の保存先',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'?'全保存先の設計を照合':'未点検の保存先が残る');await expect(svg(root)).toContainText('模式条件は実削除の証拠ではない')}
})
test('masked internal access still needs purpose role and audit while raw and external add conditions',async({page})=>{
 const root=await open(page,'conversation-data-management','conversation-use-access','役割と監査');for(const form of ['masked','raw'])for(const destination of ['internal','external'])for(const missing of ['purpose','role','audit','exception','destination','none']){await root.getByRole('combobox',{name:'閲覧する模式の加工状態',exact:true}).selectOption(form);await root.getByRole('combobox',{name:'模式の分析先',exact:true}).selectOption(destination);await root.getByRole('combobox',{name:'利用設計で不足する条件',exact:true}).selectOption(missing);const allowed=missing==='none'||form==='masked'&&missing==='exception'||destination==='internal'&&missing==='destination';await expect(svg(root)).toContainText(allowed?'利用設計の検討候補':'不足する条件へ戻る');await expect(svg(root)).toContainText('図はアクセスを許可しない')}
})
test('owner update catalogue and periodic quality each remain required without correcting source data',async({page})=>{
 const root=await open(page,'data-governance-for-ai','governance-ownership-catalogue','土台を先に');for(const missing of ['owner','duty','catalogue','quality','none']){await root.getByRole('combobox',{name:'知識源管理で不足する土台',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'?'管理設計の検討候補':'不足する土台へ戻る');await expect(svg(root)).toContainText('図は原本を修正しない')}
})
test('empty quality denominator is not zero and ratios use the selected bounded source count',async({page})=>{
 const root=await open(page,'data-governance-for-ai','governance-quality-permission','測れる基準');for(const [n,expected] of [['0',['母数なし','母数なし','母数なし']],['10',['20%','10%','20%']],['20',['10%','5%','10%']]]){await root.getByRole('combobox',{name:'品質比率の模式母数',exact:true}).selectOption(n);expect(await svg(root).locator('.lf-box').allTextContents()).toEqual(expected.map((value,i)=>`${['鮮度','正確性','一意性'][i]}${value}${['期限超過の割合','誤りの割合','重複の割合'][i]}`))}
})
test('each selected use reads its own tag and unknown stays held even when the other purpose is allowed',async({page})=>{
 const root=await open(page,'data-governance-for-ai','governance-quality-permission','未分類は保留');for(const purpose of ['search','training'])for(const search of ['allow','deny','unknown'])for(const training of ['allow','deny','unknown']){await root.getByRole('combobox',{name:'検索の利用分類',exact:true}).selectOption(search);await root.getByRole('combobox',{name:'学習の利用分類',exact:true}).selectOption(training);await root.getByRole('combobox',{name:'確認する模式用途',exact:true}).selectOption(purpose);const chosen=purpose==='search'?search:training;await expect(svg(root)).toContainText(chosen==='unknown'?'未分類なので保留':chosen==='allow'?'タグ上は検討候補':'その用途には載せない');await expect(svg(root)).toContainText('図は取り込まない')}
})
test('hypothesis plan controls remain required and observing activation alone is not success',async({page})=>{
 const root=await open(page,'chaos-engineering-for-ai','chaos-hypothesis-targets','基準を先に');for(const missing of ['hypothesis','steady','criteria','scope','none']){await root.getByRole('combobox',{name:'注入前に不足する準備',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'?'計画の検討候補':'不足する準備へ戻る')}
 await root.getByRole('button',{name:'弱点を見つける',exact:true}).click();for(const value of ['unobserved','no-fallback','only-fallback','both']){await root.getByRole('combobox',{name:'模式の演習観測',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='unobserved'?'未観測なので成否は未定':value==='both'?'模式条件で仮説を支持':'模式条件で弱点を発見')}
})
test('production needs irreproducible dependency as well as small scope and no effects and never performs injection',async({page})=>{
 const root=await open(page,'chaos-engineering-for-ai','chaos-environment-learning','本番の限定');for(const environment of ['evaluation','staging','production'])for(const missing of ['dependency','scope','effects','none']){await root.getByRole('combobox',{name:'模式の演習環境',exact:true}).selectOption(environment);await root.getByRole('combobox',{name:'演習環境で不足する条件',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'||environment!=='production'&&missing==='dependency'?'計画の検討候補':'不足する条件へ戻る');await expect(svg(root)).toContainText('図は実注入しない')}
})
test('source tables dates examples and TODO survive without JavaScript',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const page=await context.newPage();for(const [route,text] of [['conversation-data-management','誰が会話を読めるか'],['data-governance-for-ai','検索に載せてよいか'],['chaos-engineering-for-ai','ゲームデー']]){await page.goto(`${base}/docs/operations/${route}`);await expect(page.locator('article')).toContainText(text);await expect(page.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await context.close()}
})
test('low PC playback pause and print retain the original retention and deletion source',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/conversation-data-management`);const root=page.locator('[data-diagram-id="conversation-retention-deletion"]');await root.getByRole('button',{name:'二つの削除',exact:true}).click();const play=root.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const observer=new IntersectionObserver(entries=>{if(!entries.at(-1)?.isIntersecting)return;observer.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});observer.observe(el.closest('.aw-sticky'))}));await play.click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(root)).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('ユーザー・テナント');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
