import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {DEPLOYMENT_LIFECYCLE_STAGES} from '../../lib/deployment-lifecycle-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['deployment-and-scaling',['deployment-state-execution','deployment-capacity-fallback']],['long-running-agents',['resident-maintenance-signals','resident-succession-retirement']],['mlops-and-llmops',['mlops-common-differences','mlops-roles-training-join']]]
checkReadingArticles({name:'Deployment lifecycle',chapter:'operations',articles,stages:DEPLOYMENT_LIFECYCLE_STAGES,sceneSelector:'svg[data-deployment-lifecycle-diagram]'})
const svg=root=>root.locator('svg[data-deployment-lifecycle-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('route uses tail against synchronous boundary rather than an average completion promise',async({page})=>{const root=await open(page,'deployment-and-scaling','deployment-state-execution','tailで選ぶ');for(const value of ['3','5','8']){await root.getByRole('combobox',{name:'模式のtail時間',exact:true}).selectOption(value);await expect(svg(root)).toContainText(Number(value)>5?'進捗付きjobを検討':'同期経路を検討');await expect(svg(root)).toContainText('模式条件は実測でない')}})
test('unknown side effect requires reconciliation unless actual receiver or atomic contract exists',async({page})=>{const root=await open(page,'deployment-and-scaling','deployment-state-execution','副作用の契約');for(const value of ['none','receiver','atomic']){await root.getByRole('combobox',{name:'結果不明時の回復契約',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'自動再送を止め照合':'回復契約を検討');await expect(svg(root)).toContainText('図は再送しない')}})
test('loop tokens can exhaust TPM even when request count fits RPM',async({page})=>{const root=await open(page,'deployment-and-scaling','deployment-capacity-fallback','待ち行列');for(const value of ['1','2','3']){await root.getByRole('combobox',{name:'模式のloop上限',exact:true}).selectOption(value);await expect(svg(root)).toContainText(`呼出し ${3*Number(value)} ／ RPM枠 10`);await expect(svg(root)).toContainText(`token ${12*Number(value)} ／ TPM枠 30`);await expect(svg(root)).toContainText(value==='3'?'超える枠から調整':'両方の枠を照合')}})
test('fallback requires all three conditions and all providers down stops or queues',async({page})=>{const root=await open(page,'deployment-and-scaling','deployment-capacity-fallback','切替の条件');for(const value of ['quality','switch','return','down','none']){await root.getByRole('combobox',{name:'切替で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='down'?'受付停止か後続queue':value==='none'?'fallbackの検討候補':'不足する条件を評価');await expect(svg(root)).toContainText('図は実切替しない')}})
test('shadow consumes both old and new demand including the exact capacity boundary',async({page})=>{const root=await open(page,'deployment-and-scaling','deployment-capacity-fallback','小さく展開');for(const value of ['2','3','4']){await root.getByRole('combobox',{name:'模式のshadow追加需要',exact:true}).selectOption(value);await expect(svg(root)).toContainText(`需要 ${7+Number(value)}`);await expect(svg(root)).toContainText(value==='4'?'両経路で枠を超える':'追加容量を照合')}})
test('succession requires side effect disabled shadow exclusive right records and business key',async({page})=>{const root=await open(page,'long-running-agents','resident-succession-retirement','一つの実行権');for(const value of ['effects','right','records','key','none']){await root.getByRole('combobox',{name:'交代設計で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'交代設計の検討候補':'不足する条件へ戻る');await expect(svg(root)).toContainText('図は実切替しない')}})
test('retirement is not stop alone and cannot prove every stored copy deleted',async({page})=>{const root=await open(page,'long-running-agents','resident-succession-retirement','退役を決める');for(const value of ['disabled','access','state','none']){await root.getByRole('combobox',{name:'退役設計で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'退役設計の検討候補':'終了処理を点検');await expect(svg(root)).toContainText('停止は全削除の証拠でない')}})
test('borrowed path does not require training and planned training needs each responsibility',async({page})=>{const root=await open(page,'mlops-and-llmops','mlops-roles-training-join','学習の合流');for(const value of ['data','job','version','evaluation','none','borrowed']){await root.getByRole('combobox',{name:'学習連携で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='borrowed'?'借りるアプリの経路':value==='none'?'学習連携の検討候補':'不足する責任を決める');await expect(svg(root)).toContainText('図は学習を実行しない')}})
test('original tables Mermaid anti patterns and references survive without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['deployment-and-scaling','p95'],['long-running-agents','排他的'],['mlops-and-llmops','特徴量']]){await p.goto(`${base}/docs/operations/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC pause and print preserve the original shared operations requirements',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/deployment-and-scaling`);const root=page.locator('[data-diagram-id="deployment-capacity-fallback"]');await root.getByRole('button',{name:'切替の条件',exact:true}).click();const play=root.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(root)).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('アンチパターン');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
