import {test,expect} from '@playwright/test'
import {GATEWAY_REUSE_STAGES} from '../../lib/gateway-reuse-model.mjs'
import {checkReadingArticles} from './reading-article-checks.mjs'
checkReadingArticles({name:'Gateway reuse',chapter:'operations',stages:GATEWAY_REUSE_STAGES,sceneSelector:'svg[data-gateway-reuse-diagram]',articles:[['llm-gateway',['gateway-crossroads-topology','gateway-routing-boundaries']],['semantic-caching',['cache-levels-semantic-risk','cache-reuse-invalidation']],['batch-processing',['batch-route-capacity','batch-results-deadlines']]]})
const base=process.env.NEXT_PUBLIC_BASE_PATH||'',svg=root=>root.locator('svg[data-gateway-reuse-diagram]')
async function open(page,route,id,label){await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('tenant scope quota budget and audit remain required and provider redundancy alone leaves a common single point',async({page})=>{const root=await open(page,'llm-gateway','gateway-routing-boundaries','テナント境界');for(const missing of ['tenant','scope','quota','budget','audit','none']){await root.getByRole('combobox',{name:'共通層の制御で不足する条件',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'?'制御設計の検討候補':'不足する制御へ戻る')}await root.getByRole('button',{name:'共通の故障',exact:true}).click();for(const value of ['none','provider','gateway','both']){await root.getByRole('combobox',{name:'模式の冗長化対象',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'||value==='provider'?'共通層は単一障害点':'入口の冗長設計を点検')}})
test('normalization preserves direction and negation instead of merging equal words',async({page})=>{const root=await open(page,'semantic-caching','cache-levels-semantic-risk','意味を守る');for(const value of ['direction','negation']){await root.getByRole('combobox',{name:'原文で区別する意味の差',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='direction'?'支払う側が逆':'確認する内容が異なる');await expect(svg(root)).toContainText('同じ単語だけで一致させない')}})
test('each of the three shared target conditions remains required',async({page})=>{const root=await open(page,'semantic-caching','cache-reuse-invalidation','三軸の条件');for(const value of ['determinism','personal','freshness','none']){await root.getByRole('combobox',{name:'共有対象で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'共有対象の検討候補':'共有対象から外す')}})
test('each change event invalidates independently and expiry cannot replace current versions',async({page})=>{const root=await open(page,'semantic-caching','cache-reuse-invalidation','更新と期限');for(const value of ['knowledge','prompt','model','ttl','none']){await root.getByRole('combobox',{name:'模式の無効化イベント',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'ほかの利用条件も点検':'無効化の設計候補');await expect(svg(root)).toContainText('期限内でも古い版なら使い回さない')}})
test('match alone cannot bypass tenant scope context version expiry or target even for exact inputs',async({page})=>{const root=await open(page,'semantic-caching','cache-reuse-invalidation','境界をキーへ');for(const value of ['match','tenant','scope','context','version','expiry','target','none']){await root.getByRole('combobox',{name:'応答再利用で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'再利用設計の検討候補':'不足する境界へ戻る');await expect(svg(root)).toContainText('図は応答を返さない')}})
test('batch candidate cannot accept instant or small or urgent uses',async({page})=>{const root=await open(page,'batch-processing','batch-route-capacity','締切で選ぶ');for(const value of ['small','deadline','immediate','none']){await root.getByRole('combobox',{name:'バッチ対象で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'batchの検討候補':'即時経路も検討する');await expect(svg(root)).toContainText('条件だけで納期保証しない')}})
test('unknown input outcome requires reconciliation and never gains call or billing deduplication from custom_id',async({page})=>{const root=await open(page,'batch-processing','batch-results-deadlines','不明と再投入');for(const value of ['succeeded','failed','expired','unknown']){await root.getByRole('combobox',{name:'再投入を読む模式の項目状態',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='succeeded'?'成功結果を保持する':value==='unknown'?'既存jobを照合する':'対象項目の再投入を検討');await expect(svg(root)).toContainText('呼出し・課金の排除は別')}})
test('retry and recovery count towards deadline and existing realtime route still needs capacity review',async({page})=>{const root=await open(page,'batch-processing','batch-results-deadlines','費用と納期');for(const n of ['5','8','10'])for(const value of ['unknown','available']){await root.getByRole('combobox',{name:'締切までの模式時間',exact:true}).selectOption(n);await root.getByRole('combobox',{name:'即時経路の模式状態',exact:true}).selectOption(value);await expect(svg(root)).toContainText(`必要な猶予 8 ／ 締切まで ${n} ／ 余裕 ${Number(n)-8}`);await expect(svg(root)).toContainText(Number(n)>=8?'batch計画の検討候補':value==='available'?'即時経路の容量を別に確認':'締切と実行計画を見直す')}})
test('original tables examples current boundaries and TODO survive without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['llm-gateway','AI Proxy 無印'],['semantic-caching','A pays B'],['batch-processing','custom_id']]){await p.goto(`${base}/docs/operations/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC pause and print retain the original job control requirements',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/batch-processing`);const root=page.locator('[data-diagram-id="batch-results-deadlines"]');await root.getByRole('button',{name:'同じ処理',exact:true}).click();const play=root.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(root)).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('入力の版と業務操作');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
