import { test, expect } from '@playwright/test'

const path = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/docs/concepts/tool-use`

for (const width of [375, 1440]) {
  test(`glossary hover/focus dismissal, tooltip crossing and link: ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 960 })
    await page.goto(path)
    const term = page.locator('article .glossary-term').first()
    const tooltip = term.getByRole('tooltip', { includeHidden: true })
    await term.scrollIntoViewIfNeeded()
    await term.hover()
    await expect(tooltip).toBeVisible()
    expect(await term.getAttribute('aria-describedby')).toBe(await tooltip.getAttribute('id'))
    await expect(term).toHaveAccessibleDescription(await tooltip.innerText())
    await page.keyboard.press('Escape')
    await expect(tooltip).toBeHidden()
    await page.mouse.move(0, 0)
    await term.hover()
    await expect(tooltip).toBeVisible()
    const bounds = await tooltip.boundingBox()
    expect(bounds.x).toBeGreaterThanOrEqual(7)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(width - 7)
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2, { steps: 15 })
    await expect(tooltip).toBeVisible()
    await page.mouse.move(0, 0)
    await expect(tooltip).toBeHidden()
    await page.keyboard.press('Tab')
    await term.focus()
    await expect(tooltip).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(tooltip).toBeHidden()
    await expect(term).toBeFocused()
    await page.keyboard.press('Tab')
    await term.focus()
    await expect(tooltip).toBeVisible()
    await page.locator('article').evaluate(element => { element.style.zoom = '2' })
    await term.scrollIntoViewIfNeeded()
    await term.blur()
    await term.focus()
    await expect(tooltip).toBeVisible()
    const zoomBounds = await tooltip.boundingBox()
    expect(zoomBounds.x).toBeGreaterThanOrEqual(7)
    expect(zoomBounds.x + zoomBounds.width).toBeLessThanOrEqual(width - 7)
    await page.setViewportSize({ width: width === 375 ? 320 : 640, height: 700 })
    await expect(tooltip).toBeVisible()
    await expect.poll(async () => {
      const bounds = await tooltip.boundingBox()
      return bounds.x >= 7 && bounds.x + bounds.width <= page.viewportSize().width - 7
    }).toBe(true)
    const href = await term.getAttribute('href')
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL(new RegExp(href.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(?:\\.html)?(?:#.*)?$'))
  })
}
