import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {GOVERNANCE_SAFETY_STAGES} from '../../lib/governance-safety-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['compliance-and-governance',['compliance-regulatory-map','compliance-data-governance','compliance-audit-vendor']],['ai-standards-and-certification',['standards-types-stage','standards-fit-maintain']],['frontier-safety-overview',['frontier-framework-report','frontier-procurement-observation']]]
checkReadingArticles({name:'Governance safety',chapter:'security',articles,stages:GOVERNANCE_SAFETY_STAGES,sceneSelector:'svg[data-governance-safety-diagram]'})
const plans=[
 ['compliance-and-governance','compliance-regulatory-map','法域と役割','規制の整理で不足する根拠',['region','use','role','source','none'],'法務の検討へ','不足する根拠へ戻る','図は法的適合を判定しない'],
 ['compliance-and-governance','compliance-regulatory-map','日本の段階','模式の法の段階',['discussion','enacted','promulgated','in-force'],'模式入力は施行段階','施行したとは読めない','議論や意見募集の資料を'],
 ['compliance-and-governance','compliance-data-governance','保持と削除の範囲','削除範囲で未確認の保存先',['logs','memory','evaluation','derived','none'],'全保存先の検討候補','未確認の保存先へ戻る','図は削除しない'],
 ['compliance-and-governance','compliance-audit-vendor','契約時に確認','契約reviewで未確認の構成',['region','account','billing','endpoint','none'],'契約reviewの候補','未確認の構成へ戻る','図は契約解釈をしない'],
 ['ai-standards-and-certification','standards-types-stage','認証できるもの','標準の道具の種類',['guidance','framework','certifier','soft-law','requirements'],'認証対象の検討候補','組織の取得認証にしない','図は認証を発行しない'],
 ['ai-standards-and-certification','standards-types-stage','三つの段階','適合推定reviewで未確認の条件',['published','commission','oj','version','clauses','none'],'適合推定の検討候補','未確認の段階・対象へ戻る','現在の法的効果を確定しない'],
 ['ai-standards-and-certification','standards-fit-maintain','認定と認証','認定認証の未確認の主体',['accreditor','certifier','organization','none'],'三主体の検討候補','未確認の主体・scopeへ戻る','異なる行為・日付'],
 ['ai-standards-and-certification','standards-fit-maintain','統合とgap分析','管理systemで不足する条件',['operations','requirements','gaps','records','sustain','none'],'審査準備の検討候補','不足する運用へ戻る','図は認証を発行しない'],
 ['frontier-safety-overview','frontier-framework-report','文書と日付','reportで一致していない対象',['model','version','none'],'対象modelと版の検討候補','採用modelと版を照合する','対象日を延長しない'],
 ['frontier-safety-overview','frontier-procurement-observation','四つの選定軸','frontier選定で不足する根拠',['framework','card','coverage','updates','thirdparty','none'],'選定reviewの検討候補','不足する記録と範囲へ戻る','自社アプリを安全・採用済みにしない']
]
for(const [route,id,stage,label,values,yes,no,boundary] of plans)test(`${id}: ${label} changes only its stated review scope`,async({page})=>{await page.goto(`${base}/docs/security/${route}`);const r=page.locator(`[data-diagram-id="${id}"]`);await r.getByRole('button',{name:stage,exact:true}).click();const svg=r.locator('svg[data-governance-safety-diagram]');for(const v of values){await r.getByRole('combobox',{name:label,exact:true}).selectOption(v);await expect(svg).toContainText(v===values.at(-1)?yes:no);await expect(svg).toContainText(boundary)}})
test('report flow labels occupy four separate rows rather than the same text position',async({page})=>{await page.goto(`${base}/docs/security/frontier-safety-overview`);const r=page.locator('[data-diagram-id="frontier-framework-report"]');await r.getByRole('button',{name:'四段の構造',exact:true}).click();await expect(r).toHaveAttribute('data-current-stage','2');const boxes=await r.locator('svg[data-governance-safety-diagram] .lf-box').all();expect(boxes).toHaveLength(4);let last;for(const box of boxes){const b=await box.locator('text').first().boundingBox();expect(b).not.toBeNull();if(last)expect(b.y).toBeGreaterThan(last.y+last.height);last=b}})
test('original dates law snapshots standards table code and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route] of articles){await p.goto(`${base}/docs/security/${route}`);await expect(p.locator('article')).toContainText('2026-09-10');await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC print retains source snapshots and manual play can stop',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/security/compliance-and-governance`);const r=page.locator('[data-diagram-id="compliance-regulatory-map"]');await r.getByRole('button',{name:'日本の段階',exact:true}).click();const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(r.locator('svg[data-governance-safety-diagram]')).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('2026-09-10');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
