import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {HARDWARE_SERVING_STAGES} from '../../lib/hardware-serving-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['gpu-and-hardware-basics',['hardware-weights-runtime','hardware-bottleneck-purchase']],['self-hosted-inference',['serving-engines-throughput','serving-memory-rollout']],['green-ai',['environment-scope-mechanisms','environment-measure-report','environment-honest-claims']]]
checkReadingArticles({name:'Hardware serving',chapter:'operations',articles,stages:HARDWARE_SERVING_STAGES,sceneSelector:'svg[data-hardware-serving-diagram]'})
const svg=root=>root.locator('svg[data-hardware-serving-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('7B weights use original precision arithmetic and do not hide runtime memory',async({page})=>{const root=await open(page,'gpu-and-hardware-basics','hardware-weights-runtime','重みの容量');for(const [value,n] of [['fp16',14],['int8',7],['int4',3.5]]){await root.getByRole('combobox',{name:'7B重みの数値精度',exact:true}).selectOption(value);await expect(svg(root)).toContainText(`重み ${n} GB`);await expect(svg(root)).toContainText('十進GBの概算');await expect(svg(root)).toContainText('KV cache')}})
test('precision cannot skip own quality peak or runtime and never actually adopts',async({page})=>{const root=await open(page,'gpu-and-hardware-basics','hardware-weights-runtime','品質の条件');for(const value of ['quality','peak','runtime','none']){await root.getByRole('combobox',{name:'量子化で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'量子化の検討候補':'不足する条件へ戻る');await expect(svg(root)).toContainText('図は採用しない')}})
test('low toy utilization retains fixed ownership cost at the exact break even boundary',async({page})=>{const root=await open(page,'self-hosted-inference','serving-engines-throughput','借りると持つ');for(const n of ['20','60','100','200']){await root.getByRole('combobox',{name:'比較する模式の処理件数',exact:true}).selectOption(n);await expect(svg(root)).toContainText(`${120+Number(n)} 単位`);await expect(svg(root)).toContainText(Number(n)>60?'自ホスト費用の検討候補':n==='60'?'模式の費用が同じ':'API費用の検討候補')}})
test('continuous batching refills only the freed slot without changing the live request',async({page})=>{const root=await open(page,'self-hosted-inference','serving-engines-throughput','空き枠へ投入');for(const [value,a,b] of [['0','A','B'],['1','C','B'],['2','C','D']]){await root.getByRole('combobox',{name:'連続batchingの模式時点',exact:true}).selectOption(value);await expect(svg(root)).toContainText(`slot 1: ${a}`);await expect(svg(root)).toContainText(`slot 2: ${b}`)}})
test('long context and concurrent users jointly exhaust KV capacity with weight and workspace retained',async({page})=>{const root=await open(page,'self-hosted-inference','serving-memory-rollout','同時と文脈');for(const a of ['1','2','4'])for(const b of ['1','2','4']){await root.getByRole('combobox',{name:'KV模式の同時実行',exact:true}).selectOption(a);await root.getByRole('combobox',{name:'KV模式の文脈量',exact:true}).selectOption(b);await expect(svg(root)).toContainText(`重み14 ＋ KV ${Number(a)*Number(b)} ＋ 作業領域2 = ${16+Number(a)*Number(b)} 単位`);await expect(svg(root)).toContainText(Number(a)*Number(b)>8?'模式の24枠を超える':'模式の24枠を照合')}})
test('model distribution is incomplete without rollback quality cache and version',async({page})=>{const root=await open(page,'self-hosted-inference','serving-memory-rollout','変更を連動');for(const value of ['distribution','rollback','evaluation','cache','version','none']){await root.getByRole('combobox',{name:'model更新で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'更新設計の検討候補':'不足する条件へ戻る');await expect(svg(root)).toContainText('図は実更新しない')}})
test('low PUE cannot establish low carbon intensity and toy figures do not become real kg',async({page})=>{const root=await open(page,'green-ai','environment-scope-mechanisms','PUEの位置');for(const pue of ['1','1.5','2'])for(const intensity of ['1','3']){await root.getByRole('combobox',{name:'模式の施設PUE',exact:true}).selectOption(pue);await root.getByRole('combobox',{name:'模式の電源炭素強度',exact:true}).selectOption(intensity);await expect(svg(root)).toContainText(`${10*Number(pue)*Number(intensity)} 単位`);await expect(svg(root)).toContainText('scope3や実排出量は計算しない')}})
test('scope period method functional unit and method version all remain required for comparison',async({page})=>{const root=await open(page,'green-ai','environment-measure-report','開示の境界');for(const value of ['scope','period','method','unit','version','none']){await root.getByRole('combobox',{name:'開示比較で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'比較条件の検討候補':'境界を揃え直す');await expect(svg(root)).toContainText('図は比較を実施しない')}})
test('batch discount and off peak cannot become energy or carbon reduction percentages',async({page})=>{const root=await open(page,'green-ai','environment-scope-mechanisms','八つの施策');for(const [value,text] of [['batch','割引から削減率は推定不可'],['time','オフピーク≠低炭素'],['history','要約生成の計算も含める'],['response','誤hitと権限を制御']]){await root.getByRole('combobox',{name:'環境への作用を読む施策',exact:true}).selectOption(value);await expect(svg(root)).toContainText(text)}})
test('claim type highlights offset certificates goals or measured reduction without conflating them',async({page})=>{const root=await open(page,'green-ai','environment-honest-claims','年間と瞬間');for(const [value,index,text] of [['offset',1,'言葉を実削減へ変えない'],['annual',2,'24/7 CFEへ読み替えない'],['target',3,'現在の達成と区分する'],['reduction',0,'施策名だけで成果にしない']]){await root.getByRole('combobox',{name:'区分する環境の主張',exact:true}).selectOption(value);await expect(svg(root)).toContainText(text);await expect(svg(root).locator('[data-token-row] [data-selected="true"]')).toHaveAttribute('data-position',String(index))}})
test('original quantities tables provider dates and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['gpu-and-hardware-basics','3.5 GB'],['self-hosted-inference','2026-08'],['green-ai','2026-09-21']]){await p.goto(`${base}/docs/operations/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC pause and print preserve uncertainty legal boundary and original report text',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/green-ai`);const root=page.locator('[data-diagram-id="environment-measure-report"]');await root.getByRole('button',{name:'後継の観測',exact:true}).click();const play=root.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(root)).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('法務');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
