import {test,expect} from '@playwright/test'
import {QUALITY_TRACE_STAGES} from '../../lib/quality-trace-model.mjs'
import {checkReadingArticles} from './reading-article-checks.mjs'
checkReadingArticles({name:'Quality measurement',chapter:'evaluation',stages:QUALITY_TRACE_STAGES,sceneSelector:'svg[data-quality-trace-diagram]',articles:[['fairness-and-bias-evaluation',['fairness-types-measurement','fairness-japanese-remediation']],['japanese-quality-evaluation',['japanese-axes-exceptions','japanese-judge-division']]]})
checkReadingArticles({name:'Quality tracing',chapter:'operations',stages:QUALITY_TRACE_STAGES,sceneSelector:'svg[data-quality-trace-diagram]',articles:[['observability-and-tracing',['trace-hierarchy-versions','trace-signals-data-response']]]})
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
async function open(page,chapter,route,id,label){await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${base}/docs/${chapter}/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('bias types and counterfactual conditions distinguish output differences from legal conclusions',async({page})=>{
 const root=await open(page,'evaluation','fairness-and-bias-evaluation','fairness-types-measurement','類型を選ぶ');for(const value of ['quality','stereotype','refusal']){await root.getByRole('combobox',{name:'測定する偏りの類型',exact:true}).selectOption(value);await expect(root.locator('[data-fairness-bias-type]')).toHaveAttribute('data-fairness-bias-type',value)}
 await root.getByRole('button',{name:'対照ペア',exact:true}).click();for(const pair of ['attribute','request','other'])for(const different of ['yes','no']){await root.getByRole('combobox',{name:'対照ペアで変える条件',exact:true}).selectOption(pair);await root.getByRole('combobox',{name:'選択する模式の出力差',exact:true}).selectOption(different);const data=root.locator('[data-fairness-pair-ready]');await expect(data).toHaveAttribute('data-fairness-pair-ready',String(pair==='attribute'));await expect(data).toHaveAttribute('data-fairness-difference-review',String(pair==='attribute'&&different==='yes'));await expect(data).toHaveAttribute('data-fairness-legal-determined','false');await expect(data).toHaveAttribute('data-fairness-model-executed','false')}
})
test('strata keep the minority denominator and empty rates distinct from weighted overall rates',async({page})=>{
 const root=await open(page,'evaluation','fairness-and-bias-evaluation','fairness-types-measurement','層別で読む');await expect(root.locator('svg[data-quality-trace-diagram] tspan').filter({hasText:/^全体: 10\/12$/})).toHaveCount(1);for(const [value,overall,small] of [['hidden',String(10/12),'0.5'],['equal','0.5','0.5'],['empty','0.9','unavailable']]){await root.getByRole('combobox',{name:'公平性で読む模式の集計',exact:true}).selectOption(value);const data=root.locator('[data-fairness-overall-rate]');await expect(data).toHaveAttribute('data-fairness-overall-rate',overall);await expect(data).toHaveAttribute('data-fairness-small-rate',small);await expect(data).toHaveAttribute('data-fairness-guaranteed','false')}await expect(root.locator('svg[data-quality-trace-diagram]')).toContainText('母数なし')
})
test('fairness remediation cannot bypass measured limitations Japanese criteria or stakeholder agreement',async({page})=>{
 const root=await open(page,'evaluation','fairness-and-bias-evaluation','fairness-japanese-remediation','残りを測る');for(const value of ['limits','japanese','criteria','stakeholders','none']){await root.getByRole('combobox',{name:'公平性対策後に不足する条件',exact:true}).selectOption(value);const data=root.locator('[data-fairness-review-candidate]');await expect(data).toHaveAttribute('data-fairness-review-candidate',String(value==='none'));await expect(data).toHaveAttribute('data-fairness-guaranteed','false');await expect(data).toHaveAttribute('data-fairness-remediation-executed','false')}
})
test('Japanese quality axes preserve usage and quotation exceptions without grading phrases in isolation',async({page})=>{
 const root=await open(page,'evaluation','japanese-quality-evaluation','japanese-axes-exceptions','五つの軸');for(const value of ['honorific','style','notation','names','natural']){await root.getByRole('combobox',{name:'日本語で確認する品質軸',exact:true}).selectOption(value);await expect(root.locator('[data-japanese-quality-axis]')).toHaveAttribute('data-japanese-quality-axis',value)}await root.getByRole('button',{name:'例外を定める',exact:true}).click();for(const value of ['habit','quote','context']){await root.getByRole('combobox',{name:'日本語条件で保持する例外',exact:true}).selectOption(value);await expect(root.locator('[data-japanese-exception]')).toHaveAttribute('data-japanese-exception',value);await expect(root.locator('[data-japanese-graded="false"]')).toBeVisible()}
})
test('Japanese judge candidates retain human labels false accepts false rejects and shared blindspots',async({page})=>{
 const root=await open(page,'evaluation','japanese-quality-evaluation','japanese-judge-division','人手と照合');for(const value of ['human','wrong','right','blindspots','none']){await root.getByRole('combobox',{name:'日本語judgeの不足する検証',exact:true}).selectOption(value);const data=root.locator('[data-japanese-judge-candidate]');await expect(data).toHaveAttribute('data-japanese-judge-candidate',String(value==='none'));await expect(data).toHaveAttribute('data-japanese-grading-guaranteed','false');await expect(data).toHaveAttribute('data-japanese-model-executed','false')}
 await root.getByRole('button',{name:'コードの範囲',exact:true}).click();for(const kind of ['notation','style','context'])for(const scope of ['both','scope','exceptions']){await root.getByRole('combobox',{name:'日本語の採点対象',exact:true}).selectOption(kind);await root.getByRole('combobox',{name:'日本語チェックの定義状態',exact:true}).selectOption(scope);const data=root.locator('[data-japanese-check-route]');await expect(data).toHaveAttribute('data-japanese-check-route',kind==='notation'&&scope==='both'?'code':'human-or-validated-judge');await expect(data).toHaveAttribute('data-japanese-naturalness-guaranteed','false');await expect(data).toHaveAttribute('data-japanese-graded','false')}
})
test('trace hierarchy and span fields retain parent task versions and tool errors without actual collection',async({page})=>{
 const root=await open(page,'operations','observability-and-tracing','trace-hierarchy-versions','階層で追う');await expect(root.locator('svg[data-quality-trace-diagram]')).toContainText('セッション');await expect(root.locator('svg[data-quality-trace-diagram]')).toContainText('タスク実行');await root.getByRole('button',{name:'項目を分ける',exact:true}).click();for(const [value,field] of [['common','parent'],['task','versions'],['llm','stop'],['tool','result-or-error']]){await root.getByRole('combobox',{name:'確認するトレースのスパン',exact:true}).selectOption(value);const data=root.locator('[data-trace-span]');await expect(data).toHaveAttribute('data-trace-span',value);expect((await data.getAttribute('data-trace-fields')).split(',')).toContain(field);await expect(data).toHaveAttribute('data-trace-collected','false');await expect(data).toHaveAttribute('data-trace-quality-verified','false')}
})
test('equal toy means can hide a different tail without determining production p95 or cause',async({page})=>{
 const root=await open(page,'operations','observability-and-tracing','trace-signals-data-response','裾を読む');for(const [value,max] of [['tail','13'],['equal','4']]){await root.getByRole('combobox',{name:'ステップ数の模式分布',exact:true}).selectOption(value);const data=root.locator('[data-trace-tail-mean]');await expect(data).toHaveAttribute('data-trace-tail-mean','4');await expect(data).toHaveAttribute('data-trace-tail-max',max);await expect(data).toHaveAttribute('data-trace-percentile-measured','false');await expect(data).toHaveAttribute('data-trace-cause-determined','false');await expect(root.locator('svg[data-quality-trace-diagram] tspan').filter({hasText:new RegExp(`^模式4件: 平均4、最大${max}ステップ$`)})).toHaveCount(1)}
})
test('full trace design keeps masking retention access and storage permission separate from real transmission',async({page})=>{
 const root=await open(page,'operations','observability-and-tracing','trace-signals-data-response','全文の扱い');for(const value of ['mask','retention','access','location','none']){await root.getByRole('combobox',{name:'トレース全文で不足する設計',exact:true}).selectOption(value);const data=root.locator('[data-trace-data-candidate]');await expect(data).toHaveAttribute('data-trace-data-candidate',String(value==='none'));for(const attr of ['data-trace-data-stored','data-trace-external-sent','data-trace-leakage-prevented'])await expect(data).toHaveAttribute(attr,'false')}
})
test('original examples hierarchy tables and TODO survive without JavaScript',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const page=await context.newPage();for(const [chapter,route,text] of [['evaluation','fairness-and-bias-evaluation','全体の平均品質'],['evaluation','japanese-quality-evaluation','お伺いする'],['operations','observability-and-tracing','親スパンへの参照']]){await page.goto(`${base}/docs/${chapter}/${route}`);await expect(page.locator('article')).toContainText(text);await expect(page.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await context.close()}
})
test('low PC playback pause and print retain hierarchy and the original article',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/observability-and-tracing`);const root=page.locator('[data-diagram-id="trace-hierarchy-versions"]');await root.getByRole('button',{name:'階層で追う',exact:true}).click();await root.getByRole('button',{name:'図解を再生',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(root.locator('svg[data-quality-trace-diagram]')).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('親スパンへの参照');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
