import {test,expect} from '@playwright/test'
import {RELEASE_RESPONSE_STAGES} from '../../lib/release-response-model.mjs'
import {checkReadingArticles} from './reading-article-checks.mjs'
checkReadingArticles({name:'Release response',chapter:'operations',stages:RELEASE_RESPONSE_STAGES,sceneSelector:'svg[data-release-response-diagram]',articles:[['versioning-and-model-updates',['version-composition-pinning','version-rollout-migration']],['incident-response',['incident-detection-containment','incident-effects-learning']],['feedback-loops',['feedback-signals-collection','feedback-triage-release']]]})
const base=process.env.NEXT_PUBLIC_BASE_PATH||'',svg=root=>root.locator('svg[data-release-response-diagram]')
async function open(page,route,id,label){await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('all six versions must be recorded and a pin still has a retirement boundary',async({page})=>{
 const root=await open(page,'versioning-and-model-updates','version-composition-pinning','応答へ結ぶ');for(const value of ['code','prompt','tool','model','settings','evaluation','none']){await root.getByRole('combobox',{name:'構成特定で不足する版',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'組合せ特定の検討候補':'不足する版へ戻る');await expect(svg(root)).toContainText('決定性は別の条件')}
 await root.getByRole('button',{name:'指定の違い',exact:true}).click();for(const value of ['snapshot','alias']){await root.getByRole('combobox',{name:'モデル参照の模式条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='snapshot'?'pinでも期限がある':'aliasは更新を受ける')}
})
test('shadow user replies remain old while new processing never performs side effect tools',async({page})=>{
 const root=await open(page,'versioning-and-model-updates','version-rollout-migration','配信を分ける');for(const [mode,values] of [['old',['100%','0%','0%']],['shadow',['100%','0%','100%']],['canary',['90%','10%','10%']],['full',['0%','100%','100%']]]){await root.getByRole('combobox',{name:'模式の段階リリース',exact:true}).selectOption(mode);expect(await svg(root).locator('g').filter({has:page.locator('rect')}).allTextContents()).toEqual(values.map((value,i)=>`${['旧を返す','新を返す','新で処理'][i]}${value}`));if(mode==='shadow'){await expect(svg(root)).toContainText('新結果はユーザーへ返さない');await expect(svg(root)).toContainText('副作用toolは実行しない')}}
})
test('rollback requires actual exercise and an available old model while existing effects remain',async({page})=>{
 const root=await open(page,'versioning-and-model-updates','version-rollout-migration','旧構成へ戻す');for(const value of ['flag','exercise','retired','none']){await root.getByRole('combobox',{name:'戻る経路で不足する条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='none'?'戻る経路の検討候補':'不足する切替条件へ戻る');await expect(svg(root)).toContainText('既に起きた作用は取消せない')}
})
test('changed judge validation and each migration prerequisite remain independently required',async({page})=>{
 const root=await open(page,'versioning-and-model-updates','version-rollout-migration','差分を読む');for(const judge of ['changed','unchanged'])for(const missing of ['human','suite','failures','prompt','stages','none']){await root.getByRole('combobox',{name:'移行でのjudge変更',exact:true}).selectOption(judge);await root.getByRole('combobox',{name:'移行で不足する確認',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'||judge==='unchanged'&&missing==='human'?'移行の検討候補':'不足する検証へ戻る')}
})
test('quiet quality and read preserving containment do not become actual alerts or activation',async({page})=>{
 const root=await open(page,'incident-response','incident-detection-containment','複数の信号');for(const value of ['technical','steps','cost','quality','tool']){await root.getByRole('combobox',{name:'検知で読む信号',exact:true}).selectOption(value);if(value==='quality')await expect(svg(root)).toContainText('正常終了でも誤答')}
 await root.getByRole('button',{name:'事前に準備',exact:true}).click();for(const value of ['absent','untested','tested']){await root.getByRole('combobox',{name:'停止手段の準備条件',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='tested'?'封じ込め設計の検討候補':'準備または演習へ戻る')}
 await root.getByRole('button',{name:'範囲を選ぶ',exact:true}).click();for(const value of ['auto','write','readOnly','tenant','all']){await root.getByRole('combobox',{name:'封じ込めの模式範囲',exact:true}).selectOption(value);await expect(svg(root)).toContainText(value==='write'||value==='readOnly'?'読取を残す設計':'影響範囲と代替');await expect(svg(root)).toContainText('図は実停止を行わない')}
})
test('already sent notifications need correction and each compensation condition remains required',async({page})=>{
 const root=await open(page,'incident-response','incident-effects-learning','補償の違い');for(const effect of ['sent','write'])for(const missing of ['scope','logs','permission','none']){await root.getByRole('combobox',{name:'補償を考える模式作用',exact:true}).selectOption(effect);await root.getByRole('combobox',{name:'補償で不足する確認',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'?'補償の検討候補':'不足する確認へ戻る');await expect(svg(root)).toContainText(effect==='sent'?'送信は取消せない':'巻戻し条件を点検')}
})
test('implicit event availability cannot replace scope or outcome validation and is not inferred for explicit reasons',async({page})=>{
 const root=await open(page,'feedback-loops','feedback-signals-collection','必要な範囲');for(const kind of ['implicit','explicit'])for(const missing of ['trace','events','outcome','purpose','minimum','retention','access','none']){await root.getByRole('combobox',{name:'品質を考えるシグナルの系統',exact:true}).selectOption(kind);await root.getByRole('combobox',{name:'収集で不足する条件',exact:true}).selectOption(missing);await expect(svg(root)).toContainText(missing==='none'||kind==='explicit'&&missing==='events'?'収集設計の検討候補':'不足する収集条件へ戻る')}
})
test('all improvement conditions still require the toy signal improvement and a masked case needs permission',async({page})=>{
 const root=await open(page,'feedback-loops','feedback-triage-release','改善を確かめる');for(const missing of ['permission','mask','regression','comparison','owner','none'])for(const observed of ['unknown','improved']){await root.getByRole('combobox',{name:'改善の一周で不足する条件',exact:true}).selectOption(missing);await root.getByRole('combobox',{name:'品質改善の模式確認',exact:true}).selectOption(observed);await expect(svg(root)).toContainText(missing!=='none'?'不足する運用条件へ戻る':observed==='improved'?'模式条件で一周を照合':'実改善の確認が残る');await expect(svg(root)).toContainText('図は測定・公開を行わない')}
})
test('source whole tables Mermaid dates and TODO survive without JavaScript',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const page=await context.newPage();for(const [route,text] of [['versioning-and-model-updates','コスト 2 倍'],['incident-response','巻き戻せない操作'],['feedback-loops','修正 = 不満とは限らない']]){await page.goto(`${base}/docs/operations/${route}`);await expect(page.locator('article')).toContainText(text);await expect(page.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await context.close()}
})
test('low PC playback pause and print preserve original operational examples',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/feedback-loops`);const root=page.locator('[data-diagram-id="feedback-triage-release"]');await root.getByRole('button',{name:'担当と周期',exact:true}).click();await root.getByRole('button',{name:'図解を再生',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(root)).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('件数と重大度');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
