import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {SECURITY_ADVERSITY_STAGES} from '../../lib/security-adversity-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['red-teaming-agents',['red-exercise-design','red-results-return']],['ai-supply-chain-security',['supply-asset-integrity','supply-admission-update']],['advanced-attack-patterns',['attack-delayed-paths','attack-propagation-controls']]]
checkReadingArticles({name:'Security adversity',chapter:'security',articles,stages:SECURITY_ADVERSITY_STAGES,sceneSelector:'svg[data-security-adversity-diagram]'})
const svg=r=>r.locator('svg[data-security-adversity-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/security/${route}`);const r=page.locator(`[data-diagram-id="${id}"]`);await r.getByRole('button',{name:label,exact:true}).click();return r}
test('each asset and attack map row retains readable distinct text positions',async({page})=>{for(const [route,id,label,titles] of [['ai-supply-chain-security','supply-asset-integrity','五つの資産',['modelの重み','学習・調整data','prompt・skill','MCP・tool','通常の依存']],['advanced-attack-patterns','attack-delayed-paths','同じ原理の別経路',['記憶','知識源','toolの内容','Agent間','条件起動']],['advanced-attack-patterns','attack-propagation-controls','防御を対応づける',['記憶','知識源','tool','Agent間','条件起動']]]){const r=await open(page,route,id,label);const positions=[];for(const title of titles){const b=await svg(r).locator('text').filter({hasText:new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`)}).boundingBox();expect(b).not.toBeNull();positions.push(b)}for(let i=1;i<positions.length;i++)expect(positions[i].y).toBeGreaterThan(positions[i-1].y+positions[i-1].height)}})
test('each scope goal capability evidence or isolation gap returns to exercise design without launching attacks',async({page})=>{const r=await open(page,'red-teaming-agents','red-exercise-design','四つの設計');for(const v of ['scope','goal','capability','evidence','isolation','none']){await r.getByRole('combobox',{name:'演習設計で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'演習設計の検討候補':'不足条件へ戻る');await expect(svg(r)).toContainText('図は攻撃を実行しない')}})
test('observed text request execution effect and missing observations retain distinct findings',async({page})=>{const r=await open(page,'red-teaming-agents','red-results-return','証拠の違い');for(const [v,t] of [['text','出力だけを観測'],['request','tool要求を観測'],['execution','実行だけを観測'],['effect','外部の作用を観測'],['unknown','観測不足で未確定']]){await r.getByRole('combobox',{name:'観測した証拠の範囲',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('未観測は全安全でない')}})
test('repair needs structure original case variants and regression without certifying every threat',async({page})=>{const r=await open(page,'red-teaming-agents','red-results-return','同じと派生');for(const v of ['structure','same','variants','regression','none']){await r.getByRole('combobox',{name:'修正後に不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'修正受入の検討候補':'不足する再検証へ戻る');await expect(svg(r)).toContainText('全脅威の安全ではない')}})
test('source integrity license and registry are independent of harmless behavior',async({page})=>{const r=await open(page,'ai-supply-chain-security','supply-asset-integrity','審査と許諾');for(const v of ['source','integrity','license','registry','none']){await r.getByRole('combobox',{name:'資産審査で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'受入設計の検討候補':'不足する受入確認へ戻る');await expect(svg(r)).toContainText('hash一致は無害性でない')}})
test('promotion cannot infer authority from a passed trial or changed version',async({page})=>{const r=await open(page,'ai-supply-chain-security','supply-admission-update','明示的に昇格');for(const v of ['review','trial','rights','approval','version','none']){await r.getByRole('combobox',{name:'昇格判断で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'昇格判断の検討候補':'不足条件へ戻る');await expect(svg(r)).toContainText('図は権限を付与しない')}})
test('new asset version cannot transfer old approval and requires delta review and retrial',async({page})=>{const r=await open(page,'ai-supply-chain-security','supply-admission-update','固定と差分');for(const [v,t] of [['same','同じ版の受入を参照'],['new-unreviewed','差分と再試用へ戻る'],['new-reviewed','更新設計の検討候補']]){await r.getByRole('combobox',{name:'資産の版と再検証',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);if(v!=='same')await expect(svg(r)).toContainText('旧版の承認を転用しない');await expect(svg(r)).toContainText('図は実更新を行わない')}})
test('stored memory preserves write source and tenant checks and untrusted reading later',async({page})=>{const r=await open(page,'advanced-attack-patterns','attack-delayed-paths','記憶の時間差');for(const v of ['write','source','tenant','none']){await r.getByRole('combobox',{name:'記憶の取扱いで不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'記憶の扱いを検討':'不足する書込・出所・権限へ');await expect(svg(r)).toContainText('保存済みでも命令や正解にはしない')}})
test('peer source minimal rights and parent gates remain necessary and do not raise authority',async({page})=>{const r=await open(page,'advanced-attack-patterns','attack-propagation-controls','委譲の確認');for(const v of ['source','rights','gate','none']){await r.getByRole('combobox',{name:'Agent間で不足する境界',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'委譲設計の検討候補':'不足する境界へ戻る');await expect(svg(r)).toContainText('図は権限を増やさない')}})
test('absent or present triggers cannot establish all conditions safe or execute an attack',async({page})=>{const r=await open(page,'advanced-attack-patterns','attack-delayed-paths','条件が揃う時');for(const [v,t] of [['absent','起動を観測していない'],['present','起動条件が存在する']]){await r.getByRole('combobox',{name:'条件起動の観測',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('未発火は全安全でない');await expect(svg(r)).toContainText('図は攻撃を実行しない')}})
test('original exercise source trust and delayed input text tables and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['red-teaming-agents','脅威モデル'],['ai-supply-chain-security','サプライチェーン'],['advanced-attack-patterns','条件起動']]){await p.goto(`${base}/docs/security/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual pause and print preserve supply acceptance and original update boundaries',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/security/ai-supply-chain-security`);const r=page.locator('[data-diagram-id="supply-admission-update"]');await r.getByRole('button',{name:'固定と差分',exact:true}).click();const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(r)).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('バージョン');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
