import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {SECURITY_AUTHORITY_STAGES} from '../../lib/security-authority-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['agent-identity-and-auth',['identity-delegation-scope','identity-audit-credentials','identity-standards-connection']],['data-exfiltration',['exfiltration-routes-url','exfiltration-structure-authorization']],['guardrails',['guard-layers-enforcement','guard-quality-response']]]
checkReadingArticles({name:'Security authority',chapter:'security',articles,stages:SECURITY_AUTHORITY_STAGES,sceneSelector:'svg[data-security-authority-diagram]'})
const svg=root=>root.locator('svg[data-security-authority-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/security/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('effective scope takes intersection not union and either empty principal removes all operations',async({page})=>{const r=await open(page,'agent-identity-and-auth','identity-delegation-scope','権限の交差');const sets={reader:['read'],writer:['read','write'],full:['read','write','delete','send'],none:[]};for(const a of Object.keys(sets))for(const b of Object.keys(sets)){await r.getByRole('combobox',{name:'利用者の模式権限',exact:true}).selectOption(a);await r.getByRole('combobox',{name:'Agentの模式許可',exact:true}).selectOption(b);const common=sets[a].filter(x=>sets[b].includes(x));await expect(svg(r)).toContainText(common.length?`共通する操作: ${common.join(' / ')}`:'共通する操作はない')}})
test('token audience expiry and scope cannot be skipped just because the subject is the same',async({page})=>{const r=await open(page,'agent-identity-and-auth','identity-delegation-scope','tokenの境界');for(const v of ['audience','expiry','scope','none']){await r.getByRole('combobox',{name:'tokenで不足する境界',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'token設計の検討候補':'不足する条件へ戻る');await expect(svg(r)).toContainText('図はtokenを発行しない')}})
test('placeholder visibility differs from putting a secret in prompt and cannot erase a previously read secret',async({page})=>{const r=await open(page,'agent-identity-and-auth','identity-audit-credentials','実行時の注入');for(const v of ['prompt','runtime','egress']){await r.getByRole('combobox',{name:'資格情報を渡す模式経路',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='prompt'?'modelが鍵を読む':'modelには記号');if(v==='prompt')await expect(svg(r)).toContainText('既読秘密の削除は別問題');if(v==='egress')await expect(svg(r)).toContainText('送信時に記号を差し替え')}})
test('revoking identity requires all three future controls and does not cancel past effects',async({page})=>{const r=await open(page,'agent-identity-and-auth','identity-audit-credentials','ownerと失効');for(const v of ['token','credentials','tools','none']){await r.getByRole('combobox',{name:'失効で不足する制御',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'今後の制御の検討候補':'残る制御へ戻る');await expect(svg(r)).toContainText('実行済みの作用は残る')}})
test('destination path query and redirect controls all remain necessary with a proxy',async({page})=>{const r=await open(page,'data-exfiltration','exfiltration-routes-url','取得前の制約');await r.getByRole('combobox',{name:'画像取得の有無',exact:true}).selectOption('proxy');for(const v of ['destination','content','redirect','none']){await r.getByRole('combobox',{name:'URL取得で不足する制約',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'取得設計の検討候補':'不足する制約へ戻る');await expect(svg(r)).toContainText('proxyだけで保護しない')}await r.getByRole('combobox',{name:'画像取得の有無',exact:true}).selectOption('blocked');await expect(svg(r)).toContainText('自動取得の経路を閉じる')})
test('retrieval authorization is enforced before model input and output detection cannot replace it',async({page})=>{const r=await open(page,'data-exfiltration','exfiltration-structure-authorization','取得側の認可');for(const v of ['user','tenant','resource','none']){await r.getByRole('combobox',{name:'取得認可で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'取得設計の検討候補':'modelへ入れる前に戻す');await expect(svg(r)).toContainText('権限外dataをmodelへ渡さない')}})
test('a safe LLM result cannot override missing tool argument limit or approval guards',async({page})=>{const r=await open(page,'guardrails','guard-layers-enforcement','作用の直前');for(const llm of ['safe','unsafe'])for(const v of ['tool','args','limit','approval','none']){await r.getByRole('combobox',{name:'追加LLM検査の模式結果',exact:true}).selectOption(llm);await r.getByRole('combobox',{name:'action guardで不足する制約',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'実行制約の検討候補':'不足する制約で停止');await expect(svg(r)).toContainText('図はtoolを実行しない')}})
test('guard strength reports separate legitimate and violating denominators and never a measured optimum',async({page})=>{const r=await open(page,'guardrails','guard-quality-response','二つの誤り');for(const [v,fp,fn] of [['light',2,12],['balanced',8,5],['strict',20,2]]){await r.getByRole('combobox',{name:'架空caseのguard強度',exact:true}).selectOption(v);await expect(svg(r)).toContainText(`正当 ${fp} / 100件`);await expect(svg(r)).toContainText(`違反 ${fn} / 100件`);await expect(svg(r)).toContainText('実製品の品質')}})
test('incident guard requires review or stops tools without making earlier actions disappear',async({page})=>{const r=await open(page,'guardrails','guard-quality-response','異常時の縮退');for(const [v,t] of [['normal','平時の制約と監視'],['approval','強い承認のゲート'],['stop','toolを停止する']]){await r.getByRole('combobox',{name:'異常時のguard運用',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('実行済みの作用は別に確認')}})
test('proxy hides viewer IP but forwards URL content and the diagrams initiate no exfiltration request',async({page})=>{const requests=[];page.on('request',r=>requests.push(r.url()));const r=await open(page,'data-exfiltration','exfiltration-routes-url','proxyの限界');await r.getByRole('combobox',{name:'画像URLの模式取得方法',exact:true}).selectOption('proxy');await expect(svg(r)).toContainText('IPを隠しても、URLの内容は上流へ届く');expect(requests.some(u=>u.includes('attacker.example'))).toBe(false);await r.getByRole('combobox',{name:'画像URLの模式取得方法',exact:true}).selectOption('blocked');await expect(svg(r)).toContainText('自動取得の経路を閉じる')})
test('fixed standard product status API contract and preview migration retain distinct dates and scope',async({page})=>{const r=await open(page,'agent-identity-and-auth','identity-standards-connection','設定を移す');for(const [v,t] of [['openai','画面の接続設定とは別'],['google','legacy connectorからの移行'],['okta','upcomingを確定停止日にしない']]){await r.getByRole('combobox',{name:'接続と設定移行の確認先',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t)}await expect(page.locator('article')).toContainText('2026-09-10');await expect(page.locator('article')).toContainText('Internet-Draft')})
test('original identity trace URL and guard tables and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['agent-identity-and-auth','RFC 8693'],['data-exfiltration','リダイレクト'],['guardrails','誤検知']]){await p.goto(`${base}/docs/security/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual pause and print retain scoped authorization and source content',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/security/agent-identity-and-auth`);const r=page.locator('[data-diagram-id="identity-delegation-scope"]');await r.getByRole('button',{name:'権限の交差',exact:true}).click();const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(r)).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('ユーザー権限');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
