import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {SECURITY_BOUNDARIES_STAGES} from '../../lib/security-boundaries-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['threat-model-overview',['threat-boundary-cycle','threat-trifecta-workflow']],['prompt-injection',['injection-input-defense','injection-repeated-risk']],['tool-permissions-and-sandboxing',['permission-gates-scope','permission-sandbox-mcp']]]
checkReadingArticles({name:'Security boundaries',chapter:'security',articles,stages:SECURITY_BOUNDARIES_STAGES,sceneSelector:'svg[data-security-boundaries-diagram]'})
const svg=root=>root.locator('svg[data-security-boundaries-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/security/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('one removed trifecta capability closes only that path and never declares all threats safe',async({page})=>{const r=await open(page,'threat-model-overview','threat-trifecta-workflow','一条件を外す');for(const v of ['none','data','input','send']){await r.getByRole('combobox',{name:'三重奏で閉じる条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'三条件が揃う経路の候補':'この三条件の経路は閉じる');await expect(svg(r)).toContainText('全脅威への安全保証ではない')}})
test('authorization needs caller tenant resource and operation rather than a broad service account',async({page})=>{const r=await open(page,'tool-permissions-and-sandboxing','permission-gates-scope','代理の混同');for(const v of ['caller','tenant','resource','operation','none']){await r.getByRole('combobox',{name:'認可で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'認可設計の検討候補':'不足条件の照合へ戻る');await expect(svg(r)).toContainText('図は実操作を実行しない')}})
test('each irreversible high impact or untrusted recent context retains a review before execution',async({page})=>{const r=await open(page,'tool-permissions-and-sandboxing','permission-gates-scope','操作の二軸');for(const v of ['irreversible','large','external','small']){await r.getByRole('combobox',{name:'承認を配置する状況',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='small'?'限定した境界を確認':'実行前の確認へ戻す');await expect(svg(r)).toContainText('図は承認を取得しない')}})
test('100 IID trials show one expected miss and 63.4 percent chance rather than a guaranteed breach',async({page})=>{const r=await open(page,'prompt-injection','injection-repeated-risk','繰返しの量');for(const [n,expectation,percent] of [['0','0.00','0.0'],['1','0.01','1.0'],['10','0.10','9.6'],['100','1.00','63.4']]){await r.getByRole('combobox',{name:'独立な模式試行の数',exact:true}).selectOption(n);await expect(svg(r)).toContainText(`${expectation} 件`);await expect(svg(r)).toContainText(`一件以上の見逃し: ${percent}%`);await expect(svg(r)).toContainText('100回で必ずとは限らない');await expect(svg(r)).toContainText('実測の安全率')}})
test('the five defense layers distinguish enforced controls fallible detection and mixed output',async({page})=>{const r=await open(page,'prompt-injection','injection-input-defense','五層の役割');for(const [v,t] of [['design','実行側で強制する境界'],['execution','実行側で強制する境界'],['input','誤り得る検知の層'],['model','誤り得る検知の層'],['output','強制と検知を分ける']]){await r.getByRole('combobox',{name:'読み分ける防御の層',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);if(v==='output'){await expect(svg(r)).toContainText('許可宛先: 実行側で制限');await expect(svg(r)).toContainText('内容検査: 誤り得る判断')}}})
test('sandbox review requires all four independent constraints without certifying actual isolation',async({page})=>{const r=await open(page,'tool-permissions-and-sandboxing','permission-sandbox-mcp','四つの制約');for(const v of ['environment','egress','resources','account','none']){await r.getByRole('combobox',{name:'隔離で不足する制約',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'実隔離を検証する候補':'不足する制約へ戻る');await expect(svg(r)).toContainText('図は隔離を実検証しない')}})
test('MCP pin source tools and token do not turn authenticated results into trusted instructions',async({page})=>{const r=await open(page,'tool-permissions-and-sandboxing','permission-sandbox-mcp','toolと結果');for(const v of ['source','version','tools','token','none']){await r.getByRole('combobox',{name:'MCPで不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'接続設計の検討候補':'不足する条件へ戻る');await expect(svg(r)).toContainText('返った内容は未信頼入力')}})
test('read task has no write tool and incident mode removes tools and restores review',async({page})=>{const r=await open(page,'tool-permissions-and-sandboxing','permission-sandbox-mcp','状況で絞る');for(const [v,t] of [['read','write toolは渡さない'],['write','read / scoped-write'],['incident','toolを停止する']]){await r.getByRole('combobox',{name:'権限を渡すtaskの状況',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('backendでもscope制限')}})
test('tool results return to model input and a trusted user is not the author of external content',async({page})=>{const r=await open(page,'threat-model-overview','threat-boundary-cycle','結果も入力');await expect(svg(r)).toContainText('tool結果 → 再び入力');await expect(svg(r)).toContainText('資料の作者は別');await expect(svg(r)).toContainText('内容への信頼は認証と別');expect(await svg(r).locator('path').count()).toBeGreaterThan(2)})
test('each attacker goal retains its separate effect rather than only model refusal',async({page})=>{const r=await open(page,'prompt-injection','injection-input-defense','四つの目標');for(const [v,t] of [['hijack','実toolなしでも影響する'],['leak','dataと送信経路を制限'],['rights','本人・対象・操作を制限'],['recon','秘密をpromptに置かない']]){await r.getByRole('combobox',{name:'読み分ける攻撃の目標',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t)}})
test('original trust diagram tables source dates and unverified updates remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['threat-model-overview','致命的三重奏'],['prompt-injection','99%'],['tool-permissions-and-sandboxing','MCP']]){await p.goto(`${base}/docs/security/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual pause and print keep the original permission and sandbox boundaries',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/security/tool-permissions-and-sandboxing`);const r=page.locator('[data-diagram-id="permission-sandbox-mcp"]');await r.getByRole('button',{name:'四つの制約',exact:true}).click();const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(r)).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('最小権限');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
