import {test,expect} from '@playwright/test'
import {SERVICE_BUDGETS_STAGES} from '../../lib/service-budgets-model.mjs'
import {checkReadingArticles} from './reading-article-checks.mjs'
checkReadingArticles({name:'Service budgets',chapter:'operations',stages:SERVICE_BUDGETS_STAGES,sceneSelector:'svg[data-service-budgets-diagram]',articles:[['cost-management',['cost-history-measurement','cost-reduction-quality','cost-budget-cache-accounting']],['latency-optimization',['latency-breakdown-tools','latency-levers-priorities']],['ai-slo-design',['slo-indicators-reliability','slo-budget-release-sla']]]})
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
async function open(page,route,id,label){await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${base}/docs/operations/${route}`);const root=page.locator(`[data-diagram-id="${id}"]`);await root.getByRole('button',{name:label,exact:true}).click();return root}
test('repeated toy history changes cumulative input while quality and actual token measurement remain separate',async({page})=>{
 const root=await open(page,'cost-management','cost-history-measurement','履歴の累積');for(const [steps,cap,total] of [['1','8','4'],['3','8','18'],['5','8','40'],['5','3','38'],['5','1','28'],['8','8','88'],['8','3','68'],['8','1','46']]){await root.getByRole('combobox',{name:'模式の履歴再送ステップ数',exact:true}).selectOption(steps);await root.getByRole('combobox',{name:'模式で保持する履歴の増分数',exact:true}).selectOption(cap);const data=root.locator('[data-cost-history-total]');await expect(data).toHaveAttribute('data-cost-history-total',total);await expect(data).toHaveAttribute('data-cost-tokens-measured','false');await expect(data).toHaveAttribute('data-cost-quality-verified','false');await expect(root.locator('svg[data-service-budgets-diagram] tspan').filter({hasText:new RegExp(`^模式${steps}ステップ: 総入力 ${total}単位$`)})).toHaveCount(1)}
})
test('stable prefixes remain only cache candidates and changing the beginning cannot become an actual hit',async({page})=>{
 const root=await open(page,'cost-management','cost-reduction-quality','前方一致');for(const [value,result] of [['stable','candidate'],['variable','changed']]){await root.getByRole('combobox',{name:'キャッシュ用prefixの模式配置',exact:true}).selectOption(value);const data=root.locator('[data-cost-cache-prefix]');await expect(data).toHaveAttribute('data-cost-cache-prefix',result);await expect(data).toHaveAttribute('data-cost-cache-hit-measured','false')}
})
test('each budget layer stops the design independently without cancelling already incurred effects',async({page})=>{
 const root=await open(page,'cost-management','cost-budget-cache-accounting','三層の上限');for(const value of ['task','tenant','system','none']){await root.getByRole('combobox',{name:'模式予算の残量がない層',exact:true}).selectOption(value);const data=root.locator('[data-cost-budget-blocked]');await expect(data).toHaveAttribute('data-cost-budget-blocked',value);await expect(data).toHaveAttribute('data-cost-budget-may-continue',String(value==='none'));await expect(data).toHaveAttribute('data-cost-actually-stopped','false');await expect(data).toHaveAttribute('data-cost-effects-undone','false')}
})
test('cache reads writes and ordinary input are disjoint and no actual pricing or billing occurs',async({page})=>{
 const root=await open(page,'cost-management','cost-budget-cache-accounting','三つの区分');for(const [value,ordinary,weighted] of [['reuse','20','62'],['rewrite','20','140'],['none','100','100']]){await root.getByRole('combobox',{name:'cacheの模式input内訳',exact:true}).selectOption(value);const data=root.locator('[data-cost-cache-ordinary]');await expect(data).toHaveAttribute('data-cost-cache-ordinary',ordinary);await expect(data).toHaveAttribute('data-cost-cache-weighted',weighted);await expect(data).toHaveAttribute('data-cost-priced','false');await expect(data).toHaveAttribute('data-cost-billed','false')}await expect(root.locator('svg[data-service-budgets-diagram]')).toContainText('2026-09-10')
})
test('latency decomposition changes the dominant term without declaring a real measurement',async({page})=>{
 const root=await open(page,'latency-optimization','latency-breakdown-tools','実時間を分解');for(const [value,llm,tools,total] of [['llm','16','5','22'],['tool','6','19','26'],['short','6','5','12']]){await root.getByRole('combobox',{name:'内訳を読む模式時間の構成',exact:true}).selectOption(value);const data=root.locator('[data-latency-total]');await expect(data).toHaveAttribute('data-latency-llm',llm);await expect(data).toHaveAttribute('data-latency-tools',tools);await expect(data).toHaveAttribute('data-latency-total',total);await expect(data).toHaveAttribute('data-latency-measured','false')}
})
test('only independent tools can use a parallel critical path and dependent results preserve serial time',async({page})=>{
 const root=await open(page,'latency-optimization','latency-breakdown-tools','往復を減らす');for(const dependent of ['independent','dependent'])for(const parallel of ['parallel','serial']){await root.getByRole('combobox',{name:'模式tool間の依存関係',exact:true}).selectOption(dependent);await root.getByRole('combobox',{name:'模式toolの実行配置',exact:true}).selectOption(parallel);const used=dependent==='independent'&&parallel==='parallel',data=root.locator('[data-latency-parallel-used]');await expect(data).toHaveAttribute('data-latency-parallel-used',String(used));await expect(data).toHaveAttribute('data-latency-tool-pair-time',used?'5':'8');await expect(data).toHaveAttribute('data-latency-tools-executed','false')}
})
test('latency optimization retains quality total cost measured time priorities and asynchronous completion boundaries',async({page})=>{
 const root=await open(page,'latency-optimization','latency-levers-priorities','三つの優先');for(const value of ['quality','cost','latency','priority','none']){await root.getByRole('combobox',{name:'時間最適化で不足する条件',exact:true}).selectOption(value);const data=root.locator('[data-latency-review-candidate]');await expect(data).toHaveAttribute('data-latency-review-candidate',String(value==='none'));await expect(data).toHaveAttribute('data-latency-deployed','false');await expect(data).toHaveAttribute('data-latency-improvement-guaranteed','false')}await root.getByRole('button',{name:'同期の必要',exact:true}).click();for(const value of ['job','sync']){await root.getByRole('combobox',{name:'完了を待つ必要のある模式要件',exact:true}).selectOption(value);await expect(root.locator('svg[data-service-budgets-diagram]')).toContainText('即時完了の保証にせず')}
})
test('SLI choices and measurement trust retain calibrated judges sampling and the measured time window',async({page})=>{
 const root=await open(page,'ai-slo-design','slo-indicators-reliability','候補を選ぶ');for(const value of ['success','judge','deviation','escalation','combined']){await root.getByRole('combobox',{name:'SLOで確認するSLI候補',exact:true}).selectOption(value);await expect(root.locator('[data-slo-indicator]')).toHaveAttribute('data-slo-indicator',value)}await root.getByRole('button',{name:'測定の信頼',exact:true}).click();for(const value of ['definition','judge','sampling','window','none']){await root.getByRole('combobox',{name:'品質SLIの不足する測定条件',exact:true}).selectOption(value);const data=root.locator('[data-slo-measurement-candidate]');await expect(data).toHaveAttribute('data-slo-measurement-candidate',String(value==='none'));await expect(data).toHaveAttribute('data-slo-quality-measured','false');await expect(data).toHaveAttribute('data-slo-contract-created','false')}
})
test('error budget zero and exceeded allowance block a release candidate and remainder never bypasses measurement or guards',async({page})=>{
 const root=await open(page,'ai-slo-design','slo-budget-release-sla','残量と判断');for(const [target,failed,allowed,remaining] of [['99','6','10','4'],['99','10','10','0'],['99','12','10','-2'],['99','50','10','-40'],['95','6','50','44'],['95','50','50','0'],['90','50','100','50']]){await root.getByRole('combobox',{name:'SLOの模式目標',exact:true}).selectOption(target);await root.getByRole('combobox',{name:'期間内1000件の模式失敗件数',exact:true}).selectOption(failed);const data=root.locator('[data-slo-allowed]');await expect(data).toHaveAttribute('data-slo-allowed',allowed);await expect(data).toHaveAttribute('data-slo-remaining',remaining);await expect(data).toHaveAttribute('data-slo-exhausted',String(Number(remaining)<=0));await expect(data).toHaveAttribute('data-slo-quality-measured','false')}
 await root.getByRole('button',{name:'変更の関門',exact:true}).click();await root.getByRole('combobox',{name:'SLOの模式目標',exact:true}).selectOption('99');for(const failed of ['6','10','12'])for(const missing of ['measurement','guard','none']){await root.getByRole('combobox',{name:'期間内1000件の模式失敗件数',exact:true}).selectOption(failed);await root.getByRole('combobox',{name:'SLO変更の不足する条件',exact:true}).selectOption(missing);const data=root.locator('[data-slo-release-candidate]');await expect(data).toHaveAttribute('data-slo-release-candidate',String(failed==='6'&&missing==='none'));await expect(data).toHaveAttribute('data-slo-deployed','false');await expect(data).toHaveAttribute('data-slo-contract-created','false')}
})
test('source formulas dated API examples and TODO survive without JavaScript',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const page=await context.newPage();for(const [route,text] of [['cost-management','cache_write_tokens'],['latency-optimization','総レイテンシ ='],['ai-slo-design','内部で 99%']]){await page.goto(`${base}/docs/operations/${route}`);await expect(page.locator('article')).toContainText(text);await expect(page.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await context.close()}
})
test('low PC playback pause and print keep the budget and original SLA examples',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/operations/ai-slo-design`);const root=page.locator('[data-diagram-id="slo-budget-release-sla"]');await root.getByRole('button',{name:'残量と判断',exact:true}).click();await root.getByRole('button',{name:'図解を再生',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await root.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(root.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(root.locator('svg[data-service-budgets-diagram]')).toBeVisible();await expect(root.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('対外は 95%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
