import {test,expect} from '@playwright/test'
import {checkReadingArticles} from './reading-article-checks.mjs'
import {TRUST_PRIVACY_STAGES} from '../../lib/trust-privacy-model.mjs'
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const articles=[['content-provenance-and-detection',['provenance-layers-loss','provenance-detection-process']],['deepfake-and-impersonation-defense',['impersonation-callback-process','impersonation-report-monitor']],['privacy-enhancing-technologies',['privacy-layers-fit','privacy-unit-budget','privacy-basic-selection']]]
checkReadingArticles({name:'Trust privacy',chapter:'security',articles,stages:TRUST_PRIVACY_STAGES,sceneSelector:'svg[data-trust-privacy-diagram]'})
const svg=r=>r.locator('svg[data-trust-privacy-diagram]')
async function open(page,route,id,label){await page.goto(`${base}/docs/security/${route}`);const r=page.locator(`[data-diagram-id="${id}"]`);await r.getByRole('button',{name:label,exact:true}).click();return r}
test('present missing or invalid provenance cannot determine truth or call real signature verification',async({page})=>{const r=await open(page,'content-provenance-and-detection','provenance-layers-loss','剥離と編集');for(const [v,t] of [['present','履歴を照合する手がかり'],['absent','履歴だけでは判断できない'],['invalid','再署名のない編集']]){await r.getByRole('combobox',{name:'観測した来歴の状態',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('来歴なしは偽物の証拠でない');await expect(svg(r)).toContainText('来歴ありは内容の真実でない')}})
test('all detector results remain auxiliary and cannot establish identity or an AI verdict',async({page})=>{const r=await open(page,'content-provenance-and-detection','provenance-detection-process','推定の位置');for(const [v,t] of [['ai','AI由来らしい'],['human','人の制作物らしい'],['uncertain','判定が不確か']]){await r.getByRole('combobox',{name:'補助として読む検出signal',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('本人確認を成立させない');await expect(svg(r)).toContainText('AI製を断定しない')}})
test('urgent requests still need known contact independent channel identity approval and limits',async({page})=>{const r=await open(page,'deepfake-and-impersonation-defense','impersonation-callback-process','多重のプロセス');for(const v of ['contact','channel','identity','approval','limit','none']){await r.getByRole('combobox',{name:'重要指示で不足する確認',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'重要指示の検討候補':'不足する確認へ戻る');await expect(svg(r)).toContainText('急ぎでも確認を省かない');await expect(svg(r)).toContainText('図は送金や実承認をしない')}})
test('received report link returns to known official route without navigating or sending a report',async({page})=>{const r=await open(page,'deepfake-and-impersonation-defense','impersonation-report-monitor','窓口も偽装される');const url=page.url();for(const [v,t] of [['received','既知の正規経路へ戻る'],['official','正規窓口への確認候補']]){await r.getByRole('combobox',{name:'通報先へ到達する経路',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('図は移動や通報をしない');expect(page.url()).toBe(url)}})
test('aggregation learning and processing choose candidates without asserting a strongest or optimal PET',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-basic-selection','場面で選ぶ');for(const [v,t] of [['aggregation','差分プライバシーの候補'],['training','連合学習の候補'],['processing','秘密計算・TEEの候補']]){await r.getByRole('combobox',{name:'PETを選ぶ処理の場面',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('名称だけで最適にしない')}})
test('one row or event does not protect all records of a person and no unit forbids all attribute inference',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-unit-budget','単位を選ぶ');for(const v of ['row','event','person']){await r.getByRole('combobox',{name:'差分プライバシーの保護単位',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='person'?'一人の記録の単位':'一人全体への転用は不可');await expect(svg(r)).toContainText('全属性の推論禁止ではない')}})
test('epsilon changes exponential coefficient while delta independently adds to the fixed illustration bound',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-unit-budget','確率の上限');for(const e of ['0','0.1','0.5','1'])for(const d of ['0','0.001','0.01']){await r.getByRole('combobox',{name:'模式不等式のepsilon',exact:true}).selectOption(e);await r.getByRole('combobox',{name:'模式不等式のdelta',exact:true}).selectOption(d);await expect(svg(r)).toContainText(`exp(ε) = ${Math.exp(Number(e)).toFixed(3)}`);await expect(svg(r)).toContainText(`右辺 = ${(Math.exp(Number(e))*0.1+Number(d)).toFixed(3)}`);await expect(svg(r)).toContainText('全事象のDP証明ではない')}})
test('repeated same-target releases accumulate both privacy parameters rather than renewing the guarantee each time',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-unit-budget','公開を合成');for(const n of ['0','1','5','10','20']){await r.getByRole('combobox',{name:'同じ対象の模式公開回数',exact:true}).selectOption(n);await expect(svg(r)).toContainText(`累積 ε: ${(Number(n)*0.1).toFixed(1)}`);await expect(svg(r)).toContainText(`累積 δ: ${(Number(n)*0.000001).toFixed(6)}`);await expect(svg(r)).toContainText('無制限の公開にしない')}})
test('federated aggregation and output DP protect distinct stages and do not erase model inference risks',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-layers-fit','連合学習の経路');for(const v of ['none','aggregation','dp','both']){await r.getByRole('combobox',{name:'連合学習で検討する追加保護',exact:true}).selectOption(v);await expect(svg(r)).toContainText(['aggregation','both'].includes(v)?'集約の保護候補':'共有時の漏えい');await expect(svg(r)).toContainText(['dp','both'].includes(v)?'出力保護のDP候補':'公開後の推論経路');await expect(svg(r)).toContainText('集約の秘匿だけで')}})
test('minimization access mask and residual requirements remain necessary and do not establish compliance',async({page})=>{const r=await open(page,'privacy-enhancing-technologies','privacy-basic-selection','基本を尽くす');for(const v of ['minimize','access','mask','residual','none']){await r.getByRole('combobox',{name:'基本の設計で不足する条件',exact:true}).selectOption(v);await expect(svg(r)).toContainText(v==='none'?'追加保護を含め検討':'不足する基本と要件へ戻る');await expect(svg(r)).toContainText('再識別の不在は保証しない')}})
test('original ISO CD date and Claude text versus Files API scope remain bounded snapshots',async({page})=>{const r=await open(page,'content-provenance-and-detection','provenance-layers-loss','時点を保持');await expect(svg(r)).toContainText('2026-09-10');await expect(svg(r)).toContainText('発行済み規格ではない');await r.getByRole('button',{name:'対象の経路',exact:true}).click();for(const [v,t] of [['text','テキスト透かしの方式'],['file','Files APIで取得する経路']]){await r.getByRole('combobox',{name:'原文で区別する生成経路',exact:true}).selectOption(v);await expect(svg(r)).toContainText(t);await expect(svg(r)).toContainText('全生成物へ一般化しない')}})
test('PET rows and impersonation classes have separate readable text positions',async({page})=>{for(const [route,id,label,titles] of [['privacy-enhancing-technologies','privacy-layers-fit','五つの技術',['検出・mask','仮名化・匿名化','差分プライバシー','連合学習','秘密計算・TEE']],['deepfake-and-impersonation-defense','impersonation-callback-process','四つの類型',['電話の声','ビデオ会議','偽広告・声明','捜査・被害回復']]]){const r=await open(page,route,id,label);const positions=[];for(const title of titles){const b=await svg(r).locator('text').filter({hasText:title}).boundingBox();expect(b).not.toBeNull();positions.push(b)}for(let i=1;i<positions.length;i++)expect(positions[i].y).toBeGreaterThan(positions[i-1].y+positions[i-1].height)}})
test('original source dates mathematical inequality process tables and TODO remain without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:4183'});try{const p=await c.newPage();for(const [route,text] of [['content-provenance-and-detection','2026-09-10'],['deepfake-and-impersonation-defense','既知の正規'],['privacy-enhancing-technologies','プライバシー予算']]){await p.goto(`${base}/docs/security/${route}`);await expect(p.locator('article')).toContainText(text);await expect(p.locator('article h2').filter({hasText:'TODO・未確認事項'})).toBeVisible()}}finally{await c.close()}})
test('low PC manual pause and print preserve the original DP parameters and protection scope',async({page})=>{await page.setViewportSize({width:1280,height:720});await page.goto(`${base}/docs/security/privacy-enhancing-technologies`);const r=page.locator('[data-diagram-id="privacy-unit-budget"]');await r.getByRole('button',{name:'公開を合成',exact:true}).click();const play=r.getByRole('button',{name:'図解を再生',exact:true});await play.scrollIntoViewIfNeeded();await play.evaluate(el=>new Promise(resolve=>{const o=new IntersectionObserver(es=>{if(!es.at(-1)?.isIntersecting)return;o.disconnect();requestAnimationFrame(()=>requestAnimationFrame(resolve))});o.observe(el.closest('.aw-sticky'))}));await play.click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','playing');await r.getByRole('button',{name:'図解を一時停止',exact:true}).click();await expect(r.locator('.aw-diagram')).toHaveAttribute('data-mode','manual');await page.emulateMedia({media:'print'});await expect(svg(r)).toBeVisible();await expect(r.locator('.aw-timeline')).toBeHidden();await expect(page.locator('article')).toContainText('保護単位');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)})
